<div class="w3-row w3-padding-4 w3-large" >
    <div class="w3-col s12 m4 l4">
        Usuario:
    </div>
    <div class="w3-col s12 m8 l8">
        <input class="ui-text" type="text" id="txtuser" name="txtuser" value="" size="19" placeholder="Usuario" tabindex="2">
    </div>
</div>
<div class="w3-row w3-padding-4 w3-large" >
    <div class="w3-col s12 m4 l4">
        Contrase&ntilde;a:
    </div>
    <div class="w3-col s12 m8 l8">
        <input class="ui-text" type="password" id="txtpass" name="txtpass" value="" size="19" placeholder="Contrase&ntilde;a"  tabindex="3">
    </div>
</div>
<div class="w3-row w3-padding-4" >
    &nbsp;
</div>
<div class="w3-row w3-padding-6">
    <input type="button" id="btningreso" name="btningreso" value="Ingresar" tabindex="4">
    <div id="div_resp_logeo" align="center"></div>
</div>
<div class="w3-row w3-padding-4" >
    &nbsp;
</div>