<table style="width:1000;" border="0">
    <tr>
        <td style="width:520px;text-align:center;">
            <img 
                 src="<?php echo $this->util()->getImage('logo.jpg'); ?>"
                 width="510px"
                 height="450px" />
            <!--<img style="border:1px solid black;"
                 src="<?php echo $this->util()->getImage('banner-rimac-02.jpg'); ?>"
                 width="510px"
                 height="225px" />-->
        </td>
        <td>

            <div align="center" class="ui-widget ui-widget-content ui-corner-all" style="width: 460px;margin: 3px;">

                <div class="ui-widget ui-state-default ui-corner-top ui-title">
                    <label>Inicio de Sesi&oacute;n</label>
                </div>
                <table style="width: 100%;" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <td width="30">&nbsp;</td>
                        <td width="26">&nbsp;</td>
                        <td width="64">&nbsp;</td>
                        <td width="50">&nbsp;</td>
                        <td width="30">&nbsp;</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td colspan="3" align="center">
                            <img style="border:1px solid black;" id="logo" src="<?php echo $this->util()->getImage('escudo.jpg'); ?>"
                                 width="230"
                                 height="250" name="logo" id="logo">
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td colspan="3" align="center"><b><br><span style="font-size: 100%;"></span></b></td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <div id="div_resp_logeo" align="center"></div>
                        </td>
                    </tr>
                    <!--<tr>
			<td>&nbsp;</td>
			<td colspan="3">Local:</td>
			<td>&nbsp;</td>
		</tr>
	 	<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td colspan="2">
				<select style="width: 190px;" id="cboLocal">
					<?php #echo $this->util()->getComboContenedor('1000000346', '1000000347'); ?>
				</select>
				<!-- autocomplete="off" -->
                    </td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    </tr>

                    <tr>
                        <td>&nbsp;</td>
                        <td style="text-align:left;padding-left:80px;">Usuario:</td>
                        <td>
                            <input class="ui-text" type="text" id="txtuser" name="txtuser" value="" size="19" placeholder="Usuario">
                        </td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td style="text-align:left;padding-left:80px;">Contrase&ntilde;a:</td>
                        <td>
                            <input class="ui-text" type="password" id="txtpass" name="txtpass" value="" size="19" placeholder="Contrase&ntilde;a" >
                        </td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>

                            <!-- autocomplete="off" -->
                        </td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <!--
                    <tr>
                        <td>&nbsp;</td>
                        <td colspan="3">Nivel:</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td colspan="2">
                        <select id="cbnivel" name="cbnivel">
                            <option value="0">Trabajador</option>
                        </select>
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                    -->
                    <tr>
                        <td>&nbsp;</td>
                        <td colspan="3" align="center">
                            <input type="button" id="btningreso" name="btningreso" value="Ingresar">
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
</table>