<?php
$library = new Libreria_Pintar();
$TipoBusqueda = array(array("0", "GENERAL"), array("1", "ID"), array("2", "NOMBRE"), array("3", "SERIE"), array("4", "MARCA"));
?>
<div id="paneldPSM" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 100%;margin: 1px; height:95%;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Agregar Activos</label>
    </div>
    <div id="dialogPSM">
        <table class="ui-panelLayout-main">
            <tr>
                <td style="vertical-align: top;">
                    <table border="0" style="margin-left:45px;">
                        <tr>
                            <td>
                                <b> Datos Busqueda</b>
                            </td>
                        </tr>
                        <tr class="rowdatospsm" id="rowdatospsm">
                            <td style="text-align: left">
                                <select id="cbotipob" name="cbotipob" style="width:140px;">
                                    <?php echo $library->ContenidoCombo($TipoBusqueda, $this->ctipmon, 0); ?>
                                </select>
                            </td>
                            <td>Texto de busqueda:</td>
                            <TD colspan="3">
                                <input class="ui-text pnl" id="c_textbusqueda" onkeypress="if(event.keyCode==13){buscarActivos();}" style="width:100%" />
                            </TD>
                            <td> &nbsp;&nbsp;</td>
                            <td>
                                <button id="btnbuscarActivos" name="btnbuscarActivos" onclick="buscarActivos()">Buscar</button>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <input type="hidden" class="ui-text" id="txtidEntradaMat" value="<?php echo $this->identrdamat; ?>" style="width:99%" />
    <input type="hidden" class="ui-text" id="txtidDetEntradaMat" value="<?php echo $this->iddetentrada; ?>" style="width:99%" />
    <input type="text" class="ui-text" id="txtIdActivo" value="<?php echo $this->idActivos; ?>" style="width:99%" />
    <div id="dialogMensaje">
    </div>
    <div id="panelActivos" align="left" style="width: 99%;margin-left: 5px;">
        <table id="tblPSM"></table>
        <div id="ptblPSM">
        </div>
    </div>
    <br />

    <table border="0" style="margin-left:5px;">
        <tr class="rowdatospsm" id="rowdatospsm">
            <td>CANTIDAD:</td>
            <td style="text-align: left">
                <input class="ui-text pnl" id="txtCantidad" value="<?php echo $this->cantidad; ?>" style="width:100%" />
            </td>
            <td> &nbsp;&nbsp;</td>
            <td>P. UNITARIO:</td>
            <TD colspan="3">
                <input class="ui-text pnl" id="txtPrecioUnit" value="<?php echo $this->punitario; ?>" style="width:100%" />
            </TD>
            <td> &nbsp;&nbsp; </td>
        </tr>
        <tr>
            <td colspan="3"> &nbsp;&nbsp;</td>
            <td> &nbsp;&nbsp;</td>
            <td> <button id="btnAgregar" name="btnAgregar" onclick="addActivoAEntrada()">Agregar</button></td>
        </tr>
    </table>
</div>

<script type="text/javascript">
    themeComboBox();

    $("#txtnombre").keyup(function(event) {
        buscarPServ();
        document.getElementById("txtnombre").focus();
    }).keydown(function(event) {
        if (event.which == 13) {

        }
    });
    $("#txtdescri").keyup(function(event) {
        buscarActivos();
        document.getElementById("txtdescri").focus();
    }).keydown(function(event) {
        if (event.which == 13) {

        }
    });

    $('#txtPrecioUnit').on('keypress', function(e) {

        var field = $(this);
        key = e.keyCode ? e.keyCode : e.which;

        if (key == 8) return true;
        if (key > 47 && key < 58) {
            if (field.val() === "") return true;
            var existePto = (/[.]/).test(field.val());
            if (existePto === false) {
                regexp = /.[0-9]{10}$/;
            } else {
                regexp = /.[0-9]{2}$/;
            }

            return !(regexp.test(field.val()));
        }
        if (key == 46) {
            if (field.val() === "") return false;
            regexp = /^[0-9]+$/;
            return regexp.test(field.val());
        }
        return false;
    });
    $('#txtCantidad').on('keypress', function(e) {

        var field = $(this);
        key = e.keyCode ? e.keyCode : e.which;

        if (key == 8) return true;
        if (key > 47 && key < 58) {
            if (field.val() === "") return true;
            var existePto = (/[.]/).test(field.val());
            if (existePto === false) {
                regexp = /.[0-9]{10}$/;
            } else {
                regexp = /.[0-9]{2}$/;
            }

            return !(regexp.test(field.val()));
        }
        return false;
    });

    var lastsel3;
    optionPSM = {
        width: 530,
        height: 250,
        colNames: [
            'Codigo',
            'Nombre',
            'Marca',
            'Stock',
            'Serie',
            'Estado'
        ],
        colModel: [{
                name: 'idActivos',
                index: 'idActivos',
                width: 60
            },
            {
                name: 'vNombre',
                index: 'vNombre',
                width: 150
            },
            {
                name: 'vMarca',
                index: 'vMarca',
                width: 100
            },
            {
                name: 'nStock',
                index: 'nStock',
                width: 70
            },
            {
                name: 'vSerie',
                index: 'vSerie',
                width: 150
            },
            {
                name: 'vEstado',
                index: 'vEstado',
                width: 50,
                hidden: true,
                editOptions: {
                    value: "1:0",
                    defaultvalue: "1"
                },
                formatter: 'checkbox'
            }
        ],
        ignoreCase: true,
        caption: "&nbsp;&nbsp;&nbsp;Materiales Registrados",
        ondblClickRow: function(id) {
            var row = $(this).getRowData(id);
            addActivoAEntrada();
        },

        afterInsertRow: function(rowid, aData) {
            switch (
                aData.nestado
            ) {
                case '1':
                    break;
                case '0':

                    jQuery("#tblPSM").jqGrid('setCell', rowid, 'cidpers', '', {
                        color: 'red'
                    });
                    jQuery("#tblPSM").jqGrid('setCell', rowid, 'crazsoc', '', {
                        color: 'red'
                    });
                    jQuery("#tblPSM").jqGrid('setCell', rowid, 'vnrodoc', '', {
                        color: 'red'
                    });
                    jQuery("#tblPSM").jqGrid('setCell', rowid, 'nestado', '', {
                        color: 'red'
                    });
                    break;
            }
        },
        onSelectRow: function(id) {
            var row = $(this).getRowData(id);
        },
        gridComplete: function() {
            isGridComplete = true;
            $("#tblPSM").jqGrid('setSelection', 1, true);
        }
    };

    eliminar = function(a) {
        var selr = $('#tblPSM').jqGrid('getGridParam', 'selrow');
        var row = $("#tblPSM").jqGrid('getRowData', selr);
        if (row.cidpers == "" || row.cidpers == undefined) {
            openDialogWarning("Seleccione un registro para eliminar.");
            return;
        }
        parameters = {
            "idsigma": row.cidpers
        };
        openDialogConfirm1("\u00BFEst\u00E1 seguro de eliminar datos?", 350, {

            "si": function() {
                $.ajax({
                    url: jQuery.scriptPath + "index.php/mantenimientos/eliminarpersona",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function(data) {

                    },
                    success: function(requestData) {
                        $("#result").html(requestData);
                        closeDialog("jqDialogConfirmacion1");
                        closeDialog('jqDialog2');
                        closeDialog('jqDialog1');
                    },
                    error: function(requestData, strError, strTipoError) {
                        $("#result").html("Error " + strTipoError + ': ' + strError);
                    },
                    complete: function(requestData, exito) {}
                });
            },
            "no": function() {
                closeDialog("jqDialogConfirmacion1");
            }
        })
    };

    addActivoAEntrada = function(a) {
        var selr = $('#tblPSM').jqGrid('getGridParam', 'selrow');
        var row = $("#tblPSM").jqGrid('getRowData', selr);
        if (row.idActivos == "" || row.idActivos == undefined) {
            openDialogWarning("Seleccione un registro.");
            return;
        }
        if ($("#txtidEntradaMat").val() == "") {
            openDialogWarning("Primero debe buscar el proveedor.");
            return;
        }
        if ($("#txtCantidad").val() == "") {
            openDialogWarning("Agregar Cantidad.");
            return;
        }
        if ($("#txtPrecioUnit").val() == "") {
            openDialogWarning("Agregar Precio Unitario.");
            return;
        }
        parameters = {
            "id": row.idActivos,
            "identradaActivo": $("#txtidEntradaMat").val(),
            "iddetentradaActivo": $("#txtidDetEntradaMat").val(),
            "Cantidad": $("#txtCantidad").val(),
            "PrecioUnitario": $("#txtPrecioUnit").val()
        };

        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/detentradaactivoadd",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function(data) {},
            success: function(requestData) {
                $("#result").html(requestData);
                var datos = JSON.parse(requestData);
                console.log(datos[0].ok);
                closeDialog("jqDialogConfirmacion1");
                closeDialog('jqDialog1');
                buscarDetEntradaActivos();
            },
            error: function(requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function(requestData, exito) {}
        });

    };

    nuevoActivo = function() {
        parameters = {
            "idsigma": '...'
        };
        openDialogData3("mantenimientos/activos", parameters, 500);
    };
    verActivos = function() {
        var selr = $('#tblPSM').jqGrid('getGridParam', 'selrow');
        var row = $("#tblPSM").jqGrid('getRowData', selr);
        console.log(row.idActivos);
        if (row.idActivos == "" || row.idActivos == undefined) {
            openDialogWarning("Seleccione un registro para editar.");
            return;
        }
        parameters = {
            "idsigma": row.idActivos
        };
        openDialogData3("mantenimientos/activos", parameters, 500);
    };

    function buttonsGridPSM() {
        $("#tblPSM").navGrid('#ptblPSM', {
                edit: false,
                add: false,
                del: false,
                search: false,
                refresh: false
            })

            .navButtonAdd('#ptblPSM', {
                caption: "Agregar&nbsp;&nbsp;",
                buttonicon: "ui-icon-plus",
                onClickButton: function() {
                    nuevoActivo();
                },
                position: "last"
            })
            .navButtonAdd('#ptblPSM', {
                caption: "Editar&nbsp;&nbsp;",
                buttonicon: "ui-icon-pencil",
                onClickButton: function() {
                    verActivos();
                },
                position: "last"
            });
        $("#tblPSM").jqGrid('filterToolbar', {
            stringResult: true,
            searchOnEnter: false,
            defaultSearch: 'cn',
            ignoreCase: true
        });
    }

    buscarActivos = function() {
        if ($("#txtIdActivo").val()) {

        }
        var params = '[' +
            '["@tBusqueda", "' + $("#cbotipob").val() + '"],' +
            '["@vDatoBus", "' + $("#c_textbusqueda").val() + '"]' +
            ']';
        parameters = {
            "name": "tblListaMate",
            "procedure": "almacen.Bus_Activos",
            "print": "true",
            "parameters": params
        };
        procesarProcedimientoJSON(
            "panelActivos", "tblPSM", optionPSM, parameters, null, buttonsGridPSM
        );
    };
    buscarActivosPrimeravez = function() {
        var tbus = "";
        if ($("#txtIdActivo").val() != "") {
            tbus = "1";
        } else {
            tbus = "0";
        }
        var params = '[' +
            '["@tBusqueda", "' + tbus + '"],' +
            '["@vDatoBus", "' + $("#txtIdActivo").val() + '"]' +
            ']';
        parameters = {
            "name": "tblListaMate",
            "procedure": "almacen.Bus_Activos",
            "print": "true",
            "parameters": params
        };
        procesarProcedimientoJSON(
            "panelActivos", "tblPSM", optionPSM, parameters, null, buttonsGridPSM
        );
    };
    $(function() {
        buscarActivosPrimeravez();
        $("#btnbuscarActivos").button({
            icons: {
                primary: "ui-icon-search"
            }
        });
        $("#btnAgregar").button(ICON_SAVE);
    });
</script>