<?php
$library = new Libreria_Pintar();
$TipoBusqueda=array(array("0","GENERAL"), array("1","ID"), array("2","NOMBRE"), array("3","TIPOMATERIAL"), array("4","MARCA"));
?>
<div id="paneldProd" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 100%;margin: 1px; height:95%;">
    <div class="ui-widget ui-state-rombo ui-corner-top ui-title">
        <label>Agregar Producto</label>
    </div>
    <div id="dialogProducto">
        <table border="0" style="margin-left:5px;">
            <tr>

                <td width="150" style="text-align: left">Categoria:</td>
                <td width="150" class="clprod" style="text-align: left">SubCategoria:</td>
                <input class="ui-text" id="idpag" type="hidden" value="<?php echo $this->pag;?>" >


                <td> </td>

            </tr>
            <tr class="rowdatospsm" id="rowdatospsm">

                <td width="10"> <select id="cbocategor" name="cbocategor" style="width:120px;">
                        <?php  echo $this->util()->getComboContenedorOtro( '1',$this->idcat,'Cmb_Categoria','@idCat'); ?>
                    </select></td>

                <td  class="clprod" style="display: inline">
                    <select id="cbocsubcateg" name="cbocsubcateg"  style="width:130px;">
                        <?php  echo $this->util()->getComboContenedorOtro1( '1',$this->idSubCat,'Cmb_SubCategorias','@idCat'); ?>
                    </select>
                </td>



                <td>
                    <button id="btnbuscarProd" name="btnbuscarProd" onclick="buscarProd()">Buscar</button>
                </td>
            </tr>
        </table>

    </div>
    <input type="hidden" class="ui-text"  id="txtidEntradaProd" value="<?php echo $this->identradaprod; ?>" style="width:99%" />
    <input type="hidden" class="ui-text"  id="txtidDetEntradaProd" value="<?php echo $this->iddetentrada; ?>" style="width:99%" />
    <input type="hidden" class="ui-text"  id="txtidProducto" value="<?php echo $this->idProducto; ?>" style="width:99%" />
    <div id="dialogMensaje">
    </div>
    <div id="panelProduct" align="left" style="width: 99%;margin-left: 5px;">
        <table id="tblProduct"></table>
        <div id="tblProduct">
        </div>
    </div>



    </div>

<script type="text/javascript">
    themeComboBox();

    var lastsel3;
    optionProd = {
        width: 600,
        height: 270,
        colNames: [
            'Id',
            'IdEntrada',
            'idProducto',
            'Producto',
            'nStock',
            'Nro Serie',
            'vEstAlmacen',
            'vEstado'
        ],
        colModel: [
            {name: 'idProdSeries', index:'idProdSeries', width:50,search:false},
            {name: 'idDetEntradaProd', index:'idDetEntradaProd', width:50,search:false,hidden:true},
            {name: 'idProducto', index:'idProducto', width:50,search:false},
            {name: 'producto', index:'producto', width:260},
            {name: 'nStock', index:'nStock', width:200,hidden:true},
            {name: 'vNroSerie', index:'vNroSerie', width:240},
            {name: 'vEstAlmacen', index:'vEstAlmacen', width:250,hidden:true},
            {name: 'vEstado', index:'vEstado', width:20,editable: false,hidden:true}
        ],
        ignoreCase:true,
        caption: "&nbsp;&nbsp;&nbsp;Productos Registrados",
        ondblClickRow: function(id){
            var row = $(this).getRowData(id);
            console.log(row);

            addnuevosoporteSERIE();
        },

        afterInsertRow:function(rowid,aData){
            switch(
                aData.vEstado
                ){case'1':
                break;
                case '0':

                    jQuery("#tblProduct").jqGrid('setCell',rowid,'producto','',{color:'red'});
                    jQuery("#tblProduct").jqGrid('setCell',rowid,'vNroSerie','',{color:'red'});
                    jQuery("#tblProduct").jqGrid('setCell',rowid,'vEstAlmacen','',{color:'red'});
                    jQuery("#tblProduct").jqGrid('setCell',rowid,'vEstado','',{color:'red'});
                    break;
            }
        },
        onSelectRow: function(id) {
            var row = $(this).getRowData(id);
        }
    };


    addnuevosoporteSERIE = function() {
        var selr = $('#tblProduct').jqGrid('getGridParam','selrow');
        var row = $("#tblProduct").jqGrid('getRowData', selr);
        if(row.idProducto == "" || row.idProducto == undefined){
            openDialogWarning("Seleccione un registro.");
            return;
        }
        parameters = {
            "idsigma": row.idProducto,
            "idEntrada": $("#identrada").val()
        };

        $("#codigoprod").val(row.idProducto);
        $("#codprodseries").val(row.idProdSeries);
        $("#nombreprod").html(row.producto);
        $("#txtserie").val(row.vNroSerie);

        closeDialog("jqDialog1");
    };

    addDetEntradaProd=function(a){
        var selr = $('#tblProduct').jqGrid('getGridParam','selrow');
        var row = $("#tblProduct").jqGrid('getRowData', selr);
        if(row.id == "" || row.id == undefined){
            openDialogWarning("Seleccione un registro.");
            return;
        }
        if( $("#txtidEntradaProd").val()==""){
            openDialogWarning("Primero debe buscar el proveedor.");
            return;
        }


        parameters = {
            "id": row.id,
            "identradaprod":  $("#txtidEntradaProd").val(),
            "iddetentradaprod":  $("#txtidDetEntradaProd").val()

        };


        openDialogConfirm1("\u00BFEst\u00E1 seguro de agregar el Producto?",350,{
            "si":function(){
                $.ajax({
                    url: jQuery.scriptPath + "index.php/almacen/detentradaprodadd",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function (data) {
                    },
                    success: function (requestData) {
                        $("#result").html(requestData);
                        var datos=JSON.parse(requestData);
                        console.log(datos[0].ok);
                        closeDialog("jqDialogConfirmacion1");
                        closeDialog('jqDialog1');
                        buscarDetEntradaProd();
                    },
                    error: function (requestData, strError, strTipoError) {
                        $("#result").html("Error " + strTipoError + ': ' + strError);
                    },
                    complete: function (requestData, exito) {
                    }
                });
            },
            "no":function(){
                closeDialog("jqDialogConfirmacion1");
            }
        })
    };



    nuevaProducto = function(){
        parameters = {
            "idsigma": '...'
        };
        openDialogData2("mantenimientos/producto", parameters, 460);
    };

    editProd = function() {
        var selr = $('#tblProduct').jqGrid('getGridParam','selrow');
        var row = $("#tblProduct").jqGrid('getRowData', selr);
        if(row.id == "" || row.id == undefined){
            openDialogWarning("Seleccione un registro para editar.");
            return;
        }
        parameters = {
            "idsigma": row.id
        };

        openDialogData2("mantenimientos/producto", parameters, 460);

    };

    function buttonsGridProducto(){
        $("#tblProduct").navGrid('#ptblProduct', {edit:false,add:false,del:false,search:false,refresh:false})
/*
            .navButtonAdd('#ptblProduct',{
                caption:"Agregar&nbsp;&nbsp;",
                buttonicon:"ui-icon-plus",
                onClickButton: function(){
                    nuevaProducto();
                },
                position:"last"
            })
         .navButtonAdd('#ptblProduct',{
                caption:"Editar&nbsp;&nbsp;",
                buttonicon:"ui-icon-pencil",
                onClickButton: function(){
                    editProd();
                },
                position:"last"
            })
        ;*/
        $("#tblProduct").jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, defaultSearch: 'cn', ignoreCase: true});
    }

    function reiniCombo(celement){
        var xelem = $("#" + celement);
        xelem.combobox("destroy");
        $("option:selected",xelem).removeAttr("selected");
        $("option[value='9999999999']",xelem).attr("selected", "selected");
        //xelem.combobox();
    }
    function getSubcategoria(selecteds, celement){
        if (selecteds == "9999999999" || selecteds == ""){
            $("#" + celement).html("<option value='9999999999'>SELECCIONE</option>");
            $("#" + celement).val("9999999999");
        }else{
            $.ajax({
                dataType: "html",
                type: "POST",
                url: path + "mantenimientos/obtenersubcate1/",
                data: "select="+selecteds+"&subcat=",
                success: function(requestData){ 	//Llamada exitosa)
                    $("#" + celement).html(requestData);
                    $("#" + celement).combobox({
                        selected: function(event, ui){
                         buscarProd();
                        }
                    });
                },
                error: function(requestData, errNumber, errMessage){
                }
            });
        }
    }
    $("#cbocategor").combobox({
        selected: function(event, ui){
            reiniCombo("cbocsubcateg");
            getSubcategoria($("#cbocategor").val(),"cbocsubcateg");
            buscarProd();
        }
    });

    $("#cbocsubcateg").combobox({
        selected: function(event, ui){
            buscarProd();

        }
    });


   var PROCEDIMIENTO_BUSCAR_SERIES= "almacen.Bus_ProdSeries";
   obtenerParameterSeriesSalida= function() {
        return '[' +
            '["@tBusqueda", "0"],' +
            '["@vDatoBus", ""]' +
            ']';

    };
    buscarProd = function() {
        var cate= $("#cbocategor").val();
        var subcate= $("#cbocsubcateg").val();
        if(cate=='9999999999'){
            cate='';
        }

        if(subcate=='9999999999'){
            subcate='';
        }



        parameters = {
            "name": "tblListaMate",
            "procedure": PROCEDIMIENTO_BUSCAR_SERIES,
            "print": "true",
            "parameters": obtenerParameterSeriesSalida
        };
        procesarProcedimientoJSON(
            "panelProduct"
            , "tblProduct"
            , optionProd
            , parameters
            , null
            , buttonsGridProducto
        );
    };

    $(function(){
        buscarProd();
         $("#btnbuscarProd").button(ICON_SEARCH);
        reiniCombo("cbocsubcateg");
        getSubcategoria($("#cbocategor").val(),"cbocsubcateg");
    });
</script>