<div id="panelMantenimientoPersonas" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 100%;margin: 3px; height:95%;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Buscador de personas</label>
    </div>
    <div id="dialogBuscarContribuyentePredio">
        <table class="ui-panelLayout-main">
            <tr>
                <td style="vertical-align: top;">
                    <table border="0" style="margin-left:15px;">
                        <tr class="rowBuscarContribuyente">
                            <input class="ui-text" id="identrada" type="hidden" value="<?php echo $this->idsigma; ?>">
                            <input class="ui-text" id="idpag" type="hidden" value="<?php echo $this->pag; ?>">
                            <td width="100" style="text-align: left">C&oacute;digo:</td>
                            <td width="10">&nbsp;</td>
                            <td width="180" style="text-align: left">Apellidos y Nombre:</td>
                            <td width="10">&nbsp;</td>
                            <td width="100">&nbsp;</td>
                            <td width="10">&nbsp;</td>
                            <td width="100" colspan="3" style="text-align: left">Nro. Documento:</td>
                            <td width="20">&nbsp;</td>
                        </tr>
                        <tr class="rowBuscarContribuyente" id="panelBuscarContribuyente">

                            <td>
                                <input class="ui-text" id="c_codigocontrib" onkeypress="if(event.keyCode==13){buscarPersona();}" maxlength="10" style="width:90px" />
                            </td>
                            <td>&nbsp;</td>
                            <td colspan="3">
                                <input class="ui-text pnl" id="c_nombrecontrib" onkeypress="if(event.keyCode==13){buscarPersona();}" style="width:100%" />
                            </td>
                            <td>&nbsp;</td>
                            <td colspan="3" style="text-align: left;">
                                <input class="ui-text pnl" id="c_nrodoc" onkeypress="if(event.keyCode==13){buscarPersona();}" style="width:80%" />
                            </td>
                            <td>
                                <button id="btnbuscarC" name="btnbuscarC" onclick="buscarPersona()">Buscar</button>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <div id="dialogMensaje">
    </div>

    <div id="panelListaPersona" align="left" style="width: 99%;margin-left: 5px;">
        <table id="tblListaPersona"></table>
        <div id="ptblListaPersona"></div>
    </div>
</div>
<script type="text/javascript">
    $("#c_nombrecontrib").keyup(function(event) {
        buscarPersona();
        document.getElementById("c_nombrecontrib").focus();
    }).keydown(function(event) {
        if (event.which == 13) {
            buscarPersona();
        }
    });

    $("#c_nrodoc").keyup(function(event) {
        buscarPersona();
        document.getElementById("c_nrodoc").focus();
    }).keydown(function(event) {
        if (event.which == 13) {
            buscarPersona();
        }
    });


    optionPersona = {
        width: 620,
        height: 250,
        colNames: [
            'Codigo',
            'Proveedor',
            'Tippers',
            'vtipdoc',
            'Nro Doc',
            "Persona Contacto",
            "Estado"
        ],
        colModel: [{
                name: 'idProveedor',
                index: 'idProveedor',
                width: 70
            },
            {
                name: 'vNombre',
                index: 'vNombre',
                width: 250
            },
            {
                name: 'vTipPers',
                index: 'vTipPers',
                width: 100,
                hidden: false
            },
            {
                name: 'vTipoDoc',
                index: 'vTipoDoc',
                hidden: true
            },
            {
                name: 'vNroDoc',
                index: 'vNroDoc',
                width: 60,
                hidden: false
            },
            {
                name: 'vPersContac',
                index: 'vPersContac',
                width: 100,
                hidden: false
            },
            {
                name: 'vEstado',
                index: 'vEstado',
                hidden: true
            }
        ],
        caption: "&nbsp;&nbsp;&nbsp;Proveedores Registradas",
        ondblClickRow: function(id) {
            var row = $(this).getRowData(id);
            //console.log(row);
            if ($("#idpag").val() == "1") { //##detentradamat
                addIngresoMat();
            }
            if ($("#idpag").val() == "3") { //##detentradaactivos
                addIngresoActivos();
            } else { //##detentradaprod
                addIngresoProd();
            }

        },
        afterInsertRow: function(rowid, aData) {
            switch (aData.nestado) {
                case '1':
                    break;
                case '0':
                    jQuery("#tblListaPersona").jqGrid('setCell', rowid, 'idProveedor', '', {
                        color: 'red'
                    });
                    jQuery("#tblListaPersona").jqGrid('setCell', rowid, 'vNombre', '', {
                        color: 'red'
                    });
                    jQuery("#tblListaPersona").jqGrid('setCell', rowid, 'direccf', '', {
                        color: 'red'
                    });
                    jQuery("#tblListaPersona").jqGrid('setCell', rowid, 'vnrodoc', '', {
                        color: 'red'
                    });
                    break;
            }
        },
        onSelectRow: function(id) {
            var row = $(this).getRowData(id);
        }
    };


    eliminar = function(a) {
        var selr = $('#tblListaPersona').jqGrid('getGridParam', 'selrow');
        var row = $("#tblListaPersona").jqGrid('getRowData', selr);
        if (row.idProveedor == "" || row.idProveedor == undefined) {
            openDialogWarning("Seleccione un registro para eliminar.");
            return;
        }
        parameters = {
            "idsigma": row.idProveedor
        };
        openDialogConfirm1("\u00BFEst\u00E1 seguro de eliminar datos?", 350, {
            "si": function() {
                $.ajax({
                    url: jQuery.scriptPath + "index.php/mantenimientos/eliminarpersona",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function(data) {

                    },
                    success: function(requestData) {
                        $("#result").html(requestData);
                        closeDialog("jqDialogConfirmacion1");
                        closeDialog('jqDialog1');
                    },
                    error: function(requestData, strError, strTipoError) {
                        $("#result").html("Error " + strTipoError + ': ' + strError);
                    },
                    complete: function(requestData, exito) {}
                });
            },
            "no": function() {
                closeDialog("jqDialogConfirmacion1");
            }
        })


    };

    addIngresoActivos = function() {
        var selr = $('#tblListaPersona').jqGrid('getGridParam', 'selrow');
        var row = $("#tblListaPersona").jqGrid('getRowData', selr);
        if (row.idProveedor == "" || row.idProveedor == undefined) {
            openDialogWarning("Seleccione un registro.");
            return;
        }
        parameters = {
            "idsigma": row.idProveedor,
            "idEntrada": $("#identrada").val()
        };

        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/entradaactivossave",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function(data) {

            },
            success: function(requestData) {
                //$("#result").html(requestData);
                var datos = JSON.parse(requestData);
                closeDialog('jqDialog2');
                closeDialog('jqDialog1');
                $("#identradamat").val(datos[0].idEntrada);
                $("#txtidProveedor").val(row.idProveedor);
                $("#nombrecontrib").val(row.vNombre);
                // buscarDetEntradaMat(); //22-12-2020
            },
            error: function(requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function(requestData, exito) {}
        });

    };

    addIngresoMat = function() {
        var selr = $('#tblListaPersona').jqGrid('getGridParam', 'selrow');
        var row = $("#tblListaPersona").jqGrid('getRowData', selr);
        if (row.idProveedor == "" || row.idProveedor == undefined) {
            openDialogWarning("Seleccione un registro.");
            return;
        }
        parameters = {
            "idsigma": row.idProveedor,
            "idEntrada": $("#identrada").val()
        };

        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/entradamatsave",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function(data) {

            },
            success: function(requestData) {
                //$("#result").html(requestData);
                var datos = JSON.parse(requestData);
                closeDialog('jqDialog2');
                closeDialog('jqDialog1');
                $("#identradamat").val(datos[0].idEntrada);
                $("#txtidProveedor").val(row.idProveedor);
                $("#nombrecontrib").val(row.vNombre);
                // buscarDetEntradaMat(); //22-12-2020
            },
            error: function(requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function(requestData, exito) {}
        });

    };
    addIngresoProd = function() {
        var selr = $('#tblListaPersona').jqGrid('getGridParam', 'selrow');
        var row = $("#tblListaPersona").jqGrid('getRowData', selr);
        if (row.idProveedor == "" || row.idProveedor == undefined) {
            openDialogWarning("Seleccione un registro.");
            return;
        }
        parameters = {
            "idsigma": row.idProveedor,
            "idEntrada": $("#identrada").val()
        };

        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/entradaprodsave",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function(data) {

            },
            success: function(requestData) {
                //$("#result").html(requestData);
                var datos = JSON.parse(requestData);
                closeDialog('jqDialog2');
                closeDialog('jqDialog1');
                $("#identradaprod").val(datos[0].idEntrada);
                $("#txtidProveedor").val(row.idProveedor);
                $("#nombrecontrib").val(row.vNombre);
                //buscarDetEntradaProd();  //22-12-2020
            },
            error: function(requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function(requestData, exito) {}
        });

    };


    nuevaPersona = function() {
        parameters = {
            "idsigma": '0000000000'
        };
        openDialogData2("mantenimientos/proveedor", parameters, 460);
    };

    verPersona = function() {
        var selr = $('#tblListaPersona').jqGrid('getGridParam', 'selrow');
        var row = $("#tblListaPersona").jqGrid('getRowData', selr);
        if (row.idProveedor == "" || row.idProveedor == undefined) {
            openDialogWarning("Seleccione un registro para editar.");
            return;
        }
        parameters = {
            "idsigma": row.idProveedor
        };

        openDialogData2("mantenimientos/proveedor", parameters, 460);

    };

    estadoPersona = function() {
        var selr = $('#tblListaPersona').jqGrid('getGridParam', 'selrow');
        var row = $("#tblListaPersona").jqGrid('getRowData', selr);
        if (row.idProveedor == "" || row.idProveedor == undefined) {
            openDialogWarning("Seleccione un registro para editar.");
            return;
        }
        parameters = {
            "idsigma": row.idProveedor
        };

        openDialogData1("mantenimientos/estados", {
            codigo: row.idProveedor
        }, )

    };


    function buttonsGridPerson() {
        $("#tblListaPersona")
            .navGrid('#ptblListaPersona', {
                edit: false,
                add: false,
                del: false,
                search: false,
                refresh: false
            })

            .navButtonAdd('#ptblListaPersona', {
                caption: "Agregar&nbsp;&nbsp;",
                buttonicon: "ui-icon-plus",
                onClickButton: function() {
                    nuevaPersona();
                },
                position: "last"
            })
            .navSeparatorAdd()


            .navButtonAdd('#ptblListaPersona', {
                caption: "Editar&nbsp;&nbsp;",
                buttonicon: "ui-icon-pencil",
                onClickButton: function() {
                    verPersona();
                },
                position: "last"
            })
            .navSeparatorAdd()
        /*
        .navButtonAdd('#ptblListaPersona',{
            caption:"Eliminar&nbsp;&nbsp;",
            buttonicon:"ui-icon-pencil",
            onClickButton: function(){
                eliminar();
            },
            position:"last"
        })
        .navSeparatorAdd()

        .navButtonAdd('#ptblListaPersona',{
            caption:"Imprimir&nbsp;&nbsp;",
            buttonicon:"ui-icon-pencil",
            onClickButton: function(){
         imprimirperso();
            },
            position:"last"
        })
        .navSeparatorAdd()*/
        ;
    }


    function imprimirperso() {
        var selr = $('#tblListaPersona').jqGrid('getGridParam', 'selrow');
        var row = $("#tblListaPersona").jqGrid('getRowData', selr);
        //console.log(row);
        //window.open(pathRpt+"tipo=pdf&nombrereporte=imprimir&param=codidopersona^"+row.idProveedor );
    }

    buscarPersona = function() {
        var params = '[' +
            '["@codigo", "' + $("#c_codigocontrib").val() + '"],' +
            '["@nombres", "' + $("#c_nombrecontrib").val() + '"],' +
            '["@documento", "' + $("#c_nrodoc").val() + '"]' +
            ']';
        parameters = {
            "name": "tblListaPersona",
            "procedure": "Bus_Proveedor",
            "print": "true",
            "parameters": params
        };

        procesarProcedimientoJSON(
            "panelListaPersona", "tblListaPersona", optionPersona, parameters, null, buttonsGridPerson
        );
    };

    $(function() {
        buscarPersona();
        $("#btnbuscarC").button({
            icons: {
                primary: "ui-icon-search"
            }
        });
    });
</script>