<?php
$library = new Libreria_Pintar();
$TipoMoneda=array(array("1","Dolares"), array("2","Soles"));

?>


<div  id="panelMantenimientoEntradaProd" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 99%;margin: 1px; height:95%;">
    <div class="ui-widget ui-state-verde ui-corner-top ui-title">
        <label>Mantenimiento - Entrada Productos</label>
    </div>
    <input type="hidden" id="identradaprod" name="identradaprod" value="<?php echo $this->idEntradaProd;?>">
    <div id="dialogBuscarContribuyentePredio">
        <table class="ui-panelLayout-main" >
            <tr>
                <td style="vertical-align: top;">
                    <table border="0" style="margin-left:45px;">
                        <tr>
                            <td>
                              <b>  Datos Proveedor </b>
                            </td></tr>
                        <tr class="rowBuscarContribuyente">

                            <td width="100" style="text-align: left">C&oacute;digo:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" style="text-align: left">Rason Social:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230">&nbsp;</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" colspan="5" style="text-align: left"></td>
                            <td width="150">&nbsp;</td>
                        </tr>
                        <tr class="rowBuscarContribuyente" id="panelBuscarContribuyente">

                            <td>
                                <input class="ui-text-disable" readonly id="codigocontrib" value="<?php echo $this->idProveedor;?>"  maxlength="10" style="width:90px" />
                            </td>
                            <td>&nbsp;</td>
                            <td colspan="3">
                                <input class="ui-text-disable pnl" readonly id="nombrecontrib"  value="<?php echo $this->nombreproveed;?>"  style="width:100%" />
                            </td>
                            <td>&nbsp;</td>
                            <td colspan="5" style="text-align: left;">
                               <!-- <input class="ui-text-disable pnl" readonly id="nrodoc"   value="<?php echo $this->vnrodoprov;?>"  style="width:50%" /> -->
                            </td>
                            <td rowspan="1">
                                <button id="btnbuscar" name="btnbuscar" onclick="buscarProveedor()">Buscar Proveedor</button>
                            </td>
                        </tr>
                        <tr><td>
                                <b>  Datos Compra</b>
                            </td></tr>
                        <tr class="rowcoti">

                            <td width="100" style="text-align: left">Fecha:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" style="text-align: left">Factura</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" style="text-align: left">Tipo Moneda</td>
                        </tr>

                        <tr class="rowbcoti" id="panelbcoti">

                            <td>
                                <input type="text" id="fecdesde" value="<?php echo $this->dfecentrada;?>"  class="ui-text-disable " readonly style="text-align: left;width: 80px;"/>
                            </td>
                            <td>&nbsp;</td>
                            <td class="soloSolesa">&nbsp;<input type="text" class="ui-text pnl" id="txtfactura"   value="<?php  echo $this->nrofactura; ?>"  style="width:96%" /></td>

                            <td>&nbsp;
                            </td>

                            <td colspan="2">
                                <select id="cbtipomon" name="cbtipomon" style="width:140px;">
                                    <?php  echo $library->ContenidoCombo($TipoMoneda, $this->ctipmon,0); ?>
                                </select>

                            </td>
                        </tr>

                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <div id="dialogMensaje">
    </div>
    <div id="panelDetEntradaProd" align="left" style="width: 99%;margin-left: 15px; margin-right: 15px;">
        <table id="tblDetEntradaProd"></table>
        <div id="ptblDetEntradaProd">
        </div>
    </div>
    <br/>


<div align="right">
    <table border="0" style=" margin-left: 45px; margin-right: 45px">
        <tr  style="width:20%;">
            <td align="right"><b>Sub Total:</b></td>
            <td ><b>
                    <input type="text" class="ui-text-disable" readonly id="txtsubtotal" value="<?php echo $this->subtotal;?>"  maxlength="20" style="width:90px; text-align: right" />
                </b></td>
        </tr>
        <tr align="right">
            <td><b>IGV:</b></td>
            <td ><b> <input  type="text"  class="ui-text-disable" readonly id="txtigv" value="<?php echo $this->igv;?>"  maxlength="20" style="width:90px; text-align: right" /></b></td>
        </tr>
        <tr align="right">
            <td><b>Total:</b></td>
            <td><b> <input  type="text" class="ui-text-disable" readonly id="txttotal" value="<?php echo $this->total;?>"  maxlength="20" style="width:90px; text-align: right" /></b></td>
        </tr>

        <tr>
            <td><button id="btncancelardet" name="btncancelardet">Cancelar</button></td>
        <td>
            <button id="btnguardar" name="btnguardar" onclick="GuardardetalleEProd()">Guardar</button>
        </td>
        </tr>


    </table>
    </div>
    <table id="list4"></table>
    <br/>
</div>
<div class="contextMenu" id="myMenu1" style="display:none">
    <ul style="width: 200px">
        <li id="add">
            <span class="ui-icon ui-icon-plus" style="float:left"></span>
            <span style="font-size:11px; font-family:Verdana">Agregar</span>
        </li>
        <li id="edit">
            <span class="ui-icon ui-icon-pencil" style="float:left"></span>
            <span style="font-size:11px; font-family:Verdana">Editar</span>
        </li>
        <li id="del">
            <span class="ui-icon ui-icon-trash" style="float:left"></span>
            <span style="font-size:11px; font-family:Verdana">Eliminar</span>
        </li>
    </ul>
</div>
<script language="javascript">
    document.onkeydown = function(){
// a presonar el f5 se actuliza la misma pagina..
        if(window.event && window.event.keyCode == 116) {
            window.status="Por favor, Haga Click en Cerrar Sesión Para Salir del Sistema de Auditoría de Servicios";
            if (confirm('¿Estás seguro que deseas salir de la actual página?')) {
               // alert("Pulsada la tecla F5");
            }else{
                return false;
            }

        }

        /*if(window.event && window.event.keyCode == 8){	// cuando el usuario presione el boton retroceso o borrar no regrese atras
          window.status="Por favor, Haga Click en Cerrar Sesión Para Salir del Sistema de Auditoría de Servicios";
            return false;
        }*/
    }
    //Al presionar la fecla de retroceso o de refresh del navegador se muestra un mensaje
   /* window.onbeforeunload = function() {
        return "¿Estás seguro que deseas salir de la actual página?"
    }*/
    /* window.onbeforeunload = function(e) {
        return 'Texto de aviso';
    };*/

   /* var myEvent = window.attachEvent || window.addEventListener;
    var chkevent = window.attachEvent ? 'onbeforeunload' : 'beforeunload'; /// make IE7, IE8 compitable

    myEvent(chkevent, function(e) { // For >=IE7, Chrome, Firefox
        var confirmationMessage = 'Are you sure to leave the page?';  // a space
        (e || window.event).returnValue = confirmationMessage;
        return confirmationMessage;
    });*/

</script>


<script type="text/javascript">
themeComboBox();
    var lastsel3;
    optionDetEntradaProd = {
        datatype: "local",
        width: 950,
        height: 250,
        rowNum:80,
        colNames: [
            'Id Detalle Entrada',
            'Id Entrada Prod',
            'IdProducto',
            'Producto',
            "Modelo",
            'Cantidad',
            'PU',
            'P. Total',
            'estado',
            "",
            "Serie",
            ""
        ],
        colModel: [
            {name: 'idDetEntradaProd', index:'idDetEntradaProd', width:80,hidden: false},
            {name: 'idEntradaProd', index:'idEntradaProd', width:80,hidden: false},
            {name: 'idProducto', index:'idProducto', width:80},
            {name: 'producto', index:'producto', width:250},
            {name: 'vModelo', index:'vModelo', width:90},
            {name: 'nCantidad', index:'nCantidad', width:80,editable: true,editoptions: { dataInit: function (elem) {
                setTimeout(function(){
                    $(elem).numeric();
                }, 100);
            }
            } },
            {name: 'nPrecioUnit', index:'nPrecioUnit', width:80,editable: true , edittype:"text", editoptions: {   dataInit: function (elem) {
                setTimeout(function(){
                    $(elem).numeric();
                }, 100);
            }
            } },
            {name: 'nPrecioTotal', index:'nPrecioTotal', width:80,editable: false,editoptions: { dataInit: function (elem) {
                setTimeout(function(){
                    $(elem).numeric();
                }, 100);
            }}
            },
            {name: 'vEstado', index:'vEstado', width:100, hidden: true,editable: false},
            { name: 'btndocumall', index: 'btndocumall', width: 40, align: 'center' ,formatter : btncalcular,search:false},
            { name: 'btnserie', index: 'btnserie', width: 50, align: 'center' ,formatter : btnAgregarserie,search:false,hidden:false},
            { name: 'btndocumall1', index: 'btndocumall1', width: 40, align: 'center' ,formatter : btndelete,search:false}
        ],
        editurl: "clientArray",
        caption: "&nbsp;&nbsp;&nbsp;Detalle de entrada Productos",
        ondblClickRow: function(id){
            var row = $(this).getRowData(id);
            EditProducto();
        },
        afterInsertRow:function(rowid,aData){
            switch( aData.vEstado){
                case'':
            break;
            case '0':
            jQuery("#tblDetEntradaProd").jqGrid('setCell',rowid,'idDetEntradaProd','',{background:'pink'});
            jQuery("#tblDetEntradaProd").jqGrid('setCell',rowid,'idEntradaProd','',{background:'pink'});
            jQuery("#tblDetEntradaProd").jqGrid('setCell',rowid,'idProducto','',{background:'pink'});
            jQuery("#tblDetEntradaProd").jqGrid('setCell',rowid,'producto','',{background:'pink'});
            jQuery("#tblDetEntradaProd").jqGrid('setCell',rowid,'nCantidad','',{background:'pink'});
            jQuery("#tblDetEntradaProd").jqGrid('setCell',rowid,'nPrecioUnit','',{background:'pink'});
            jQuery("#tblDetEntradaProd").jqGrid('setCell',rowid,'nPrecioTotal','',{background:'pink'});
            jQuery("#tblDetEntradaProd").jqGrid('setCell',rowid,'btndocumall','',{background:'pink'});
            jQuery("#tblDetEntradaProd").jqGrid('setCell',rowid,'btndocumall1','',{background:'pink'});
            break;
            }
        },
        onSelectRow: function(id) {
            if(lastsel3!=undefined)
                    calcular();
            var row = $(this).getRowData(id);

            if(id && id!==lastsel3){
                jQuery('#tblDetEntradaProd').jqGrid('saveRow',lastsel3);
                lastsel3=id;
            }
            if(row.vEstado!='0'){
            jQuery('#tblDetEntradaProd').jqGrid('editRow',id,true);
            }
        },
        gridComplete: function(id){
            calcular();

            isGridComplete = true;
            $("#tblDetEntradaProd").jqGrid('setSelection', 1, true);

            var ids = jQuery("#tblDetEntradaProd").jqGrid('getDataIDs');

            for (var i = 0; i < ids.length; i++) {
                var cl = ids[i];
                var rowdat = jQuery("#tblDetEntradaProd").jqGrid('getRowData', cl);
                buttvisor = '<div title="Visor de ' + rowdat.docadjunto + '" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\')" onclick="visorarchivo(\''+ rowdat.docadjunto + '\');"><span class="ui-icon ui-icon-search"></span></div>';

                jQuery("#tblDetEntradaProd").jqGrid('setRowData', ids[i], {visor: buttvisor});
                if (''=='1'){
                    butttrash = '<div title="Eliminar ' + rowdat.vadjunto + '" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\')" onclick="eliminarDocAdjunto(\'' + rowdat.idsigma + '\');"><span class="ui-icon ui-icon-trash"></span></div>';

                    jQuery("#tblDetEntradaProd").jqGrid('setRowData', ids[i], {trash: butttrash});
                }
            }
        },
        loadComplete: function(){
            $("tr.jqgrow", this).contextMenu('myMenu1', {
                bindings: {
                    'edit': function(trigger) {
                        EditProducto();
                    },
                    'add': function() {
                        nuevoProducto();
                    },
                    'del': function(trigger) {
                        if ($('#del').hasClass('ui-state-disabled') === false) {
                            var selr = $('#tblDetEntradaProd').jqGrid('getGridParam','selrow');
                            eliminardetentradama(trigger.id);
                        }
                    }
                },
                onContextMenu: function(event, menu) {
                    var rowId = $(event.target).closest("tr.jqgrow").attr("id");
                    $('#del').attr("disabled",Number(rowId)%2 === 0);
                    if (Number(rowId)%2 === 0) {
                        $('#del').attr("disabled","disabled").addClass('ui-state-disabled');
                    } else {
                        $('#del').removeAttr("disabled").removeClass('ui-state-disabled');
                    }
                    return true;
                }
            });
        }
    };




    buscarProveedor = function(){
        parameters = {
            "idsigma":  $("#identradaprod").val(),
            "pag":"2"
        };
        openDialogData1("almacen/buscarpersona", parameters, 660,500);

    };
    eliminar=function(a){
        var selr = $('#tblDetEntradaProd').jqGrid('getGridParam','selrow');
        var row = $("#tblDetEntradaProd").jqGrid('getRowData', selr);
        if(row.cidpers == "" || row.cidpers == undefined){
            openDialogWarning("Seleccione un registro para eliminar.");
            return;
        }
        parameters = {
            "idsigma": row.cidpers
        };

       openDialogConfirm1("\u00BFEst\u00E1 seguro de eliminar datos?",350,{

           "si":function(){
               $.ajax({
                   url: jQuery.scriptPath + "index.php/mantenimientos/eliminarpersona",
                   type: 'POST',
                   cache: false,
                   data: parameters,
                   beforeSend: function (data) {
                   },
                   success: function (requestData) {
                       $("#result").html(requestData);
                       closeDialog("jqDialogConfirmacion1");
                       closeDialog('jqDialog1');
                   },
                   error: function (requestData, strError, strTipoError) {
                       $("#result").html("Error " + strTipoError + ': ' + strError);
                   },
                   complete: function (requestData, exito) {
                   }

               });
           },

           "no":function(){
               closeDialog("jqDialogConfirmacion1");
           }
       })


    };

function linkadjunto(cellvalue, options, rowObject) {
    return '<a href="#" onclick="linkadjuntoOpen(\'' + options.rowId + '\',\'' + cellvalue + '\')" > ' + cellvalue + '</a>'
}
function linkadjuntoOpen(rowId, cellvalue) {
    var row = jQuery("#tblResultDocAdjunto").jqGrid('getRowData', rowId);
    window.open(path + "mantenimientos/forzardescarga?file=" +  cellvalue);
}



// -----> Calcular============================================00
function btncalcular(cellvalue, options, rowObject){

    return '<div align="center" class="ui-pg-button " ' +
        'title="Calcular" style="text-align:center;float: left; cursor: pointer; display: block;" ' +
        'onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
        'onclick="Calculaentradaprod(\''+options.rowId+'\');"><div class="ui-pg-div  ui-inline-edit" >' +
        '<span class="ui-icon ui-icon-calculator"></span></div></div>';
}


function Calculaentradaprod(rowId) {
    var row = jQuery("#tblDetEntradaProd").jqGrid('getRowData', rowId);
    calcular();

    actualizarcantdetalleCot();
}

    function calcular() {
        var rows= jQuery("#tblDetEntradaProd").jqGrid('getRowData');
        if (rows.length >0) {
        }else{
            return;
        }
        if(lastsel3==undefined){
            lastsel3=1;}
       jQuery('#tblDetEntradaProd').jqGrid('saveRow',lastsel3);
        gsrr = jQuery("#tblDetEntradaProd").jqGrid('getRowData');
       var subtot=(gsrr[lastsel3-1].nPrecioUnit)*(gsrr[lastsel3-1].nCantidad);

        var total1=subtot;
        $("#tblDetEntradaProd").setRowData(lastsel3,{nPrecioTotal:total1} );

        var rows= jQuery("#tblDetEntradaProd").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i=0;i<rows.length;i++) {
                var row=rows[i];
                var subt=parseFloat(row.nPrecioTotal);
                subtotal= subtotal +subt;
            }

            var txtotal= subtotal;
            var txsubtotal= (txtotal/1.18);
            var txigv=txtotal-txsubtotal;

            $("#txtsubtotal").val(parseFloat(Math.round(txsubtotal * 100) / 100).toFixed(2));
            $("#txtigv").val(parseFloat(Math.round(txigv * 100) / 100).toFixed(2));
            $("#txttotal").val(parseFloat(Math.round(txtotal * 100) / 100).toFixed(2));
        }
        return true;
    };

GuardardetalleEProd = function(){
        jQuery('#tblDetEntradaProd').jqGrid('saveRow',lastsel3);
        var rows= jQuery("#tblDetEntradaProd").jqGrid('getRowData');
        if (rows.length > 0) {
            for (var i=0;i<rows.length;i++) {
                var row=rows[i];
                parameters = {
                    "idDetEntradaProd": row.idDetEntradaProd,
                    "nPrecioUnit": row.nPrecioUnit,
                    "nCantidad": row.nCantidad,
                    "nPrecTotal": row.nPrecioTotal
                };
                $.ajax({
                    url: jQuery.scriptPath + "index.php/almacen/detentradaprodupdate",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function (data) {   },
                    success: function (requestData) {
                    },
                    error: function (requestData, strError, strTipoError) {   },
                    complete: function (requestData, exito) {    }
                });
            }
        }


        var tieneDes=0;
        parameters1 = {
            "idsigma":  $("#identradaprod").val(),
            "subtotal":  $("#txtsubtotal").val(),
            "igv":  $("#txtigv").val(),
            "total":  $("#txttotal").val(),
            "fecha": $("#fecdesde").val(),
            "factura": $("#txtfactura").val(),
            "tipoMoneda": $("#cbtipomon").val()

        };
        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/entradaprodupdate",
            type: 'POST',
            cache: false,
            data: parameters1,
            beforeSend: function (data) {   },
            success: function (requestData) {
                window.open(path + "almacen/entradaprod", "_self");
            },
            error: function (requestData, strError, strTipoError) {   },
            complete: function (requestData, exito) {    }
        });

    };

    nuevoProducto = function(){

        parameters = {
            "idsigma": $("#identradaprod").val()
        };
        openDialogData1("almacen/addproducto", parameters, 650,560);

    };
    EditProducto= function(){
        var selr = $('#tblDetEntradaProd').jqGrid('getGridParam','selrow');
        var row = $("#tblDetEntradaProd").jqGrid('getRowData', selr);
        if(row.idDetEntradaProd == "" || row.idDetEntradaProd == undefined){
            openDialogWarning("Seleccione un registro para editar.");
            return;
        }
        parameters = {
            "idsigma": $("#identradaprod").val(),
            "iddetentrada": row.idDetEntradaProd,
            "idProducto":row.idProducto
        };
        openDialogData1("almacen/addproducto", parameters, 650,560);

    };

    function buttonsGridDetcoti(){
        $("#tblDetEntradaProd")
            .navGrid('#ptblDetEntradaProd', {edit:false,add:false,del:false,search:false,refresh:false})

            .navButtonAdd('#ptblDetEntradaProd',{
                caption:"Agregar&nbsp;&nbsp;",
                buttonicon:"ui-icon-plus",
                onClickButton: function(){
                    nuevoProducto();
                },
                position:"last"
            })
            .navSeparatorAdd()

            .navButtonAdd('#ptblDetEntradaProd',{
                caption:"Editar&nbsp;&nbsp;",
                buttonicon:"ui-icon-pencil",
                onClickButton: function(){
                    EditProducto();
                },
                position:"last"
            })
            .navSeparatorAdd();
    }


    function imprimir(){
        var selr = $('#tblDetEntradaProd').jqGrid('getGridParam','selrow');
        var row = $("#tblDetEntradaProd").jqGrid('getRowData', selr);

        host = '<?php echo $this->util()->getPath(); ?>report/';
         window.open(host+"rptCotizacion.php?idCotiz="+ $("#identradaprod").val() ,'_blank');
    }

// -----> Borrar============================================00
function btndelete(cellvalue, options, rowObject){

    return '<div align="center" class="ui-pg-button " ' +
        'title="Borrar" style="text-align:center;float: left; cursor: pointer; display: block;" ' +
        'onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
        'onclick="eliminardetentradama(\''+options.rowId+'\');"><div class="ui-pg-div  ui-inline-edit" >' +
        '<span class="ui-icon ui-icon-trash"></span></div></div>';
}
function eliminardetentradama(rowId) {

    var row = jQuery("#tblDetEntradaProd").jqGrid('getRowData', rowId);
    openDialogConfirm1("Eliminar Registro?", 350, {
        "Si": function () {
            var parmter = {};
            parmter.idDetEntradaProd = row.idDetEntradaProd;
            closeDialog("jqDialogConfirmacion1");
            $.post(path + "almacen/detentradaproddel", parmter, updCheckdelete, 'json');
        },
        "No": function () {
            closeDialog("jqDialogConfirmacion1");

        }
    });
}
function updCheckdelete(data) {
    if (data[0][1]=="ERR"){
        openDialogWarning(data[0][0]);
    }else{
        lastsel3=undefined;
        buscarDetEntradaProd();
    }
}



// -----> Calcular============================================00
function btnAgregarserie(cellvalue, options, rowObject){

    return '<div align="center" class="ui-pg-button " ' +
        'title="Calcular" style="text-align:center;float: left; cursor: pointer; display: block;" ' +
        'onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
        'onclick="AgregarSeries(\''+options.rowId+'\');"><div class="ui-pg-div  ui-inline-edit" >' +
        '<span class="ui-icon ui-icon-search"></span></div></div>';
}


function AgregarSeries(rowId) {
    console.log(lastsel3);
jQuery('#tblDetEntradaProd').jqGrid('saveRow',lastsel3);
var row = jQuery("#tblDetEntradaProd").jqGrid('getRowData', rowId);
calcular();
    parameters = {
        "idsigma":row.idDetEntradaProd,
        "idProducto":row.idProducto,
        "nombreProd":row.producto,
        "nCantidad": row.nCantidad
    };
    openDialogData1("almacen/ingresarseries", parameters, 560,560);
}


    buscarDetEntradaProd = function() {
        var params = '['
            + '["@tBusqueda", "0"],'
			+ '["@vIdEntradaProd", "' + $("#identradaprod").val() + '"],'
			+ '["@vDatoBus", ""]'
            + ']';
        parameters = {
            "name": "tblDetEntradaProd",
            "procedure": "almacen.Bus_DetEntradaProd",
            "print": "true",
            "parameters": params
        };

        procesarProcedimientoJSON(
            "panelDetEntradaProd"
            , "tblDetEntradaProd"
            , optionDetEntradaProd
            , parameters
            , null
            , buttonsGridDetcoti
        );
    };



//Funcion para regresar al la grilla naterior
    function Cancelar(){
        parameters = {
            "identradaprod":$("#identradaprod").val()
        }
        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/cancelareliminadosentradaprod",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function (data) { },
            success: function (requestData) {
                window.open(path + "almacen/entradaprod", "_self");
            },
            error: function (requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function (requestData, exito) {    }
        });


    }


actualizarcantdetalleCot = function(){
    jQuery('#tblDetEntradaProd').jqGrid('saveRow',lastsel3);
    var rows= jQuery("#tblDetEntradaProd").jqGrid('getRowData');
    console.log(rows.length);
    if (rows.length > 0) {
        for (var i=0;i<rows.length;i++) {
            var row=rows[i];
            parameters = {
                "idDetEntradaProd": row.idDetEntradaProd,
                "nPrecioUnit": row.nPrecioUnit,
                "nCantidad": row.nCantidad,
                "nPrecTotal": row.nPrecioTotal
            };
            $.ajax({
                url: jQuery.scriptPath + "index.php/almacen/detentradaprodupdate",
                type: 'POST',
                cache: false,
                data: parameters,
                beforeSend: function (data) {   },
                success: function (requestData) {
                },
                error: function (requestData, strError, strTipoError) {   },
                complete: function (requestData, exito) {    }
            });
        }
    }

}


    $(function(){
        $("#fecdesde").datepicker({showOn: "button", buttonImage: pathImage + "calendar.gif", buttonImageOnly: true, dateFormat: "dd/mm/yy"});
        $("#fechasta").datepicker({showOn: "button", buttonImage: pathImage + "calendar.gif", buttonImageOnly: true, dateFormat: "dd/mm/yy"});

        buscarDetEntradaProd();


        $("#btnbuscar").button(ICON_SEARCH);
        $("#btnguardar").button(ICON_SAVE);
        $("#btncancelardet").button(ICON_CANCEL).click(function () {
            Cancelar('');
        });
    });
function reiniCombo(celement){
    var xelem = $("#" + celement);
    xelem.combobox("destroy");
    $("option:selected",xelem).removeAttr("selected");
    $("option[value='9999999999']",xelem).attr("selected", "selected");
}

</script>