<?php
$library = new Libreria_Pintar();
$TipoMoneda = array(array("2", "Soles"), array("1", "Dolares"));

?>


<div id="panelMantenimientoCotizacion" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 99%;margin: 1px; height:95%;">
    <div class="ui-widget ui-state-verde ui-corner-top ui-title">
        <label>Mantenimiento - Entrada Activos</label>
    </div>
    <input type="hidden" id="idEntradaActivos" name="idEntradaActivos" value="<?php echo $this->idEntradaMat; ?>">
    <div id="dialogBuscarContribuyentePredio">
        <table class="ui-panelLayout-main">
            <tr>
                <td style="vertical-align: top;">
                    <table border="0" style="margin-left:45px;">
                        <tr>
                            <td>
                                <b> Datos Proveedor </b>
                            </td>
                        </tr>
                        <tr class="rowBuscarProveedor">

                            <td width="100" style="text-align: left">C&oacute;digo:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" style="text-align: left">Rason Social:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230">&nbsp;</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" colspan="5" style="text-align: left"></td>
                            <td width="150">&nbsp;</td>
                        </tr>
                        <tr class="rowBuscarProveedor" id="panelBuscarContribuyente">

                            <td>
                                <input class="ui-text-disable" readonly id="txtidProveedor" value="<?php echo $this->idProveedor; ?>" maxlength="10" style="width:90px" />
                            </td>
                            <td>&nbsp;</td>
                            <td colspan="3">
                                <input class="ui-text-disable pnl" readonly id="nombrecontrib" value="<?php echo $this->nombreproveed; ?>" style="width:100%" />
                            </td>
                            <td>&nbsp;</td>
                            <td colspan="5" style="text-align: left;">
                                <!-- <input class="ui-text-disable pnl" readonly id="nrodoc"   value="<?php echo $this->vnrodoprov; ?>"  style="width:50%" /> -->
                            </td>
                            <td rowspan="1">
                                <button id="btnbuscar" name="btnbuscar" onclick="buscarProveedor()">Buscar Proveedor</button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <b> Datos Compra</b>
                            </td>
                        </tr>
                        <tr class="rowcoti">

                            <td width="100" style="text-align: left">Fecha:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" style="text-align: left">Factura</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" style="text-align: left">Tipo Moneda</td>
                        </tr>

                        <tr class="rowbcoti" id="panelbcoti">

                            <td>
                                <input type="text" id="fecdesde" value="<?php echo $this->dfecentrada; ?>" class="ui-text-disable " readonly style="text-align: left;width: 80px;" />
                            </td>
                            <td>&nbsp;</td>
                            <td class="soloSolesa">&nbsp;<input type="text" class="ui-text pnl" id="txtfactura" value="<?php echo $this->nrofactura; ?>" style="width:96%" /></td>

                            <td>&nbsp;
                            </td>

                            <td colspan="2">
                                <select id="cbtipomon" name="cbtipomon" style="width:140px;">
                                    <?php echo $library->ContenidoCombo($TipoMoneda, $this->ctipmon, 0); ?>
                                </select>

                            </td>


                        </tr>

                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <div id="dialogMensaje">
    </div>
    <div id="panelDetEntradaMat" align="left" style="width: 99%;margin-left: 15px; margin-right: 15px;">
        <table id="tblDetEntradaMat"></table>
        <div id="ptblDetEntradaMat">
        </div>
    </div>
    <br />


    <div align="right">
        <table border="0" style=" margin-left: 45px; margin-right: 45px">
            <tr style="width:20%;">
                <td align="right"><b>Sub Total:</b></td>
                <td><b>
                        <input type="text" class="ui-text-disable" readonly id="txtsubtotal" value="<?php echo $this->subtotal; ?>" maxlength="20" style="width:90px; text-align: right" />
                    </b></td>
            </tr>
            <tr align="right">
                <td><b>IGV:</b></td>
                <td><b> <input type="text" class="ui-text-disable" readonly id="txtigv" value="<?php echo $this->igv; ?>" maxlength="20" style="width:90px; text-align: right" /></b></td>
            </tr>
            <tr align="right">
                <td><b>Total:</b></td>
                <td><b> <input type="text" class="ui-text-disable" readonly id="txttotal" value="<?php echo $this->total; ?>" maxlength="20" style="width:90px; text-align: right" /></b></td>
            </tr>

            <tr>
                <td><button id="btncancelardet" name="btncancelardet">Cancelar</button></td>
                <td>
                    <button id="btnguardar" name="btnguardar" onclick="GuardarDetalleActivos()">Guardar</button>
                </td>
            </tr>


        </table>
    </div>
    <table id="list4"></table>
    <br />
</div>
<div class="contextMenu" id="myMenu1" style="display:none">
    <ul style="width: 200px">
        <li id="add">
            <span class="ui-icon ui-icon-plus" style="float:left"></span>
            <span style="font-size:11px; font-family:Verdana">Agregar</span>
        </li>
        <li id="edit">
            <span class="ui-icon ui-icon-pencil" style="float:left"></span>
            <span style="font-size:11px; font-family:Verdana">Editar</span>
        </li>
        <li id="del">
            <span class="ui-icon ui-icon-trash" style="float:left"></span>
            <span style="font-size:11px; font-family:Verdana">Eliminar</span>
        </li>
    </ul>
</div>
<script language="javascript">
    document.onkeydown = function() {
        // a presonar el f5 se actuliza la misma pagina..
        if (window.event && window.event.keyCode == 116) {
            window.status = "Por favor, Haga Click en Cerrar Sesión Para Salir del Sistema de Auditoría de Servicios";
            if (confirm('¿Estás seguro que deseas salir de la actual página?')) {
                //alert("Pulsada la tecla F5");
            } else {
                return false;
            }

        }
    }
</script>


<script type="text/javascript">
    themeComboBox();

    function validarTipoCambio(tipo) {
        switch (tipo) {
            case '1': // Dolares
                $(".soloSoles").hide();
                // ActualizarMontos(); //No se cacula la cantidad
                //$("#tasacambio").val("0");
                break;
            case '2': // Soles
                $(".soloSoles").show();
                break;
            default:
                break;
        }
    }
    validarTipoCambio($("#cbtipomon").val());

    $("#cbtipomon").combobox({
        selected: function(event, ui) {

        }
    });



    var lastsel3;
    optionDetEntradaMat = {
        datatype: "local",
        width: 950,
        height: 250,
        keys: true,
        rowNum: 80,
        colNames: [
            'Id Detalle',
            'Id Entrada',
            'idActivos',
            'Activo',
            'Cantidad',
            'PU',
            'P. Total',
            'estado',
            "",
            ""
        ],
        colModel: [{
                name: 'idDetEntradaActivos',
                index: 'idDetEntradaActivos',
                width: 80,
                hidden: false
            },
            {
                name: 'idEntradaActivos',
                index: 'idEntradaActivos',
                width: 80,
                hidden: false
            },
            {
                name: 'idActivos',
                index: 'idActivos',
                width: 80
            },
            {
                name: 'activos',
                index: 'activos',
                width: 260
            },
            {
                name: 'nCantidad',
                index: 'nCantidad',
                width: 80,
                editable: false,
                editoptions: {
                    dataInit: function(elem) {
                        setTimeout(function() {
                            $(elem).numeric();
                        }, 100);
                    }
                }
            },
            {
                name: 'nPrecioUnit',
                index: 'nPrecioUnit',
                width: 80,
                editable: false,
                edittype: "text",
                editoptions: {
                    dataInit: function(elem) {
                        setTimeout(function() {
                            $(elem).numeric();
                        }, 100);
                    }
                }
            },
            {
                name: 'nPrecioTotal',
                index: 'nPrecioTotal',
                width: 80,
                editable: false,
                editoptions: {
                    dataInit: function(elem) {
                        setTimeout(function() {
                            $(elem).numeric();
                        }, 100);
                    }
                }
            },
            {
                name: 'vEstado',
                index: 'vEstado',
                width: 100,
                hidden: true,
                editable: false
            },
            {
                name: 'btndocumall',
                index: 'btndocumall',
                width: 60,
                align: 'center',
                formatter: btncalcular,
                search: false,
                hidden: true
            },
            {
                name: 'btndocumall',
                index: 'btndocumall',
                width: 40,
                align: 'center',
                formatter: btndelete,
                search: false
            }

        ],
        editurl: "clientArray",
        caption: "&nbsp;&nbsp;&nbsp;Detalle de entrada Activos",
        ondblClickRow: function(id) {
            var row = $(this).getRowData(id);
            EditPSM();

        },
        afterInsertRow: function(rowid, aData) {
            switch (aData.opcional) {
                case '':
                    break;
                case '1':
                    jQuery("#tblDetEntradaMat").jqGrid('setCell', rowid, 'idDetEntradaActivos', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetEntradaMat").jqGrid('setCell', rowid, 'idEntradaActivos', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetEntradaMat").jqGrid('setCell', rowid, 'idActivos', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetEntradaMat").jqGrid('setCell', rowid, 'activos', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetEntradaMat").jqGrid('setCell', rowid, 'nCantidad', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetEntradaMat").jqGrid('setCell', rowid, 'nPrecioUnit', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetEntradaMat").jqGrid('setCell', rowid, 'nPrecioTotal', '', {
                        background: '#ddeaa6'
                    });
                    break;
            }
        },
        onSelectRow: function(id) {
            if (lastsel3 != undefined)
                if (id && id !== lastsel3) {
                    jQuery('#tblDetEntradaMat').jqGrid('saveRow', lastsel3);
                    lastsel3 = id;
                }
            jQuery('#tblDetEntradaMat').jqGrid('editRow', id, true);

        },
        gridComplete: function(id) {
            calcular();

            isGridComplete = true;
            $("#tblDetEntradaMat").jqGrid('setSelection', 1, true);

            var ids = jQuery("#tblDetEntradaMat").jqGrid('getDataIDs');

            for (var i = 0; i < ids.length; i++) {
                var cl = ids[i];
                var rowdat = jQuery("#tblDetEntradaMat").jqGrid('getRowData', cl);
                buttvisor = '<div title="Visor de ' + rowdat.docadjunto + '" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\')" onclick="visorarchivo(\'' + rowdat.docadjunto + '\');"><span class="ui-icon ui-icon-search"></span></div>';

                jQuery("#tblDetEntradaMat").jqGrid('setRowData', ids[i], {
                    visor: buttvisor
                });
                if ('' == '1') {
                    butttrash = '<div title="Eliminar ' + rowdat.vadjunto + '" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\')" onclick="eliminarDocAdjunto(\'' + rowdat.idsigma + '\');"><span class="ui-icon ui-icon-trash"></span></div>';

                    jQuery("#tblDetEntradaMat").jqGrid('setRowData', ids[i], {
                        trash: butttrash
                    });
                }
            }
        },
        aftersavefunc: function(rowid) { // can add jqXHR, sentData, options
            alert(rowid + " is saved");
        },
        loadComplete: function() {
            $("tr.jqgrow", this).contextMenu('myMenu1', {
                bindings: {
                    'edit': function(trigger) {
                        // trigger is the DOM element ("tr.jqgrow") which are triggered
                        EditPSM();
                        //jQuery('#tblDetEntradaMat').editGridRow(trigger.id, "");
                    },
                    'add': function( /*trigger*/ ) {
                        nuevaPSM();
                        //jQuery('#tblDetEntradaMat').editGridRow("new", "");
                    },
                    'del': function(trigger) {
                        if ($('#del').hasClass('ui-state-disabled') === false) {
                            // disabled item can do be choosed
                            // jQuery('#tblDetEntradaMat').delGridRow(trigger.id, "");
                            var selr = $('#tblDetEntradaMat').jqGrid('getGridParam', 'selrow');
                            //var row = $("#tblDetEntradaMat").jqGrid('getRowData', selr);
                            eliminardetentradama(trigger.id);
                        }
                    }
                },
                onContextMenu: function(event /*, menu*/ ) {
                    var rowId = $(event.target).closest("tr.jqgrow").attr("id");
                    //grid.setSelection(rowId);
                    // disable menu for rows with even rowids
                    $('#del').attr("disabled", Number(rowId) % 2 === 0);
                    if (Number(rowId) % 2 === 0) {
                        $('#del').attr("disabled", "disabled").addClass('ui-state-disabled');
                    } else {
                        $('#del').removeAttr("disabled").removeClass('ui-state-disabled');
                    }
                    return true;
                }
            });
        }
    };




    buscarProveedor = function() {
        parameters = {
            "idsigma": $("#idEntradaActivos").val(),
            "pag": "3"
        };
        openDialogData1("almacen/buscarpersona", parameters, 660, 500);
        //   window.open(path + "mantenimientos/backup", "_self");

    };
    eliminar = function(a) {
        var selr = $('#tblDetEntradaMat').jqGrid('getGridParam', 'selrow');
        var row = $("#tblDetEntradaMat").jqGrid('getRowData', selr);
        if (row.cidpers == "" || row.cidpers == undefined) {
            openDialogWarning("Seleccione un registro para eliminar.");
            return;
        }
        parameters = {
            "idsigma": row.cidpers
        };

        //openDialogData2("mantenimientos/eliminarpersona", parameters, 460);
        openDialogConfirm1("\u00BFEst\u00E1 seguro de eliminar datos?", 350, {

            "si": function() {
                //openDialogData2("mantenimientos/eliminarpersona", parameters, 460);
                $.ajax({
                    url: jQuery.scriptPath + "index.php/mantenimientos/eliminarpersona",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function(data) {},
                    success: function(requestData) {
                        $("#result").html(requestData);
                        closeDialog("jqDialogConfirmacion1");
                        closeDialog('jqDialog1');
                    },
                    error: function(requestData, strError, strTipoError) {
                        $("#result").html("Error " + strTipoError + ': ' + strError);
                    },
                    complete: function(requestData, exito) {}

                });
            },

            "no": function() {
                closeDialog("jqDialogConfirmacion1");
            }
        })


    };

    function linkadjunto(cellvalue, options, rowObject) {
        return '<a href="#" onclick="linkadjuntoOpen(\'' + options.rowId + '\',\'' + cellvalue + '\')" > ' + cellvalue + '</a>'
    }

    function linkadjuntoOpen(rowId, cellvalue) {
        var row = jQuery("#tblResultDocAdjunto").jqGrid('getRowData', rowId);
        //console.log(row);
        window.open(path + "mantenimientos/forzardescarga?file=" + cellvalue);
    }


    function ActualizarMontos() {
        //No se usa en el ingreso de Activos no se calcula
        jQuery('#tblDetEntradaMat').jqGrid('saveRow', lastsel3);
        var tasa = $("#tasacambio").val();
        var tipomon = $("#cbtipomon").val();

        if (tasa == 0 || tasa == undefined || tasa == "") {
            openDialogWarning("Ingrese la tasa de cambio.");
            return;
        }
        var rows = jQuery("#tblDetEntradaMat").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                var subt = parseFloat(row.nPrecioUnit);
                if (tipomon == '1') { //Si es dolares divide el subtotal entre la tasa de cambio
                    subtotal = subt / tasa;
                } else { //Si es soles multiplica el subtotal por la tasa de cambio
                    subtotal = subt * tasa;
                }
                var total = subtotal * (row.nCantidad);

                var total1 = total;
                console.log(total1);
                $("#tblDetEntradaMat").setRowData(i + 1, {
                    nPrecioUnit: parseFloat(Math.round(subtotal * 100) / 100).toFixed(2)
                });
                $("#tblDetEntradaMat").setRowData(i + 1, {
                    nPrecioTotal: parseFloat(Math.round(total1 * 100) / 100).toFixed(2)
                });
            }
        }

        var rows = jQuery("#tblDetEntradaMat").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                var subt = parseFloat(row.nPrecioTotal);
                subtotal = subtotal + subt;
            }

            var txtotal = subtotal;
            var txsubtotal = (txtotal / 1.18);
            var txigv = txtotal - txsubtotal;
            $("#txtsubtotal").val(parseFloat(Math.round(txsubtotal * 100) / 100).toFixed(2));
            $("#txtigv").val(parseFloat(Math.round(txigv * 100) / 100).toFixed(2));
            $("#txttotal").val(parseFloat(Math.round(txtotal * 100) / 100).toFixed(2));

        }
        return true;
    };

    function calcular() {
        var rows = jQuery("#tblDetEntradaMat").jqGrid('getRowData');
        if (rows.length > 0) {} else {
            return;
        }

        console.log(lastsel3);
        if (lastsel3 == undefined) {
            lastsel3 = 1;
        }
        console.log(lastsel3);
        jQuery('#tblDetEntradaMat').jqGrid('saveRow', lastsel3);
        gsrr = jQuery("#tblDetEntradaMat").jqGrid('getRowData');
        //var nrowid = $('#tblDetEntradaMat').jqGrid('getGridParam','selrow');
        var subtot = (gsrr[lastsel3 - 1].nPrecioUnit) * (gsrr[lastsel3 - 1].nCantidad);

        var total1 = subtot;
        $("#tblDetEntradaMat").setRowData(lastsel3, {
            nPrecioTotal: total1
        });

        var rows = jQuery("#tblDetEntradaMat").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                var subt = parseFloat(row.nPrecioTotal);
                subtotal = subtotal + subt;
            }

            var txtotal = subtotal;
            var txsubtotal = (txtotal / 1.18);
            var txigv = txtotal - txsubtotal;

            $("#txtsubtotal").val(parseFloat(Math.round(txsubtotal * 100) / 100).toFixed(2));
            $("#txtigv").val(parseFloat(Math.round(txigv * 100) / 100).toFixed(2));
            $("#txttotal").val(parseFloat(Math.round(txtotal * 100) / 100).toFixed(2));
        }
        return true;
    };

    GuardarDetalleActivos = function() {
        var tieneDes = 0;
        parameters1 = {
            "idsigma": $("#idEntradaActivos").val(),
            "idProveedor": $("#txtidProveedor").val(),
            "subtotal": $("#txtsubtotal").val(),
            "igv": $("#txtigv").val(),
            "total": $("#txttotal").val(),
            "fecha": $("#fecdesde").val(),
            "factura": $("#txtfactura").val(),
            "tipoMoneda": $("#cbtipomon").val()
        };
        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/entradaactivosupdate",
            type: 'POST',
            cache: false,
            data: parameters1,
            beforeSend: function(data) {},
            success: function(requestData) {
                //imprimir();
                window.open(path + "almacen/entradaactivos", "_self");
            },
            error: function(requestData, strError, strTipoError) {},
            complete: function(requestData, exito) {}
        });

    };



    nuevaPSM = function() {
        parameters = {
            "idsigma": $("#idEntradaActivos").val()
        };
        openDialogData1("almacen/addactivos", parameters, 560, 560);

    };
    EditPSM = function() {
        var selr = $('#tblDetEntradaMat').jqGrid('getGridParam', 'selrow');
        var row = $("#tblDetEntradaMat").jqGrid('getRowData', selr);
        if (row.idDetEntradaActivos == "" || row.idDetEntradaActivos == undefined) {
            openDialogWarning("Seleccione un registro para editar.");
            return;
        }
        parameters = {
            "idsigma": $("#idEntradaActivos").val(),
            "iddetentrada": row.idDetEntradaActivos,
            "idActivos": row.idActivos,
            "nCantidad": row.nCantidad,
            "nPrecioUnit": row.nPrecioUnit
        };
        openDialogData1("almacen/addactivos", parameters, 560, 560);

    };




    function buttonsGridDetcoti() {
        $("#tblDetEntradaMat")
            .navGrid('#ptblDetEntradaMat', {
                edit: false,
                add: false,
                del: false,
                search: false,
                refresh: false
            })

            .navButtonAdd('#ptblDetEntradaMat', {
                caption: "Agregar&nbsp;&nbsp;",
                buttonicon: "ui-icon-plus",
                onClickButton: function() {
                    nuevaPSM();
                },
                position: "last"
            })
            .navSeparatorAdd()

            .navButtonAdd('#ptblDetEntradaMat', {
                caption: "Editar&nbsp;&nbsp;",
                buttonicon: "ui-icon-pencil",
                onClickButton: function() {
                    EditPSM();
                },
                position: "last"
            })
            .navSeparatorAdd()




        ;
    }


    function imprimir() {
        var selr = $('#tblDetEntradaMat').jqGrid('getGridParam', 'selrow');
        var row = $("#tblDetEntradaMat").jqGrid('getRowData', selr);

        host = '<?php echo $this->util()->getPath(); ?>report/';
        window.open(host + "rptCotizacion.php?idCotiz=" + $("#idEntradaActivos").val(), '_blank');
        //console.log(host);

    }

    // -----> Borrar============================================00
    function btndelete(cellvalue, options, rowObject) {

        return '<div align="center" class="ui-pg-button " ' +
            'title="Borrar" style="text-align:center;float: left; cursor: pointer; display: block;" ' +
            'onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
            'onclick="eliminardetentradama(\'' + options.rowId + '\');"><div class="ui-pg-div  ui-inline-edit" >' +
            '<span class="ui-icon ui-icon-trash"></span></div></div>';
    }

    function eliminardetentradama(rowId) {

        var row = jQuery("#tblDetEntradaMat").jqGrid('getRowData', rowId);
        openDialogConfirm1("Eliminar Registro?", 350, {
            "Si": function() {
                var parmter = {};
                parmter.idDetEntradaActivos = row.idDetEntradaActivos;
                closeDialog("jqDialogConfirmacion1");
                $.post(path + "almacen/detentradamatdel", parmter, updCheckdelete, 'json');
            },
            "No": function() {
                //ProcesoBuscarRuta(''); chkrecep_5
                closeDialog("jqDialogConfirmacion1");

            }
        });
    }

    function updCheckdelete(data) {
        lastsel3 = undefined
        buscarDetEntradaMat();

    }



    // -----> Calcular============================================00
    function btncalcular(cellvalue, options, rowObject) {

        return '<div align="center" class="ui-pg-button " ' +
            'title="Calcular" style="text-align:center;float: left; cursor: pointer; display: block;" ' +
            'onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
            'onclick="Calculadetentrada(\'' + options.rowId + '\');"><div class="ui-pg-div  ui-inline-edit" >' +
            '<span class="ui-icon ui-icon-calculator"></span></div></div>';
    }


    function Calculadetentrada(rowId) {
        var row = jQuery("#tblDetEntradaMat").jqGrid('getRowData', rowId);
        calcular();
        actualizarcantdetalleCot();
    }


    buscarDetEntradaMat = function() {
        var params = '[' +
            '["@tBusqueda", "0"],' +
            '["@vIdEntradaActivos", "' + $("#idEntradaActivos").val() + '"],' +
            '["@vDatoBus", ""]' +
            ']';
        parameters = {
            "name": "tblDetEntradaMat",
            "procedure": "almacen.Bus_DetEntradaActivos",
            "print": "true",
            "parameters": params
        };

        procesarProcedimientoJSON(
            "panelDetEntradaMat", "tblDetEntradaMat", optionDetEntradaMat, parameters, null, buttonsGridDetcoti
        );
    };



    //Funcion para regresar al la grilla naterior
    function Cancelar() {
        parameters = {
            "idEntradaActivos": $("#idEntradaActivos").val()
        };

        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/cancelareliminadosentradaactivos",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function(data) {},
            success: function(requestData) {
                // $("#result").html(requestData);
                //  var datos=JSON.parse(requestData);
                window.open(path + "almacen/entradaactivos", "_self");
            },
            error: function(requestData, strError, strTipoError) {
                console.log("Error " + strTipoError + ': ' + strError);
                $("#result").html("Error " + strTipoError + ': ' + strError);

            },
            complete: function(requestData, exito) {}
        });


    }


    actualizarcantdetalleCot = function() {
        jQuery('#tblDetEntradaMat').jqGrid('saveRow', lastsel3);
        var rows = jQuery("#tblDetEntradaMat").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                parameters = {
                    "idDetCotiz": row.idDetCotiz,
                    "nPrecioUnit": row.nPrecioUnit,
                    "nCantidad": row.nCantidad,
                    "nPrecioTotal": row.nPrecioTotal,
                    "nDescu": row.nDesc
                };
                $.ajax({
                    url: jQuery.scriptPath + "index.php/almacen/detcotizacionupdate",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function(data) {},
                    success: function(requestData) {

                    },
                    error: function(requestData, strError, strTipoError) {},
                    complete: function(requestData, exito) {}
                });
            }
        }

    }


    $(function() {
        $("#fecdesde").datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });
        $("#fechasta").datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });

        buscarDetEntradaMat();


        $("#btnbuscar").button({
            icons: {
                primary: "ui-icon-search"
            }
        });
        $("#btnguardar").button({
            icons: {
                primary: "ui-icon-disk"
            }
        });
        $("#btncancelardet").button({
            icons: {
                primary: "ui-icon-cancel"
            }
        }).click(function() {
            Cancelar('');
        });

    });

    function reiniCombo(celement) {
        var xelem = $("#" + celement);
        xelem.combobox("destroy");
        $("option:selected", xelem).removeAttr("selected");
        $("option[value='9999999999']", xelem).attr("selected", "selected");
        //xelem.combobox();
    }

    function visorarchivo(nom_archivo) {
        var page = '';
        arrarchivo = nom_archivo.split(".");
        extarchivo = arrarchivo[1];

        if (extarchivo == 'png' || extarchivo == 'jpg' || extarchivo == 'gif') {

            if (navigator.appName == 'Microsoft Internet Explorer') {

                var ver = getInternetExplorerVersion();
                if (ver > -1) {
                    // alert(ver);
                    if (ver <= 9.0) {
                        page = jQuery.scriptPath + 'FichaTecnica/' + nom_archivo;
                        var $dialog = $('<div></div>')
                            .html('<div align="center"><iframe style="border: 0px; " src="' + page + '" width="700" height="600"></iframe></div>')
                            .dialog({
                                autoOpen: false,
                                modal: true,
                                height: 700,
                                width: 800,
                                title: "Visor de Archivos"
                            });
                        $dialog.dialog('open');

                    }
                } else {
                    page = path + "mantenimientos/visordocs?img=" + nom_archivo;
                    var $dialog = $('<div></div>')
                        .load(page)
                        .dialog({
                            autoOpen: false,
                            modal: true,
                            height: 650,
                            width: 800,
                            title: "Visor de Archivos"
                        });
                    $dialog.dialog('open');


                }
            } else {

                page = path + "mantenimientos/visordocs?img=" + nom_archivo;
                var $dialog = $('<div></div>')
                    .load(page)
                    .dialog({
                        autoOpen: false,
                        modal: true,
                        height: 650,
                        width: 800,
                        title: "Visor de Archivos"
                    });
                $dialog.dialog('open');

            }




        } else {
            page = jQuery.scriptPath + 'FichaTecnica/' + nom_archivo;
            var $dialog = $('<div></div>')
                .html('<div align="center"><iframe style="border: 0px; " src="' + page + '" width="700" height="600"></iframe></div>')
                .dialog({
                    autoOpen: false,
                    modal: true,
                    height: 700,
                    width: 800,
                    title: "Visor de Archivos"
                });
            $dialog.dialog('open');
        }
    }
</script>