<?php
$library = new Libreria_Pintar();
//array("0","GENERAL"), array("1","ID"), array("2","SERIE"), array("3","PRODUCTO"), array("4","DETENTRADA"),
$TipoBusqueda=array( array("5","ID SALIDA"));
?>
<style>
    #tableRetornoProd { margin :  0 2em 0em 0; border-collapse: collapse; width: 100%; }
    #tableRetornoProd td, #tableRetornoProd th { border: 1px solid #eee; padding: .4em 5px; text-align: left; }
</style>

<div  id="panelMantenimientoCotizacion" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 99%;margin: 1px; height:95%;">
    <div class="ui-widget ui-state-azul ui-corner-top ui-title">
        <label>Mantenimiento - Retorno Producto</label>
    </div>
    <input type="hidden" id="idRetornoProd" name="idRetornoProd" value="<?php echo $this->idRetornoProd;?>">
    <input type="hidden" id="idSalidaProd" name="idSalidaProd" value="<?php echo $this->idSalidaProd;?>">

    <div id="panelPapeleta" align="center" class="ui-widget ui-widget-content ui-corner-all"
         style="width: 99%;margin: 3px;padding-bottom: 5px;">
        <table class="ui-panelLayout-main" >
            <tr>
                <td style="vertical-align: top;">
                    <table border="0" style="margin-left:45px;">

                        <tr>

                            <td  style="text-align: left" colspan="4">Obra:</td>
                            </tr>

                        <tr>

                            <td colspan="4">
                                <input class="ui-text"   id="txtobra" value="<?php echo $this->obra;?>"  maxlength="100" style="width:100%" />
                            </td>
                        </tr>
                <tr>
                    <td><br></td>
                </tr>
                        <tr class="rowcoti">

                            <td width="100" style="text-align: left">Fecha Retorno:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" style="text-align: left">Lugar</td>
                        </tr>

                        <tr class="rowbcoti" id="panelbcoti">

                            <td>
                                <input type="text" id="fecretorno" value="<?php echo $this->dFecRetorno;?>"  class="ui-text-disable " readonly style="text-align: left;width: 80px;"/>
                            </td>
                           <td>&nbsp; </td>
                            <td class="soloSolesa">&nbsp;<input type="text" class="ui-text pnl" id="txtlugar"   value="<?php  echo $this->lugar; ?>"  style="width:96%" /></td>

                        </tr>
                        <tr>
                            <td><br></td>
                        </tr>
                        <tr>
                            <td width="230" style="text-align: left">Tecnico encargado:</td>
                            <td width="10">&nbsp;</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" colspan="5" style="text-align: left"></td>
                            <td width="150">&nbsp;</td>
                        </tr>
                        <tr class="rowBuscarContribuyente" id="panelBuscarContribuyente">

                            <td colspan="3">
                                <input class="ui-text-disable pnl" type="hidden" readonly id="txtidtecnico"  value="<?php echo $this->idtecnico;?>"  style="width:100%" />
                                <input class="ui-text-disable pnl" readonly id="txtnombretecnico"  value="<?php echo $this->nomtecnico;?>"  style="width:100%" />
                            </td>

                            <td colspan="5" style="text-align: left;">
                                <!-- <input class="ui-text-disable pnl" readonly id="nrodoc"   value="<?php echo $this->vnrodoprov;?>"  style="width:50%" /> -->
                            </td>
                            <td rowspan="1">
                                <button id="btnbuscartec" name="btnbuscartec" onclick="buscarTecni()">Buscar Tecnico</button>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
</div>


    <div id="panelDatosConductor" align="center" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;height: 100%;margin: 3px;">
        <div class="ui-widget ui-state-default ui-corner-top ui-title">
            <label>Materiales </label>
        </div>
        <div style="text-align: left" >
            <button id="btnRegistroAgregar" >Agregar</button>
        </div>
        <table id="tableRetornoProd" border="1" class="ui-widget ui-widget-content">
            <thead>
            <tr class="ui-widget-header">
                <th>Codigo</th>
                <th>Producto</th>
                <th>Stock</th>
                <th>Serie</th>
                <th>Observacion</th>
                <th>Buscar</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <tr style="display: none;">
                <td>
                    <input type="hidden" name="txtidDetRetornoProd" id="txtidDetRetornoProd"/>
                    <input id="txtProdSeries"  name="txtProdSeries" class="ui-text-disable" disabled="disabled"  style="width:80px" >
                </td>
                <td>
                    <div  class="ui-text-disable" style="padding: .4em 5px; text-align: left; width:450px" id="txtProducto" name="txtProducto">&nbsp;</div>
                </td>
                <td>
                    <input id="txtStock"  name="txtStock" class="ui-text-disable" disabled="disabled"  style="width:70px" >
                </td>
                <td>
                    <input id="txtSerie"  name="txtSerie" class="ui-text-disable" disabled="disabled"  style="width:150px" >
                </td>
                <td>
                    <textarea id="txtareaIntervieneObservacion" name="txtareaIntervieneObservacion" rows="2" cols="40"></textarea>
                </td>
                <td>
                    <button id="btnBuscarSerie">Buscar</button>
                </td>
                <td>
                    <div title="Eliminar" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass('ui-state-hover');" onmouseout="jQuery(this).removeClass('ui-state-hover')" onclick="deleteFilaTable(this);">
                        <span class="ui-icon ui-icon-trash"></span>
                    </div>
                </td>
            </tr>
            <?php foreach ($this->detSeries as $value) { ?>

                <tr>
                    <td>
                        <input value="<?php echo $value["idDetRetornoProd"]; ?>" type="hidden" name="txtidDetRetornoProd" id="txtidDetRetornoProd" />
                        <input value="<?php echo $value["idProdSeries"]; ?>" id="txtProdSeries"  name="txtProdSeries" class="ui-text-disable" disabled="disabled"  style="width:80px" >
                    </td>
                    <td>
                        <!--<input value="<?php echo $value["Producto"]; ?>" id="txtProducto"  name="txtProducto" class="ui-text-disable" disabled="disabled"  style="width:300px" >-->
                        <div  class="ui-text-disable" style="padding: .4em 5px; text-align: left; width:450px" id="txtProducto" name="txtProducto"><?php echo $value["Producto"]; ?></div>

                    </td>
                    <td>
                        <input value="<?php echo $value["nStock"]; ?>" id="txtStock"  name="txtStock" class="ui-text-disable" disabled="disabled"  style="width:70px" >
                    </td>
                    <td>
                        <input value="<?php echo $value["Serie"]; ?>" id="txtSerie"  name="txtSerie" class="ui-text-disable" disabled="disabled"  style="width:150px" >
                    </td>
                    <td>
                        <textarea id="txtareaIntervieneObservacion" name="txtareaIntervieneObservacion" rows="2" cols="40"><?php echo $value["vObserv"]; ?></textarea>
                    </td>
                    <td>
                        <button role="button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-hover" id="btnTestigoBuscarPersona"><span class="ui-button-text">Buscar</span></button>
                    </td>
                    <td>
                        <div title="Eliminar" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass('ui-state-hover');" onmouseout="jQuery(this).removeClass('ui-state-hover')" onclick="deleteFilaTable(this);">
                            <span class="ui-icon ui-icon-trash"></span>
                        </div>
                    </td>
                </tr>

            <?php } ?>
            </tbody>
        </table>
    </div>
<table>

    <tr>
        <td><button id="btncancelardet" name="btncancelardet">Cancelar</button></td>
        <td>
            <button id="btnguardar" name="btnguardar">Guardar</button>
        </td>
    </tr>

</table>
</div>


<div id="dialogBuscarSeries<?php echo $this->id; ?>">
    <table class="ui-panelLayout-main">
        <tr><td style="vertical-align: top;">
                <table style="width: 100%;">
                    <tr>
                        <td>
                            <table>
                                <tr class="rowBuscarContribuyente<?php echo $this->id; ?>">
                                    <td>
                                        <b>  Datos Busqueda</b>
                                    </td></tr>
                                <tr class="rowBuscarContribuyente<?php echo $this->id; ?>">
                                    <td style="text-align: left">
                                        <select id="cbotipob" name="cbotipob"  style="width:140px;" >
                                            <?php  echo $library->ContenidoCombo($TipoBusqueda, 5,0); ?>
                                        </select>
                                    </td>
                                    <td>Texto de busqueda:</td>
                                    <TD colspan="3">
                                        <input class="ui-text pnl" id="c_textbusqueda" value="<?php echo $this->idSalidaProd;?>" readonly onkeypress="if(event.keyCode==13){buscarMate();}" style="width:100%" />
                                    </TD>
                                    <td> &nbsp;&nbsp;</td>
                                </tr>
                            </table>
                        </td>
                        <td>
                            <button id="btnbuscar<?php echo $this->id; ?>" name="btnbuscar">Buscar</button>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" colspan="2">
                            <br/>
                            <div id="panelResult<?php echo $this->id; ?>">
                                <table id="tblResult<?php echo $this->id; ?>"></table>
                                <div id="ptblResult<?php echo $this->id; ?>"></div>
                                <input type="hidden" id="ctblResult" name="ctblResult<?php echo $this->id; ?>" value="" />
                            </div>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>






<script language="javascript">
    document.onkeydown = function(){
// a presonar el f5 se actuliza la misma pagina..
       /* if(window.event && window.event.keyCode == 116) {
            window.status="Por favor, Haga Click en Cerrar Sesión Para Salir del Sistema de Auditoría de Servicios";
            if (confirm('¿Estás seguro que deseas salir de la actual página?')) {
                alert("Pulsada la tecla F5");
            }else{
                return false;
            }

        }*/

        /*if(window.event && window.event.keyCode == 8){	// cuando el usuario presione el boton retroceso o borrar no regrese atras
          window.status="Por favor, Haga Click en Cerrar Sesión Para Salir del Sistema de Auditoría de Servicios";
            return false;
        }*/
    }
    //Al presionar la fecla de retroceso o de refresh del navegador se muestra un mensaje
    window.onbeforeunload = function() {
     //   return "¿Estás seguro que deseas salir de la actual página?"
    }


</script>


<script type="text/javascript">
themeComboBox();

buscarTecni = function(){
    parameters = {
        "idsigma":  $("#identradamat").val()
    };
    openDialogData1("almacen/buscartecnico", parameters, 660,500);
    //   window.open(path + "mantenimientos/backup", "_self");

};

$("#cbtitulo").combobox({
    selected: function(event, ui){
        var select = document.getElementById('cbtitulo');
        var selectedOption = this.options[select.selectedIndex];
        console.log(selectedOption.value + ': ' + selectedOption.text);
        $("#c_motivohd").val( selectedOption.text);
        if($("#cbtitulo").val()=='9'){
            $(".titulotext").show();
            $("#c_motivo").val("");

        }else{
            $(".titulotext").hide();
        }
    }
});
$("#cbreferencial").combobox({
    selected: function(event, ui){
        var select = document.getElementById('cbreferencial');
        var selectedOption = this.options[select.selectedIndex];
        console.log(selectedOption.value + ': ' + selectedOption.text);
        $("#referncialhd").val( selectedOption.text);
        if($("#cbreferencial").val()=='9'){
            $(".referencialtext").show();
        }else{
            $(".referencialtext").hide();
        }
    }
});

$("#cbformapago").combobox({
    selected: function(event, ui){
        var select = document.getElementById('cbformapago');
        var selectedOption = this.options[select.selectedIndex];
        console.log(selectedOption.value + ': ' + selectedOption.text);
        $("#formapagohd").val( selectedOption.text);
        if($("#cbformapago").val()=='9'){
            $(".formapagotext").show();
        }else{
            $(".formapagotext").hide();
        }
    }
});






    function imprimir(){
        var selr = $('#tblDetEntradaMat').jqGrid('getGridParam','selrow');
        var row = $("#tblDetEntradaMat").jqGrid('getRowData', selr);

        host = '<?php echo $this->util()->getPath(); ?>report/';
         window.open(host+"rptCotizacion.php?idCotiz="+ $("#identradamat").val() ,'_blank');
     //console.log(host);

    }





//Funcion para regresar al la grilla naterior
    function Cancelar(){
        window.open(path + "almacen/salidaprod", "_self");
    }



var invocaBusPersona = 0;


cargarCategoria = function () {
    $("#txtLicenciaCategoria").val('');
    contenidocomboContenedor('#cboLicenciaCategoria', $("#cboLicenciaClase").val())

}
actualizarSerie=function(a){

    if(a == "" || a == undefined){
        openDialogWarning("Seleccione un registro.");
        return;
    }
    console.log(a);
    parameters = {
        "id": a
    };


            $.ajax({
                url: jQuery.scriptPath + "index.php/almacen/actualizarserie",
                type: 'POST',
                cache: false,
                data: parameters,
                beforeSend: function (data) {
                },
                success: function (requestData) {
                    $("#result").html(requestData);
                    var datos=JSON.parse(requestData);
                    console.log(datos[0].ok);
                },
                error: function (requestData, strError, strTipoError) {
                    $("#result").html("Error " + strTipoError + ': ' + strError);
                },
                complete: function (requestData, exito) {
                }
            });
};

buscarSeriesSalida = function (d) {
    console.log(d);
    __gridConfigSeries.data = [];
    __gridConfigSeries.ondblClickRow = function (rowid) {
        row = $("#tblResult").jqGrid('getRowData', rowid);
        if (invocaBusPersona == 1) {
            $(d).parent().parent().find("input[name=txtProdSeries]").val(row.idProdSeries);
            $(d).parent().parent().find("input[name=txtStock]").val(row.nStock);
            $(d).parent().parent().find("div[name=txtProducto]").html(row.producto );
            $(d).parent().parent().find("input[name=txtSerie]").val(row.vNroSerie);
        }
        actualizarSerie(row.idProdSeries);
        closeDialog("dialogBuscarSeries");

    };
    BuscadorSeries.bindkeysPersona = {"onEnter": __gridConfigSeries.ondblClickRow};
    BuscadorSeries.buscar();
    $("#tblResult").jqGrid("clearGridData");
    if ($(".rowBuscarContribuyente").hasClass("row-hide")) {
        $(".rowBuscarContribuyente").removeClass("row-hide");
    }
    //$(".rowBuscarPredio").css({display: "none"});
    $("#dialogBuscarSeries").dialog("open");
    $("#c_codigocontrib").focus();
};


var i = 1;

deleteFilaTable = function (d) {
    $(d).parent().parent().remove();
}
agregarFilaTable = function (id) {
    var id_combobox = "";

    $("#" + id + " tbody tr:first").clone().show().find("input,select,button").each(function () {
        if ($(this).is("select")) {
            id_combobox = this.id + '_' + id + "_" + i;
        }
        $(this).attr({
            'id': this.id + '_' + id + "_" + i,
            'value': ''
        });
    }).end().appendTo("#" + id);

    themeComboBox("#" + id_combobox);
    $("#btnBuscarSerie_" + id + "_" + i).button().click(function () {
        invocaBusPersona = 1;
        buscarSeriesSalida(this);

    });
    i++;
}

$(function () {
    $("#fecretorno").datepicker({showOn: "button", buttonImage: pathImage + "calendar.gif", buttonImageOnly: true, dateFormat: "dd/mm/yy"});
    $("#fechasta").datepicker({showOn: "button", buttonImage: pathImage + "calendar.gif", buttonImageOnly: true, dateFormat: "dd/mm/yy"});
    $("#div_titulo").html("Almacen => Retorno Productos");

    $("#btnbuscartec").button({icons: {primary: "ui-icon-search"}});
    $("#btnguardar").button({icons: {primary: "ui-icon-disk"}}).click(function(){
        guardar();
    });
    $("#btncancelardet").button({icons: {primary: "ui-icon-cancel"}}).click(function () {
        Cancelar('');
    });

// clone inspector

    $("#btnBuscarMaterial").button("destroy");
    agregarFilaTable("tableRetornoProd");
    $("#btnRegistroAgregar").click(function () {
        agregarFilaTable("tableRetornoProd");
    });
    $("#btnRegistroAgregar").button({icons: {primary: "ui-icon-plus"}});
//fin clone inspector

    //--- Buscar persona
    Persona.init(true);
    BuscadorSeries.init(BuscadorSeries.MODO_CERO, true);
    BuscadorSeries.configurarDialog();
    //---- fin buscar persona


  /*  dialogPersona = $("#dialogBuscarPersona").dialog({
        autoOpen: false,
        height: 100,
        width: 100,
        modal: true,
        buttons: {
//                "Aceptar": function () {
//
//                },
            Cerrar: function () {
                //invocaBusPersona = 0;
                dialogPersona.dialog("close");
            }
        },
        close: function () {
            invocaBusPersona = 0;
            //dialogPersona.dialog("close");
        }
    });*/



    function guardar() {

        var detalleretorno = {};
        var objSeries = [];

        //Datos generales del salida de objSeries
        detalleretorno.idRetornoProd = $("#idRetornoProd").val();
        detalleretorno.idSalidaProd = $("#idSalidaProd").val();
        detalleretorno.obra = $("#txtobra").val();
        detalleretorno.lugar = $("#txtlugar").val();
        detalleretorno.fecha = $("#fecretorno").val();
        detalleretorno.idtecnico = $("#txtidtecnico").val();

        //Datos del detalle
        $('#tableRetornoProd > tbody  > tr').each(function () {
            var detSeries = {};
            if ($(this).find("[name=txtProdSeries]").val() != '' ) {
                detSeries.idDetRetornoProd = $(this).find("[name=txtidDetRetornoProd]").val();
                detSeries.idProdSeries = $(this).find("[name=txtProdSeries]").val();
                //detSeries.cantidadRetorno = $(this).find("[name=txtCantidadretorno]").val();
                detSeries.observacion = $(this).find("[name=txtareaIntervieneObservacion]").val();
                objSeries.push(detSeries);
            }
        });
        detalleretorno.objSeries = objSeries;

        var pRetornoMat = {};
        pRetornoMat.objSalidaProd = JSON.stringify(detalleretorno);
        //console.log(JSON.stringify(pPapeleta));
        //console.log(papeleta);
        $.post(path + "almacen/guardarretornoprod", pRetornoMat, function (data) {
            console.log(data);
            console.log(data["idRetornoProd"]);
            if (data["a"] == '0') {
                openDialogInfo(data["b"], "280", "150", null, function () {
                    return;
                });
            }else{
              // $("#iframeUploadDocPapeleta").attr("src", path + "papeleta/uploadarchivo?mpapeleta=" + data.idsigma);
              //  dialogUpload.dialog("open");
                window.open(path + "almacen/salidaprod", "_self");
            }

//
        }, 'json');
    };
})
</script>