<?php
$library = new Libreria_Pintar();
$TipoBusqueda = array(array("0", "GENERAL"), array("1", "ID"), array("2", "SERIE"), array("3", "PRODUCTO"));
?>
<style>
    #tableSeries {
        margin: 0 2em 0em 0;
        border-collapse: collapse;
        width: 100%;
    }

    #tableSeries td,
    #tableSeries th {
        border: 1px solid #eee;
        padding: .4em 5px;
        text-align: left;
    }


    #tableTecnicos {
        margin: 0em 2em 0em 0em;
        border-collapse: collapse;
        width: 95%;
    }

    #tableTecnicos td,
    #tableTecnicos th {
        border: 1.5px solid #eee;
        padding: .4em 5px;
        text-align: left;
    }
</style>

<div id="panelMantenimientoCotizacion" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 99%;margin: 1px; height:95%;">
    <div class="ui-widget ui-state-rojo ui-corner-top ui-title">
        <label>Mantenimiento - Salida Producto</label>
    </div>
    <input type="hidden" id="idsalidaprod" name="idsalidaprod" value="<?php echo $this->idSalidaProd; ?>">

    <div id="panelPapeleta" align="center" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;padding-bottom: 5px;">
        <table class="ui-panelLayout-main">
            <tr>
                <td style="vertical-align: top;">
                    <table border="0" style="margin-left:45px;">
                        <tr>
                            <td style="text-align: left" colspan="4">Obra:</td>
                        </tr>
                        <tr>
                            <td colspan="4">
                                <input class="ui-text" id="txtobra" value="<?php echo $this->obra; ?>" maxlength="100" style="width:100%" />
                            </td>
                        </tr>
                        <tr>
                            <td><br></td>
                        </tr>
                        <tr class="rowcoti">

                            <td width="100" style="text-align: left">Fecha:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" style="text-align: left">Lugar</td>
                        </tr>

                        <tr class="rowbcoti" id="panelbcoti">

                            <td>
                                <input type="text" id="fecsalida" value="<?php echo $this->dFecSalida; ?>" class="ui-text-disable " readonly style="text-align: left;width: 80px;" />
                            </td>
                            <td>&nbsp; </td>
                            <td class="soloSolesa">&nbsp;<input type="text" class="ui-text pnl" id="txtlugar" value="<?php echo $this->lugar; ?>" style="width:96%" /></td>

                        </tr>
                        <tr>
                            <td><br></td>
                        </tr>
                        <tr>
                            <td width="230" style="text-align: left">Nro de Cotizacion:</td>
                            <td width="10">&nbsp;</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" colspan="5" style="text-align: left"></td>
                            <td width="150">&nbsp;</td>
                        </tr>
                        <tr>

                            <td colspan="3">
                                <input class="ui-text-disable pnl" type="hidden" readonly id="idCotizacion" value="<?php echo $this->idCotiz; ?>" style="width:100%" />
                                <input class="ui-text-disable pnl" readonly id="nroCotizacion" value="<?php echo $this->vnroCot; ?>" style="width:100%" />
                            </td>

                            <td colspan="5" style="text-align: left;">
                            </td>
                            <td rowspan="1">
                                <button id="btnbuscarCotizacion" name="btnbuscarCotizacion" onclick="buscarCotizacion()">Buscar Cotizacion</button>
                            </td>
                        </tr>


                        <tr>
                            <td width="230" style="text-align: left">Cliente:</td>
                            <td width="10">&nbsp;</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" colspan="5" style="text-align: left"></td>
                            <td width="150">&nbsp;</td>
                        </tr>
                        <tr class="rowBuscarContribuyente" id="panelBuscarContribuyente">

                            <td colspan="3">
                                <input class="ui-text-disable pnl" type="hidden" readonly id="codigoCliente" value="<?php echo $this->idCliente; ?>" style="width:100%" />
                                <input class="ui-text-disable pnl" readonly id="nombreCliente" value="<?php echo $this->nomCliente; ?>" style="width:100%" />
                            </td>

                            <td colspan="5" style="text-align: left;">
                            </td>
                            <td rowspan="1">
                                <button id="btnbuscarClie" name="btnbuscarClie" onclick="buscarCli()">Buscar Cliente</button>
                            </td>
                        </tr>


                        <tr>
                            <td width="230" style="text-align: left">Tecnico encargado:</td>
                            <td width="10">&nbsp;</td>
                            <td width="10">
                                <div style="text-align: left">
                                    <button id="btnTecnicoAgregar">Agregar Técnico</button>
                                </div>
                            </td>
                            <td width="230" colspan="5" style="text-align: left"></td>
                            <td width="150">&nbsp;</td>
                        </tr>
                        <tr class="rowBuscarContribuyente" id="panelBuscarContribuyente" style="display: none;">

                            <td colspan="3">
                                <input class="ui-text-disable pnl" type="hidden" readonly id="txtidtecnico" value="<?php echo $this->idtecnico; ?>" style="width:100%" />
                                <input class="ui-text-disable pnl" readonly id="txtnombretecnico" value="<?php echo $this->nomtecnico; ?>" style="width:100%" />
                            </td>

                            <td colspan="5" style="text-align: left;">
                                <!-- <input class="ui-text-disable pnl" readonly id="nrodoc"   value="<?php echo $this->vnrodoprov; ?>"  style="width:50%" /> -->
                            </td>
                            <td rowspan="1">
                                <button id="btnbuscartec" name="btnbuscartec" onclick="buscarTecni()">Buscar Tecnico</button>
                            </td>
                        </tr>

                        <tr>
                            <td colspan="5">
                                <table id="tableTecnicos" border="1" class="ui-widget ui-widget-content">
                                    <tbody>
                                        <tr style="display: none;">
                                            <td>
                                                <input type="hidden" name="txtidDetTecnicoProd" id="txtidDetTecnicoProd" />
                                                <input type="hidden" id="txtIdTecnico" name="txtIdTecnico" class="ui-text-disable" disabled="disabled" style="width:450px">
                                                <input id="txtTecnico" name="txtTecnico" class="ui-text-disable" disabled="disabled" style="width:450px">
                                            </td>
                                            <td>
                                                <button id="btnTestigoBuscarTecnico">Buscar Técnico</button>
                                            </td>
                                            <td>
                                                <div title="Eliminar" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit" onmouseover="jQuery(this).addClass('ui-state-hover');" onmouseout="jQuery(this).removeClass('ui-state-hover')" onclick="deleteFilaTable(this);">
                                                    <span class="ui-icon ui-icon-trash">Quitar</span>
                                                </div>
                                            </td>
                                        </tr>
                                        <?php $cont = 0;
                                        foreach ((array)$this->detTecnicoProd as $value) {
                                            $cont++ ?>
                                            <tr>
                                                <td>
                                                    <input value="<?php echo $value["idDetTecnicoProd"]; ?>" type="hidden" name="txtidDetTecnicoProd" id="txtidDetTecnicoProd" />
                                                    <input value="<?php echo $value["idTecnico"]; ?>" type="hidden" id="txtIdTecnico" name="txtIdTecnico" class="ui-text-disable" disabled="disabled" style="width:450px">
                                                    <input value="<?php echo $value["NombreTecnico"]; ?>" id="txtTecnico" name="txtTecnico" class="ui-text-disable" disabled="disabled" style="width:450px">
                                                </td>
                                                <td>
                                                    <button id="btnTestigoBuscarTecnico" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-hover" onclick="buscarTecni(this)"><span class="ui-button-text">Buscar Tecnico</span></button>
                                                </td>
                                                <td>
                                                    <div title="Eliminar" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit" onmouseover="jQuery(this).addClass('ui-state-hover');" onmouseout="jQuery(this).removeClass('ui-state-hover')" onclick="deleteFilaTable(this);">
                                                        <span class="ui-icon ui-icon-trash">Quitar</span>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </td>
                        </tr>


                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>


    <div id="panelDatosConductor" align="center" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;height: 100%;margin: 3px;">
        <div class="ui-widget ui-state-default ui-corner-top ui-title">
            <label>SERIES </label>
        </div>
        <div style="text-align: left">
            <button id="btnTestigoAgregar">Agregar</button>
        </div>
        <table id="tableSeries" border="1" class="ui-widget ui-widget-content">
            <thead>
                <tr class="ui-widget-header">
                    <th>Codigo Serie</th>
                    <th>Producto</th>
                    <th>Modelo</th>
                    <th>H. Stock</th>
                    <th>Serie</th>
                    <th></th>
                    <th>Buscar</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr style="display: none;">
                    <td>
                        <input type="hidden" name="txtidDetSalidaProd" id="txtidDetSalidaProd" />
                        <input id="txtCodigoSerie" name="txtCodigoSerie" class="ui-text-disable" disabled="disabled" style="width:80px">
                    </td>
                    <td>
                        <!-- <input id="txtNombreMaterial" type="hidden" name="txtNombreMaterial" class="ui-text-disable" disabled="disabled"  style="width:380px" >-->
                        <div class="ui-text-disable" style="padding: .4em 5px; text-align: left; width:300px" id="txtNombreProd" name="txtNombreProd">&nbsp;</div>
                    </td>
                    <td>
                        <div class="ui-text-disable" style="padding: .4em 5px; text-align: left; width:90px" id="txtModelo" name="txtModelo">&nbsp;</div>
                    </td>
                    <td>
                        <input id="txtStock" name="txtStock" class="ui-text-disable" disabled="disabled" style="width:50px">
                    </td>
                    <td>
                        <input id="txtSerie" name="txtSerie" class="ui-text-disable" disabled="disabled" style="width:180px">
                    </td>
                    <td>
                        <input type="text" id="fecsalidaProducto" name="fecsalidaProducto" class="ui-text-disable " readonly style="text-align: left;width: 90px; " />
                    </td>
                    <!--<td>
                    <input id="txtFechaSalida"  name="txtFechaSalida" class="ui-text-disable" disabled="disabled"  style="width:250px" >
                </td>-->
                    <td>
                        <button id="btnTestigoBuscarPersona">Buscar</button>
                    </td>
                    <td>
                        <div title="Eliminar" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit" onmouseover="jQuery(this).addClass('ui-state-hover');" onmouseout="jQuery(this).removeClass('ui-state-hover')" onclick="deleteFilaTable(this);">
                            <span class="ui-icon ui-icon-trash"></span>
                        </div>
                    </td>
                </tr>
                <?php $cont = 0;
                foreach ((array)$this->detSalidaProd as $value) {
                    $cont++ ?>

                    <tr>
                        <td>
                            <input value="<?php echo $value["idDetSalidaProd"]; ?>" type="hidden" name="txtidDetSalidaProd" id="txtidDetSalidaProd" />
                            <input value="<?php echo $value["idProdSeries"]; ?>" id="txtCodigoSerie" name="txtCodigoSerie" class="ui-text-disable" disabled="disabled" style="width:80px">
                        </td>
                        <td>
                            <!--<input value="<?php echo $value["Producto"]; ?>" id="txtNombreMaterial" type="hidden" name="txtNombreMaterial" class="ui-text-disable" disabled="disabled"  style="width:380px" >-->
                            <div class="ui-text-disable" style="padding: .4em 5px; text-align: left; width:300px" id="txtNombreProd" name="txtNombreProd"><?php echo $value["Producto"]; ?></div>
                        </td>
                        <td>
                            <div class="ui-text-disable" style="padding: .4em 5px; text-align: left; width:90px" id="txtModelo" name="txtModelo">&nbsp;<?php echo $value["vModelo"]; ?></div>
                        </td>
                        <td>
                            <input value="<?php echo $value["nStock"]; ?>" id="txtStock" name="txtStock" class="ui-text-disable" disabled="disabled" style="width:50px">
                        </td>
                        <td>
                            <input value="<?php echo $value["Serie"]; ?>" id="txtSerie" name="txtSerie" class="ui-text-disable" disabled="disabled" style="width:180px">
                        </td>
                        <td style="width: 120px !important;">
                            <input type="text" id="fecsalidaProducto<?php echo $cont ?>" name="fecsalidaProducto" value="<?php echo $value["dFecSalidaProducto"]; ?>" class="ui-text-disable inputdatepicker" readonly style="text-align: left;width: 90px;" />
                        </td>
                        <!--<td>
                    <input  value="<?php echo $value["fechareg"]; ?>" id="txtFechaSalida"  name="txtFechaSalida" class="ui-text-disable" disabled="disabled"  style="width:250px" >
                </td>-->
                        <td>
                            <button role="button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-hover" id="btnTestigoBuscarPersona"><span class="ui-button-text">Buscar</span></button>
                        </td>
                        <td>
                            <div title="Eliminar" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit" onmouseover="jQuery(this).addClass('ui-state-hover');" onmouseout="jQuery(this).removeClass('ui-state-hover')" onclick="deleteFilaTable(this);">
                                <span class="ui-icon ui-icon-trash"></span>
                            </div>
                        </td>
                    </tr>

                <?php } ?>
            </tbody>
        </table>
    </div>


    <div>
        <table align="left" style="width: 100%">

            <tr>

                <td>Observaciones: </td>



            </tr>

            <tr>
                <td>
                    <textarea name="txtObs" id="txtObs" rows="4" style="width: 600px; margin-left:3px "><?php echo $this->obs; ?> </textarea>
                </td>
            </tr>
        </table>
    </div>
    <table>

        <tr>
            <td><button id="btncancelardet" name="btncancelardet">Cancelar</button></td>
            <td>
                <button id="btnguardar" name="btnguardar">Guardar</button>
            </td>
        </tr>

    </table>
</div>


<div id="dialogBuscarSeries<?php echo $this->id; ?>">
    <table class="ui-panelLayout-main">
        <tr>
            <td style="vertical-align: top;">
                <table style="width: 100%;">
                    <tr>
                        <td>
                            <table>
                                <tr class="rowBuscarContribuyente<?php echo $this->id; ?>">
                                    <td>
                                        <b> Datos Busqueda</b>
                                    </td>
                                </tr>
                                <tr class="rowBuscarContribuyente<?php echo $this->id; ?>">
                                    <td style="text-align: left">
                                        <select id="cbotipob" name="cbotipob" style="width:140px;">
                                            <?php echo $library->ContenidoCombo($TipoBusqueda, $this->ctipmon, 0); ?>
                                        </select>
                                    </td>
                                    <td>Texto de busqueda:</td>
                                    <TD colspan="3">
                                        <input class="ui-text pnl" id="c_textbusqueda" name="c_textbusqueda" onkeypress="if(event.keyCode==13){BuscadorSeries.buscar();}" style="width:100%" />
                                    </TD>
                                    <td> &nbsp;&nbsp;</td>
                                </tr>
                            </table>
                        </td>
                        <td>
                            <button id="btnbuscar<?php echo $this->id; ?>" name="btnbuscar">Buscar</button>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" colspan="2">
                            <br />
                            <div id="panelResult<?php echo $this->id; ?>">
                                <table id="tblResult<?php echo $this->id; ?>"></table>
                                <div id="ptblResult<?php echo $this->id; ?>"></div>
                                <input type="hidden" id="ctblResult" name="ctblResult<?php echo $this->id; ?>" value="" />
                            </div>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>






<script language="javascript">
    document.onkeydown = function() {
        // a presonar el f5 se actuliza la misma pagina..
        /* if(window.event && window.event.keyCode == 116) {
             window.status="Por favor, Haga Click en Cerrar Sesión Para Salir del Sistema de Auditoría de Servicios";
             if (confirm('¿Estás seguro que deseas salir de la actual página?')) {
                 alert("Pulsada la tecla F5");
             }else{
                 return false;
             }

         }*/

        /*if(window.event && window.event.keyCode == 8){	// cuando el usuario presione el boton retroceso o borrar no regrese atras
          window.status="Por favor, Haga Click en Cerrar Sesión Para Salir del Sistema de Auditoría de Servicios";
            return false;
        }*/
    }
    //Al presionar la fecla de retroceso o de refresh del navegador se muestra un mensaje
    window.onbeforeunload = function() {
        //   return "¿Estás seguro que deseas salir de la actual página?"
    }
</script>


<script type="text/javascript">
    themeComboBox();



    $("#cbtitulo").combobox({
        selected: function(event, ui) {
            var select = document.getElementById('cbtitulo');
            var selectedOption = this.options[select.selectedIndex];
            console.log(selectedOption.value + ': ' + selectedOption.text);
            $("#c_motivohd").val(selectedOption.text);
            if ($("#cbtitulo").val() == '9') {
                $(".titulotext").show();
                $("#c_motivo").val("");

            } else {
                $(".titulotext").hide();
            }
        }
    });
    $("#cbreferencial").combobox({
        selected: function(event, ui) {
            var select = document.getElementById('cbreferencial');
            var selectedOption = this.options[select.selectedIndex];
            console.log(selectedOption.value + ': ' + selectedOption.text);
            $("#referncialhd").val(selectedOption.text);
            if ($("#cbreferencial").val() == '9') {
                $(".referencialtext").show();
            } else {
                $(".referencialtext").hide();
            }
        }
    });

    $("#cbformapago").combobox({
        selected: function(event, ui) {
            var select = document.getElementById('cbformapago');
            var selectedOption = this.options[select.selectedIndex];
            console.log(selectedOption.value + ': ' + selectedOption.text);
            $("#formapagohd").val(selectedOption.text);
            if ($("#cbformapago").val() == '9') {
                $(".formapagotext").show();
            } else {
                $(".formapagotext").hide();
            }
        }
    });






    function imprimir() {
        var selr = $('#tblDetEntradaMat').jqGrid('getGridParam', 'selrow');
        var row = $("#tblDetEntradaMat").jqGrid('getRowData', selr);

        host = '<?php echo $this->util()->getPath(); ?>report/';
        window.open(host + "rptCotizacion.php?idCotiz=" + $("#identradamat").val(), '_blank');
        //console.log(host);

    }





    //Funcion para regresar al la grilla naterior
    function Cancelar() {
        parameters = {
            "idSalidaprod": $("#idsalidaprod").val()
        };
        console.log(parameters);
        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/cancelarsalidaprod",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function(data) {},
            success: function(requestData) {
                // $("#result").html(requestData);
                //  var datos=JSON.parse(requestData);
                window.open(path + "almacen/salidaprod", "_self");
            },
            error: function(requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function(requestData, exito) {}
        });

    };



    var invocaBusPersona = 0;


    cargarCategoria = function() {
        $("#txtLicenciaCategoria").val('');
        contenidocomboContenedor('#cboLicenciaCategoria', $("#cboLicenciaClase").val())

    };

    actualizarSerie = function(a) {

        if (a == "" || a == undefined) {
            openDialogWarning("Seleccione un registro.");
            return;
        }
        console.log(a);
        parameters = {
            "id": a
        };


        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/actualizarseriesalida",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function(data) {},
            success: function(requestData) {
                $("#result").html(requestData);
                var datos = JSON.parse(requestData);
                console.log(datos[0].ok);
            },
            error: function(requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function(requestData, exito) {}
        });
    };


    buscarSeriesSalida = function(d) {
        //  console.log(d);
        __gridConfigSeries.data = [];
        __gridConfigSeries.ondblClickRow = function(rowid) {
            row = $("#tblResult").jqGrid('getRowData', rowid);
            if (invocaBusPersona == 1) {
                if (row.nStock <= row.nStockMinimo) {
                    openDialogWarning("Comprar Material. Stock menor al Stock Minimo.");
                }
                $(d).parent().parent().find("input[name=txtCodigoSerie]").val(row.idProdSeries);
                $(d).parent().parent().find("input[name=txtStock]").val(row.nStock - 1);
                $(d).parent().parent().find("div[name=txtNombreProd]").html(row.producto);
                $(d).parent().parent().find("div[name=txtModelo]").html(row.vModelo); //18-01-2021
                $(d).parent().parent().find("input[name=txtSerie]").val(row.vNroSerie);

            }
            actualizarSerie(row.idProdSeries);
            closeDialog("dialogBuscarSeries");

        };
        BuscadorSeries.bindkeysPersona = {
            "onEnter": __gridConfigSeries.ondblClickRow
        };
        BuscadorSeries.buscar();
        $("#tblResult").jqGrid("clearGridData");
        if ($(".rowBuscarContribuyente").hasClass("row-hide")) {
            $(".rowBuscarContribuyente").removeClass("row-hide");
        }
        //$(".rowBuscarPredio").css({display: "none"});
        $("#dialogBuscarSeries").dialog("open");
        $("#c_codigocontrib").focus();
    };

    var i = 1;

    deleteFilaTable = function(d) {
        var serie = $(d).parent().parent().find("input[name=txtCodigoSerie]").val();
        var iddetsalidaprod = $(d).parent().parent().find("input[name=txtidDetSalidaProd]").val();


        if (iddetsalidaprod == "" || iddetsalidaprod == undefined) {
            $(d).parent().parent().remove();
            parameters = {
                "idProdSerie": serie,
                "idDetsalida": 0
            };
            $.ajax({
                url: jQuery.scriptPath + "index.php/almacen/salidaprodregresaestadostockprodseries",
                type: 'POST',
                cache: false,
                data: parameters,
                beforeSend: function(data) {},
                success: function(requestData) {},
                error: function(requestData, strError, strTipoError) {
                    $("#result").html("Error " + strTipoError + ': ' + strError);
                },
                complete: function(requestData, exito) {}
            });
            return;
        }

        parameters = {
            "id": serie,
            "idDetsalida": iddetsalidaprod
        };
        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/eliminarseriesalidaprod",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function(data) {},
            success: function(requestData) {
                $("#result").html(requestData);
                var datos = JSON.parse(requestData);
                console.log(datos[0][1]);
                console.log(datos[0][0]);
                if (datos[0][0] == "ok") {
                    $(d).parent().parent().remove();
                } else {
                    openDialogInfo(datos[0][1], "280", "150", null, function() {
                        return;
                    });
                }

            },
            error: function(requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function(requestData, exito) {}
        });

    };

    agregarFilaTableTecnico = function(id) {
        var id_combobox = "";

        $("#" + id + " tbody tr:first").clone().show().find("input,select,button").each(function() {
            if ($(this).is("select")) {
                id_combobox = this.id + '_' + id + "_" + i;
            }
            $(this).attr({
                'id': this.id + '_' + id + "_" + i,
                'value': ''
            });
        }).end().appendTo("#" + id);

        themeComboBox("#" + id_combobox);
        $("#btnTestigoBuscarTecnico_" + id + "_" + i).button().click(function() {
            invocaBusPersona = 1;
            // buscarMaterialSalida(this);
            buscarTecni(this);

        });

        i++;
    }
    agregarFilaTable = function(id) {
        var id_combobox = "";

        $("#" + id + " tbody tr:first").clone().show().find("input,select,button").each(function() {
            if ($(this).is("select")) {
                id_combobox = this.id + '_' + id + "_" + i;
            }
            $(this).attr({
                'id': this.id + '_' + id + "_" + i,
                'value': ''
            });
        }).end().appendTo("#" + id);

        themeComboBox("#" + id_combobox);
        $("#btnTestigoBuscarPersona_" + id + "_" + i).button(ICON_SEARCH).click(function() {
            invocaBusPersona = 1;
            buscarSeriesSalida(this);

        });
        $("#fecsalidaProducto_" + id + "_" + i).datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });
        $("#fecsalidaProducto_" + id + "_" + i).datepicker("setDate", new Date());

        i++;

        for (index = 1; index < 20; index++) {
            $("#fecsalidaProducto" + index).datepicker({
                showOn: "button",
                buttonImage: pathImage + "calendar.gif",
                buttonImageOnly: true,
                dateFormat: "dd/mm/yy"
            });
        }
    };

    buscarTecni = function(d) {
        // console.log(d);
        parameters = {
            "idsigma": $("#identradamat").val()
        };
        // openDialogData1("almacen/buscartecnico", parameters, 660, 500);

        openDialogDataFunction1("almacen/buscartecnico", parameters, 660, 500, "Buscar tecnico.!", cargarTecn = function() {
            var selr = $('#tblListaPersona').jqGrid('getGridParam', 'selrow');
            var row = $("#tblListaPersona").jqGrid('getRowData', selr);
            // console.log(row);
            // invocaBusPersona == 1 && 
            if (row.idTecnico != undefined) {
                $(d).parent().parent().find("input[name=txtIdTecnico]").val(row.idTecnico);
                $(d).parent().parent().find("input[name=txtTecnico]").val(row.vNombre);
                closeDialog("jqDialog1");
            }
        }, {});

        // openDialogDataFunction1("almacen/buscartecnico", parameters, "750", "625", "Buscar tecnico.!!!", function() {
        //     $("#txt_idsigma").val(row.idsigma);
        //     $("#txtnumero").val(row.dnumero);
        //     $("#txtviacentrpob").val(row.tnomvia);
        //     $("#txtczoncat").val(row.czoncat);
        //     habpredio();
        // });
    };


    buscarCli = function() {
        parameters = {
            "idsigma": $("#identradamat").val()
        };
        openDialogData1("almacen/buscarcliente", parameters, 660, 500);
        //   window.open(path + "mantenimientos/backup", "_self");

    };
    buscarCotizacion = function() {
        parameters = {
            "idsigma": $("#identradamat").val()
        };
        openDialogData1("almacen/buscarcotizacion", parameters, 660, 500);
        //   window.open(path + "mantenimientos/backup", "_self");

    };

    $(function() {
        $("#fecsalida").datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });
        $("#fechasta").datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });

        $("#btnbuscartec").button(ICON_SEARCH);
        $("#btnguardar").button({
            icons: {
                primary: "ui-icon-disk"
            }
        }).click(function() {
            Guardar();
        });
        $("#btncancelardet").button({
            icons: {
                primary: "ui-icon-cancel"
            }
        }).click(function() {
            Cancelar('');
        });

        // clone inspector
        $("#btnbuscarClie").button({
            icons: {
                primary: "ui-icon-search"
            }
        });
        $("#btnbuscarCotizacion").button({
            icons: {
                primary: "ui-icon-search"
            }
        });
        $("#btnTestigoBuscarPersona").button("destroy");
        agregarFilaTable("tableSeries");
        $("#btnTestigoAgregar").click(function() {
            agregarFilaTable("tableSeries");
        });
        $("#btnTestigoAgregar").button({
            icons: {
                primary: "ui-icon-plus"
            }
        });
        //fin clone inspector

        // Clonar tecnico

        agregarFilaTableTecnico("tableTecnicos");
        $("#btnTecnicoAgregar").click(function() {
            agregarFilaTableTecnico("tableTecnicos");
        });
        $("#btnTecnicoAgregar").button({
            icons: {
                primary: "ui-icon-plus"
            }
        });
        //fin clonar tecnico

        //--- Buscar serie
        Persona.init(true);
        BuscadorSeries.init(BuscadorSeries.MODO_FULL, true);
        BuscadorSeries.configurarDialog();
        //---- fin buscar serie


        function Guardar() {

            var detallesalida = {};
            var series = [];
            var tecnicos = [];


            //Datos generales del salida de series
            detallesalida.idsalidaprod = $("#idsalidaprod").val();
            detallesalida.obra = $("#txtobra").val();
            detallesalida.lugar = $("#txtlugar").val();
            detallesalida.fecha = $("#fecsalida").val();
            detallesalida.idtecnico = $("#txtidtecnico").val();
            detallesalida.idcliente = $("#codigoCliente").val();
            detallesalida.idcotizacion = $("#idCotizacion").val();
            detallesalida.obs = $("#txtObs").val();

            // if ($("#txtidtecnico").val() == "") {
            //     openDialogWarning("Seleccione un tecnico encargado.");
            //     return;
            // }
            if ($("#fecsalida").val() == "") {
                openDialogWarning("Seleccione la fecha.");
                return;
            }
            //Datos series
            $('#tableSeries > tbody  > tr').each(function() {
                var detseries = {};
                if ($(this).find("[name=txtCodigoSerie]").val() != '') {
                    detseries.idDetSalidaProd = $(this).find("[name=txtidDetSalidaProd]").val();
                    detseries.idSerie = $(this).find("[name=txtCodigoSerie]").val();
                    detseries.vSerie = $(this).find("[name=txtSerie]").val();
                    detseries.stock = $(this).find("[name=txtStock]").val();
                    detseries.fecsalidaProducto = $(this).find("[name=fecsalidaProducto]").val();
                    series.push(detseries);
                }
            });
            detallesalida.series = series;

            //Datos Tecnicos
            $('#tableTecnicos > tbody  > tr').each(function() {
                var detTecnicos = {};
                if ($(this).find("[name=txtIdTecnico]").val() != '') {
                    detTecnicos.idDetTecnicoProd = $(this).find("[name=txtidDetTecnicoProd]").val();
                    detTecnicos.idTecnico = $(this).find("[name=txtIdTecnico]").val();
                    detTecnicos.NombreTecnico = $(this).find("[name=txtTecnico]").val();
                    tecnicos.push(detTecnicos);
                }
            });
            detallesalida.tecnicos = tecnicos;

            var pSalidaProd = {};
            pSalidaProd.objSalidaProd = JSON.stringify(detallesalida);
            //console.log(JSON.stringify(pPapeleta));
            //console.log(papeleta);


            $.post(path + "almacen/guardarsalidaprod", pSalidaProd, function(data) {
                console.log(data);
                console.log(data["idsalidaprod"]);
                if (data["a"] == '0') {
                    openDialogInfo(data["b"], "280", "150", null, function() {
                        return;
                    });
                } else {
                    // $("#iframeUploadDocPapeleta").attr("src", path + "papeleta/uploadarchivo?mpapeleta=" + data.idsigma);
                    //  dialogUpload.dialog("open");
                    window.open(path + "almacen/salidaprod", "_self");
                }

            }, 'json');


        };
    })
</script>