<?php
$library = new Libreria_Pintar();
$TipoBusqueda = array(array("0", "GENERAL"), array("1", "ID"), array("2", "NOMBRE"), array("3", "TIPOMATERIAL"), array("4", "MARCA"));
?>
<style>
    #tableTestigos {
        margin: 0 2em 0em 0;
        border-collapse: collapse;
        width: 100%;
    }

    #tableTestigos td,
    #tableTestigos th {
        border: 1px solid #eee;
        padding: .4em 5px;
        text-align: left;
    }
</style>

<div id="panelMantenimientoCotizacion" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 99%;margin: 1px; height:95%;">
    <div class="ui-widget ui-state-rojo ui-corner-top ui-title">
        <label>Mantenimiento - Salida Materiales</label>
    </div>
    <input type="hidden" id="idsalidamat" name="idsalidamat" value="<?php echo $this->idSalidaMat; ?>">

    <div id="panelPapeleta" align="center" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;margin: 3px;padding-bottom: 5px;">
        <table class="ui-panelLayout-main">
            <tr>
                <td style="vertical-align: top;">
                    <table border="0" style="margin-left:45px;">
                        <tr>
                            <td style="text-align: left" colspan="4">Obra:</td>
                        </tr>
                        <tr>
                            <td colspan="4">
                                <input class="ui-text" id="txtobra" value="<?php echo $this->obra; ?>" maxlength="100" style="width:100%" />
                            </td>
                        </tr>
                        <tr>
                            <td><br></td>
                        </tr>
                        <tr class="rowcoti">

                            <td width="100" style="text-align: left">Fecha:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" style="text-align: left">Lugar</td>
                        </tr>

                        <tr class="rowbcoti" id="panelbcoti">

                            <td>
                                <input type="text" id="fecsalida" value="<?php echo $this->dFecSalida; ?>" class="ui-text-disable " readonly style="text-align: left;width: 80px;" />
                            </td>
                            <td>&nbsp; </td>
                            <td class="soloSolesa">&nbsp;<input type="text" class="ui-text pnl" id="txtlugar" value="<?php echo $this->lugar; ?>" style="width:96%" /></td>

                        </tr>
                        <tr>
                            <td><br></td>
                        </tr>

                        <tr>
                            <td width="230" style="text-align: left">Nro de Cotizacion:</td>
                            <td width="10">&nbsp;</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" colspan="5" style="text-align: left"></td>
                            <td width="150">&nbsp;</td>
                        </tr>
                        <tr>

                            <td colspan="3">
                                <input class="ui-text-disable pnl" type="hidden" readonly id="idCotizacion" value="<?php echo $this->idCotiz; ?>" style="width:100%" />
                                <input class="ui-text-disable pnl" readonly id="nroCotizacion" value="<?php echo $this->vnroCot; ?>" style="width:100%" />
                            </td>

                            <td colspan="5" style="text-align: left;">
                            </td>
                            <td rowspan="1">
                                <button id="btnbuscarCotizacion" name="btnbuscarCotizacion" onclick="buscarCotizacion()">Buscar Cotizacion</button>
                            </td>
                        </tr>



                        <tr>
                            <td width="230" style="text-align: left">Cliente:</td>
                            <td width="10">&nbsp;</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" colspan="5" style="text-align: left"></td>
                            <td width="150">&nbsp;</td>
                        </tr>
                        <tr class="rowBuscarContribuyente" id="panelBuscarContribuyente">

                            <td colspan="3">
                                <input class="ui-text-disable pnl" type="hidden" readonly id="codigoCliente" value="<?php echo $this->idCliente; ?>" style="width:100%" />
                                <input class="ui-text-disable pnl" readonly id="nombreCliente" value="<?php echo $this->nomCliente; ?>" style="width:100%" />
                            </td>

                            <td colspan="5" style="text-align: left;">
                            </td>
                            <td rowspan="1">
                                <button id="btnbuscarClie" name="btnbuscarClie" onclick="buscarCli()">Buscar Cliente</button>
                            </td>
                        </tr>


                        <tr>
                            <td width="230" style="text-align: left">Tecnico encargado:</td>
                            <td width="10">&nbsp;</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" colspan="5" style="text-align: left"></td>
                            <td width="150">&nbsp;</td>
                        </tr>
                        <tr class="rowBuscarContribuyente" id="panelBuscarContribuyente">

                            <td colspan="3">
                                <input class="ui-text-disable pnl" type="hidden" readonly id="txtidtecnico" value="<?php echo $this->idtecnico; ?>" style="width:100%" />
                                <input class="ui-text-disable pnl" readonly id="txtnombretecnico" value="<?php echo $this->nomtecnico; ?>" style="width:100%" />
                            </td>

                            <td colspan="5" style="text-align: left;">
                            </td>
                            <td rowspan="1">
                                <button id="btnbuscartec" name="btnbuscartec" onclick="buscarTecni()">Buscar Tecnico</button>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>

                    </table>
                </td>
            </tr>
        </table>
    </div>


    <div id="panelDatosConductor" align="center" class="ui-widget ui-widget-content ui-corner-all" style="width: 99%;height: 100%;margin: 3px;">
        <div class="ui-widget ui-state-default ui-corner-top ui-title">
            <label>Materiales </label>
        </div>
        <div style="text-align: left">
            <button id="btnTestigoAgregar">Agregar</button>
        </div>
        <table id="tableTestigos" border="1" class="ui-widget ui-widget-content">
            <thead>
                <tr class="ui-widget-header">
                    <th>Codigo</th>
                    <th>Material</th>
                    <th>Unidad de Medida</th>
                    <th>Stock</th>
                    <th>Buscar</th>
                    <th>Cantidad</th>
                    <!-- <th>Tecnico Responsable</th>
                <th>Buscar Tec</th>-->
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr style="display: none;">
                    <td>
                        <input type="hidden" name="txtidDetSalidaMat" id="txtidDetSalidaMat" />
                        <input id="txtCodigoMaterial" name="txtCodigoMaterial" class="ui-text-disable" disabled="disabled" style="width:90px">
                    </td>
                    <td>
                        <input id="txtNombreMaterial" name="txtNombreMaterial" class="ui-text-disable" disabled="disabled" style="width:350px">
                    </td>

                    <td>
                        <input id="txtUnidadMedida" name="txtUnidadMedida" class="ui-text-disable" disabled="disabled" style="width:100px">
                    </td>
                    <td>
                        <input id="txtStock" name="txtStock" class="ui-text-disable" disabled="disabled" style="width:80px">
                    </td>
                    <td>
                        <button id="btnTestigoBuscarPersona">Buscar</button>
                    </td>
                    <td>
                        <input id="txtCantidad" name="txtCantidad" class="ui-text" style="width:80px">
                    </td>
                    <td>
                        <input type="text" id="fecsalidaMaterial" name="fecsalidaMaterial" class="ui-text-disable " readonly style="text-align: left;width: 80px; " />
                    </td>
                    <!-- <td>
                    <input class="ui-text-disable pnl" type="hidden" readonly name="txtidtecnico"  id="txtidtecnico"  value="<?php echo $this->idtecnico; ?>"  style="width:100px" />
                    <input class="ui-text-disable pnl" readonly name="txtnombretecnico" id="txtnombretecnico"  value="<?php echo $this->nomtecnico; ?>"  style="width:250px" />
                </td>
                <td>
                    <button id="btnBuscarTecnicoa" style="width:105px">Buscar Tecnico</button>
                </td>-->

                    <td>
                        <div title="Eliminar" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit" onmouseover="jQuery(this).addClass('ui-state-hover');" onmouseout="jQuery(this).removeClass('ui-state-hover')" onclick="deleteFilaTable(this);">
                            <span class="ui-icon ui-icon-trash"></span>
                        </div>
                    </td>
                </tr>
                <?php $cont = 0;
                foreach ($this->detSalidaMat as $value) {
                    $cont++ ?>

                    <tr>
                        <td>
                            <input value="<?php echo $value["idDetSalidaMat"]; ?>" type="hidden" name="txtidDetSalidaMat" id="txtidDetSalidaMat" />
                            <input value="<?php echo $value["idMaterial"]; ?>" id="txtCodigoMaterial" name="txtCodigoMaterial" class="ui-text-disable" disabled="disabled" style="width:90px">
                        </td>
                        <td>
                            <input value="<?php echo $value["material"]; ?>" id="txtNombreMaterial" name="txtNombreMaterial" class="ui-text-disable" disabled="disabled" style="width:350px">
                        </td>
                        <td>
                            <input value="<?php echo $value["UnidadMediad"]; ?>" id="txtUnidadMedida" name="txtUnidadMedida" class="ui-text-disable" disabled="disabled" style="width:100px">
                        </td>
                        <td>
                            <input value="<?php echo $value["nStock"]; ?>" id="txtStock" name="txtStock" class="ui-text-disable" disabled="disabled" style="width:80px">
                        </td>
                        <td>
                            <button role="button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-hover" id="btnTestigoBuscarPersona"><span class="ui-button-text">Buscar</span></button>
                        </td>
                        <td>
                            <input value="<?php echo $value["nCantidad"]; ?>" id="txtCantidad" name="txtCantidad" class="ui-text" style="width:80px">
                        </td>
                        <td>
                            <input type="text" id="fecsalidaMaterial<?php echo $cont ?>" name="fecsalidaMaterial" value="<?php echo $value["dFecSalidaMaterial"]; ?>" class="ui-text-disable inputdatepicker" readonly style="text-align: left;width: 80px;" />
                        </td>
                        <!-- <td>
                        <input class="ui-text-disable pnl" type="hidden" name="txtidtecnico"  readonly id="txtidtecnico"  value="<?php echo $this->idtecnico; ?>"  style="width:10px" />
                        <input class="ui-text-disable pnl" readonly name="txtnombretecnico"  id="txtnombretecnico"  value="<?php echo $this->nomtecnico; ?>"  style="width:250px" />
                    </td>
                    <td>
                        <button role="button" style="width:105px" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-hover" id="btnBuscarTecnicoa"><span class="ui-button-text">Buscar Tecnico</span></button>

                    </td>-->

                        <td>
                            <div title="Eliminar" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit" onmouseover="jQuery(this).addClass('ui-state-hover');" onmouseout="jQuery(this).removeClass('ui-state-hover')" onclick="deleteFilaTable(this);">
                                <span class="ui-icon ui-icon-trash"></span>
                            </div>
                        </td>
                    </tr>

                <?php } ?>
            </tbody>
        </table>


    </div>


    <div>
        <table align="left" style="width: 100%">
            <tr>
                <td>
                    <textarea name="txtObs" id="txtObs" rows="3" style="width: 600px; margin-left:3px "><?php echo $this->obs; ?> </textarea>
                </td>
            </tr>
        </table>
    </div>

    <table>

        <tr>
            <td><button id="btncancelardet" name="btncancelardet">Cancelar</button></td>
            <td>
                <button id="btnguardar" name="btnguardar">Guardar</button>
            </td>
        </tr>

    </table>
</div>


<div id="dialogBuscarContribuyentePredio<?php echo $this->id; ?>">
    <table class="ui-panelLayout-main">
        <tr>
            <td style="vertical-align: top;">
                <table style="width: 100%;">
                    <tr>
                        <td>
                            <table>
                                <tr class="rowBuscarContribuyente<?php echo $this->id; ?>">
                                    <td>
                                        <b> Datos Busqueda</b>
                                    </td>
                                </tr>
                                <tr class="rowBuscarContribuyente<?php echo $this->id; ?>">
                                    <td style="text-align: left">
                                        <select id="cbotipob" name="cbotipob" style="width:140px;">
                                            <?php echo $library->ContenidoCombo($TipoBusqueda, $this->ctipmon, 0); ?>
                                        </select>
                                    </td>
                                    <td>Texto de busqueda:</td>
                                    <TD colspan="3">
                                        <input class="ui-text pnl" id="c_textbusqueda" onkeypress="if(event.keyCode==13){buscarMate();}" style="width:100%" />
                                    </TD>
                                    <td> &nbsp;&nbsp;</td>
                                </tr>
                            </table>
                        </td>
                        <td>
                            <button id="btnbuscar<?php echo $this->id; ?>" name="btnbuscar">Buscar</button>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" colspan="2">
                            <br />
                            <div id="panelResult<?php echo $this->id; ?>">
                                <table id="tblResult<?php echo $this->id; ?>"></table>
                                <div id="ptblResult<?php echo $this->id; ?>"></div>
                                <input type="hidden" id="ctblResult" name="ctblResult<?php echo $this->id; ?>" value="" />
                            </div>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>

<!--
<div id="dialogBuscarTecnico<?php echo $this->id; ?>">
    <table class="ui-panelLayout-main">
        <tr><td style="vertical-align: top;">
                <table style="width: 100%;">
                    <tr>
                        <td>
                            <table>
                                <tr class="rowBuscarContribuyente<?php echo $this->id; ?>">
                                    <td>
                                        <b>  Datos Busqueda</b>
                                    </td></tr>
                                <tr class="rowBuscarContribuyente<?php echo $this->id; ?>">
                                    <td style="text-align: left">
                                        <select id="cbotipob" name="cbotipob" style="width:140px;">
                                            <?php echo $library->ContenidoCombo($TipoBusqueda, $this->ctipmon, 0); ?>
                                        </select>
                                    </td>
                                    <td>Texto de busqueda:</td>
                                    <TD colspan="3">
                                        <input class="ui-text pnl" id="c_textbusqueda"  onkeypress="if(event.keyCode==13){buscarMate();}" style="width:100%" />
                                    </TD>
                                    <td> &nbsp;&nbsp;</td>
                                </tr>
                            </table>
                        </td>
                        <td>
                            <button id="btnbuscar<?php echo $this->id; ?>" name="btnbuscar">Buscar</button>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" colspan="2">
                            <br/>
                            <div id="panelResulttec<?php echo $this->id; ?>">
                                <table id="tblResulttec<?php echo $this->id; ?>"></table>
                                <div id="ptblResulttec<?php echo $this->id; ?>"></div>
                                <input type="hidden" id="ctblResulttec" name="ctblResulttec<?php echo $this->id; ?>" value="" />
                            </div>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
-->



<script language="javascript">
    document.onkeydown = function() {
        // a presonar el f5 se actuliza la misma pagina..
        /* if(window.event && window.event.keyCode == 116) {
             window.status="Por favor, Haga Click en Cerrar Sesión Para Salir del Sistema de Auditoría de Servicios";
             if (confirm('¿Estás seguro que deseas salir de la actual página?')) {
                 alert("Pulsada la tecla F5");
             }else{
                 return false;
             }

         }*/

        /*if(window.event && window.event.keyCode == 8){	// cuando el usuario presione el boton retroceso o borrar no regrese atras
          window.status="Por favor, Haga Click en Cerrar Sesión Para Salir del Sistema de Auditoría de Servicios";
            return false;
        }*/
    }
    //Al presionar la fecla de retroceso o de refresh del navegador se muestra un mensaje
    window.onbeforeunload = function() {
        //   return "¿Estás seguro que deseas salir de la actual página?"
    }
</script>


<script type="text/javascript">
    themeComboBox();


    buscarCli = function() {
        parameters = {
            "idsigma": $("#identradamat").val()
        };
        openDialogData1("almacen/buscarcliente", parameters, 660, 500);

    };
    buscarCotizacion = function() {
        parameters = {
            "idsigma": $("#identradamat").val()
        };
        openDialogData1("almacen/buscarcotizacion", parameters, 660, 500);

    };

    $("#cbtitulo").combobox({
        selected: function(event, ui) {
            var select = document.getElementById('cbtitulo');
            var selectedOption = this.options[select.selectedIndex];
            console.log(selectedOption.value + ': ' + selectedOption.text);
            $("#c_motivohd").val(selectedOption.text);
            if ($("#cbtitulo").val() == '9') {
                $(".titulotext").show();
                $("#c_motivo").val("");

            } else {
                $(".titulotext").hide();
            }
        }
    });
    $("#cbreferencial").combobox({
        selected: function(event, ui) {
            var select = document.getElementById('cbreferencial');
            var selectedOption = this.options[select.selectedIndex];
            console.log(selectedOption.value + ': ' + selectedOption.text);
            $("#referncialhd").val(selectedOption.text);
            if ($("#cbreferencial").val() == '9') {
                $(".referencialtext").show();
            } else {
                $(".referencialtext").hide();
            }
        }
    });

    $("#cbformapago").combobox({
        selected: function(event, ui) {
            var select = document.getElementById('cbformapago');
            var selectedOption = this.options[select.selectedIndex];
            console.log(selectedOption.value + ': ' + selectedOption.text);
            $("#formapagohd").val(selectedOption.text);
            if ($("#cbformapago").val() == '9') {
                $(".formapagotext").show();
            } else {
                $(".formapagotext").hide();
            }
        }
    });




    function imprimir() {
        var selr = $('#tblDetEntradaMat').jqGrid('getGridParam', 'selrow');
        var row = $("#tblDetEntradaMat").jqGrid('getRowData', selr);

        host = '<?php echo $this->util()->getPath(); ?>report/';
        window.open(host + "rptCotizacion.php?idCotiz=" + $("#identradamat").val(), '_blank');
        //console.log(host);

    }



    //Funcion para regresar al la grilla naterior
    function Cancelar() {
        parameters = {
            "idSalidamat": $("#idsalidamat").val()
        }
        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/cancelareliminadossalidamat",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function(data) {},
            success: function(requestData) {
                window.open(path + "almacen/salidamat", "_self");
            },
            error: function(requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function(requestData, exito) {}
        });


    }



    var invocaBusPersona = 0;


    cargarCategoria = function() {
        $("#txtLicenciaCategoria").val('');
        contenidocomboContenedor('#cboLicenciaCategoria', $("#cboLicenciaClase").val())

    }

    buscarMaterialSalida = function(d) {
        console.log(d);
        __gridConfigMaterial.data = [];
        __gridConfigMaterial.ondblClickRow = function(rowid) {
            row = $("#tblResult").jqGrid('getRowData', rowid);
            if (invocaBusPersona == 1) {
                if (row.nStock <= row.nStockMinimo) {
                    openDialogWarning("Comprar Material. Stock menor al Stock Minimo.");
                }
                $(d).parent().parent().find("input[name=txtCodigoMaterial]").val(row.idMaterial);
                $(d).parent().parent().find("input[name=txtNombreMaterial]").val(row.vNombre);
                $(d).parent().parent().find("input[name=txtUnidadMedida]").val(row.vUnidadMed);
                $(d).parent().parent().find("input[name=txtStock]").val(row.nStock);
                // $(d).parent().parent().find("input[name=txtCantidad]").val(1);
            }
            closeDialog("dialogBuscarContribuyentePredio");

        };
        BuscadorMaterial.bindkeysPersona = {
            "onEnter": __gridConfigMaterial.ondblClickRow
        };
        BuscadorMaterial.buscar();
        $("#tblResult").jqGrid("clearGridData");
        if ($(".rowBuscarContribuyente").hasClass("row-hide")) {
            $(".rowBuscarContribuyente").removeClass("row-hide");
        }
        //$(".rowBuscarPredio").css({display: "none"});
        $("#dialogBuscarContribuyentePredio").dialog("open");
        $("#c_codigocontrib").focus();
    }

    /*buscarTecnico = function (d) {
        console.log(d);

        __gridConfigTecnico.data = [];
        __gridConfigTecnico.ondblClickRow = function (rowid) {
            row = $("#tblResulttec").jqGrid('getRowData', rowid);
            if (invocaBusPersona == 1) {
                $(d).parent().parent().find("input[name=txtidtecnico]").val(row.idTecnico);
                $(d).parent().parent().find("input[name=txtnombretecnico]").val(row.vNombre);
                $(d).parent().parent().find("input[name=txtnombretecnico]").val("dfdf");
                console.log(row.vNombre);
            }
            closeDialog("dialogBuscarTecnico");

        };
        BuscadorTecnico.bindkeysPersona = {"onEnter": __gridConfigTecnico.ondblClickRow};
        BuscadorTecnico.buscar();
        $("#tblResulttec").jqGrid("clearGridData");
        if ($(".rowBuscarContribuyente").hasClass("row-hide")) {
            $(".rowBuscarContribuyente").removeClass("row-hide");
        }
        //$(".rowBuscarPredio").css({display: "none"});
        $("#dialogBuscarTecnico").dialog("open");
        $("#c_codigocontrib").focus();
    }*/


    var i = 1;

    deleteFilaTable = function(d) {
        var idmaterial = $(d).parent().parent().find("input[name=txtCodigoMaterial]").val();
        var iddetsalidamat = $(d).parent().parent().find("input[name=txtidDetSalidaMat]").val();

        if (iddetsalidamat == "" || iddetsalidamat == undefined) {
            $(d).parent().parent().remove();
            return;
        }

        parameters = {
            "id": idmaterial,
            "idDetsalida": iddetsalidamat
        };
        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/eliminarmaterialsalidamat",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function(data) {},
            success: function(requestData) {
                $("#result").html(requestData);
                var datos = JSON.parse(requestData);
                console.log(datos[0][1]);
                console.log(datos[0][0]);
                if (datos[0][0] == "ok") {
                    $(d).parent().parent().remove();
                } else {
                    openDialogInfo(datos[0][1], "280", "150", null, function() {
                        return;
                    });
                }

            },
            error: function(requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function(requestData, exito) {}
        });

    }

    buscarTecni = function() {
        parameters = {
            "idsigma": $("#identradamat").val()
        };
        openDialogData1("almacen/buscartecnico", parameters, 660, 500);
        //   window.open(path + "mantenimientos/backup", "_self");

    };


    agregarFilaTable = function(id) {
        var id_combobox = "";

        $("#" + id + " tbody tr:first").clone().show().find("input,select,button").each(function() {
            if ($(this).is("select")) {
                id_combobox = this.id + '_' + id + "_" + i;
            }
            $(this).attr({
                'id': this.id + '_' + id + "_" + i,
                'value': ''
            });
        }).end().appendTo("#" + id);

        themeComboBox("#" + id_combobox);
        $("#btnTestigoBuscarPersona_" + id + "_" + i).button().click(function() {
            invocaBusPersona = 1;
            buscarMaterialSalida(this);

        });
        /*  $("#btnBuscarTecnicoa_" + id + "_" + i).button().click(function () {
              invocaBusPersona = 1;
              buscarTecnico(this);

          });*/

        $("#fecsalidaMaterial_" + id + "_" + i).datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });
        $("#fecsalidaMaterial_" + id + "_" + i).datepicker("setDate", new Date());

        i++;

        for (index = 1; index < 20; index++) {
            $("#fecsalidaMaterial" + index).datepicker({
                showOn: "button",
                buttonImage: pathImage + "calendar.gif",
                buttonImageOnly: true,
                dateFormat: "dd/mm/yy"
            });
        }



    }

    $(function() {
        $("#fecsalida").datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });
        $("#fechasta").datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });




        $("#btnbuscartec").button({
            icons: {
                primary: "ui-icon-search"
            }
        });
        $("#btnbuscarClie").button({
            icons: {
                primary: "ui-icon-search"
            }
        });
        $("#btnbuscarCotizacion").button({
            icons: {
                primary: "ui-icon-search"
            }
        });
        $("#btnguardar").button({
            icons: {
                primary: "ui-icon-disk"
            }
        }).click(function() {
            Guardar();
        });
        $("#btncancelardet").button({
            icons: {
                primary: "ui-icon-cancel"
            }
        }).click(function() {
            Cancelar('');
        });

        // clone inspector

        $("#btnTestigoBuscarPersona").button("destroy");
        $("#btnBuscarTecnicoa").button("destroy");
        agregarFilaTable("tableTestigos");
        $("#btnTestigoAgregar").click(function() {
            agregarFilaTable("tableTestigos");
        });
        $("#btnTestigoAgregar").button({
            icons: {
                primary: "ui-icon-plus"
            }
        });
        //fin clone inspector

        //--- Buscar persona
        Persona.init(true);
        BuscadorMaterial.init(BuscadorMaterial.MODO_FULL, true);
        BuscadorMaterial.configurarDialog();
        //BuscadorTecnico.init(BuscadorTecnico.MODO_FULL, true);
        /// BuscadorTecnico.configurarDialog();

        //---- fin buscar persona


        /*  dialogPersona = $("#dialogBuscarPersona").dialog({
        autoOpen: false,
        height: 100,
        width: 100,
        modal: true,
        buttons: {
//                "Aceptar": function () {
//
//                },
            Cerrar: function () {
                //invocaBusPersona = 0;
                dialogPersona.dialog("close");
            }
        },
        close: function () {
            invocaBusPersona = 0;
            //dialogPersona.dialog("close");
        }
    });*/



        function Guardar() {

            var detallesalida = {};
            var materiales = [];

            //Datos generales del salida de Materiales
            detallesalida.idSalidaMat = $("#idsalidamat").val();
            detallesalida.obra = $("#txtobra").val();
            detallesalida.lugar = $("#txtlugar").val();
            detallesalida.fecha = $("#fecsalida").val();
            detallesalida.idtecnico = $("#txtidtecnico").val();
            detallesalida.idcliente = $("#codigoCliente").val();
            detallesalida.idcotizacion = $("#idCotizacion").val();
            detallesalida.obs = $("#txtObs").val();
            /* if($("#txtidtecnico").val()==""){
                 openDialogWarning("Seleccione un tecnico encargado.");
                 return;
             }*/
            if ($("#fecsalida").val() == "") {
                openDialogWarning("Seleccione la fecha.");
                return;
            }
            //Datos materiales
            $('#tableTestigos > tbody  > tr').each(function() {
                var detMateriales = {};
                if ($(this).find("[name=txtCodigoMaterial]").val() != '') {
                    detMateriales.idDetSalidaMat = $(this).find("[name=txtidDetSalidaMat]").val();
                    detMateriales.idMaterial = $(this).find("[name=txtCodigoMaterial]").val();
                    detMateriales.Cantidad = $(this).find("[name=txtCantidad]").val();
                    detMateriales.stock = $(this).find("[name=txtStock]").val();
                    detMateriales.fecsalidaMaterial = $(this).find("[name=fecsalidaMaterial]").val();
                    materiales.push(detMateriales);
                }
            });
            detallesalida.materiales = materiales;

            var pSalidaMat = {};
            pSalidaMat.objSalidaMat = JSON.stringify(detallesalida);
            //console.log(JSON.stringify(pPapeleta));
            //console.log(papeleta);


            $.post(path + "almacen/guardarsalidamat", pSalidaMat, function(data) {
                console.log(data);
                console.log(data["idSalidaMat"]);
                if (data["a"] == '0') {
                    openDialogInfo(data["b"], "280", "150", null, function() {
                        return;
                    });
                } else {
                    // $("#iframeUploadDocPapeleta").attr("src", path + "papeleta/uploadarchivo?mpapeleta=" + data.idsigma);
                    //  dialogUpload.dialog("open");
                    window.open(path + "almacen/salidamat", "_self");
                }

            }, 'json');


        };
    })
</script>