<?php
$library = new Libreria_Pintar();
$TipoBusqueda=array(array("0","GENERAL"), array("1","ID"), array("2","NOMBRE"), array("3","TIPOMATERIAL"), array("4","MARCA"));
?>
<div id="paneldPSM" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 100%;margin: 1px; height:95%;">
    <div class="ui-widget ui-state-rombo ui-corner-top ui-title">
        <label>Agregar Series</label>
    </div>

    <input type="hidden" class="ui-text"  id="txtiddetEntradaProd" value="<?php echo $this->iddetentradaprod; ?>" style="width:99%" />
    <input type="hidden" class="ui-text"  id="txtidProducto" value="<?php echo $this->idproducto; ?>" style="width:99%" />
    <input type="hidden" class="ui-text"  id="txtCantidad"  style="width:99%" value="<?php echo $this->cantidad; ?>" />
    <br>
    <!--<input type="text" class="ui-text-disable" readonly id="txtnombreprod" value="<?php echo $this->nombreprod; ?>" style="width:99%; display: none;" />-->
    <h1>PRODUCTO:</h1>
    <div class="ui-text-disable"><h1><?php echo $this->nombreprod; ?></h1></div>
  <br>
    <div class="ui-state-diag-negro" style="margin: 0 0.3em; line-height: 2em; text-align: center;">Cantidad Ingresada <?php echo $this->cantidad; ?> <span id="mensaje" style="margin: 0 2.3em; line-height: 2em; text-align: center; font-weight: normal; color: #fffc0c; "></span></div>
    <div id="dialogMensaje">
    </div>
    <div id="panelPrSerie" align="left" style="width: 99%;margin-left: 5px;">
        <table id="tblPrSerie"></table>
        <div id="ptblPrSerie">
        </div>
    </div>
    <br/>
<!--
    <div class="ui-widget ui-state-default ui-corner-all ui-title">
        <label>Agregar Material</label>
    </div>-->

      <button id="btnCancelarSe" name="btnCancelarSe">Cancelar</button>
      <button id="btnGuardarSerie" name="btnGuardarSerie">Guardar</button>
    </div>

<script type="text/javascript">
    themeComboBox();
    var mydata = [];
    var cant=0;

    $( "#txtnombre" ).keyup(function( event ) {
        buscarPServ();
        document.getElementById("txtnombre").focus();
    }).keydown(function( event ) {
        if ( event.which == 13 ) {

        }
    });
    $( "#txtdescri" ).keyup(function( event ) {
        buscarMate();
        document.getElementById("txtdescri").focus();
    }).keydown(function( event ) {
        if ( event.which == 13 ) {

        }
    });

    $('#txtPrecioUnit').on('keypress', function (e) {
        // Backspace = 8, Enter = 13, ’0? = 48, ’9? = 57, ‘.’ = 46

        var field = $(this);
        key = e.keyCode ? e.keyCode : e.which;

        if (key == 8) return true;
        if (key > 47 && key < 58) {
            if (field.val() === "") return true;
            var existePto = (/[.]/).test(field.val());
            if (existePto === false){
                regexp = /.[0-9]{10}$/;
            }
            else {
                regexp = /.[0-9]{2}$/;
            }

            return !(regexp.test(field.val()));
        }
        if (key == 46) {
            if (field.val() === "") return false;
            regexp = /^[0-9]+$/;
            return regexp.test(field.val());
        }
        return false;
    });
    $('#txtCantidad').on('keypress', function (e) {
        // Backspace = 8, Enter = 13, ’0? = 48, ’9? = 57, ‘.’ = 46

        var field = $(this);
        key = e.keyCode ? e.keyCode : e.which;

        if (key == 8) return true;
        if (key > 47 && key < 58) {
            if (field.val() === "") return true;
            var existePto = (/[.]/).test(field.val());
            if (existePto === false){
                regexp = /.[0-9]{10}$/;
            }
            else {
                regexp = /.[0-9]{2}$/;
            }

            return !(regexp.test(field.val()));
        }
        return false;
    });

   /* $("#cbo_bus").combobox({
        selected: function(event, ui){
           if($("#cbo_bus").val()=='1'){
               $(".clprod").show();
               $(".clserv").hide();

           }else{
               $(".clprod").hide();
               $(".clserv").show();

           }
        }
    });*/

    var lastselSerie;
    optionPSM = {
        datatype: "local",
        width: 530,
       // keys: true,
        height: 250,
        colNames: [
            'Codigo',
            'Serie',
            'EstadoAlmacen',
            'Estado',
            ''
        ],
        colModel: [
            {name: 'idProdSeries', index:'idProdSeries', width:60,search:false},
            {name: 'vNroSerie', index:'vNroSerie', width:250, editable:true,editoptions: {maxlength: 100}},
            {name: 'vEstAlmacen', index:'vEstAlmacen', width:50, hidden: true, editOptions:{value:"1:0",defaultvalue:"1"},formatter:'checkbox'},
            {name: 'vEstado', index:'vEstado', width:50, hidden: true, editOptions:{value:"1:0",defaultvalue:"1"},formatter:'checkbox'},
            {name: 'btndel', index: 'btndel', width: 40, align: 'center' ,formatter : btnEliminaSerie,search:false}
        ],
        editurl: "clientArray",
        caption: "&nbsp;&nbsp;&nbsp;Series",
        ondblClickRow: function(id){
            var row = $(this).getRowData(id);

        },

        afterInsertRow:function(rowid,aData){
            switch(
                aData.nestado
                ){case'1':
                break;
                case '0':

                    jQuery("#tblPrSerie").jqGrid('setCell',rowid,'idProdSeries','',{color:'red'});
                    jQuery("#tblPrSerie").jqGrid('setCell',rowid,'vNroSerie','',{color:'red'});
                    jQuery("#tblPrSerie").jqGrid('setCell',rowid,'vEstAlmacen','',{color:'red'});
                    jQuery("#tblPrSerie").jqGrid('setCell',rowid,'vEstado','',{color:'red'});
                    break;
            }
        },
        onSelectRow: function(id) {
            var row = $(this).getRowData(id);
           // if(lastselSerie!=undefined)

                if(id && id!==lastselSerie){
                    jQuery('#tblPrSerie').jqGrid('saveRow',lastselSerie);
                    lastselSerie=id;
                }
            jQuery('#tblPrSerie').jqGrid('editRow',id,true);
        }
    };


    // -----> Borrar============================================00
    function btnEliminaSerie(cellvalue, options, rowObject){

        return '<div align="center" class="ui-pg-button " ' +
            'title="Borrar" style="text-align:center;float: left; cursor: pointer; display: block;" ' +
            'onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
            'onclick="eliminarseriep(\''+options.rowId+'\');"><div class="ui-pg-div  ui-inline-edit" >' +
            '<span class="ui-icon ui-icon-trash"></span></div></div>';
    }
    function eliminarseriep(rowId) {
       var gr = jQuery("#tblPrSerie").jqGrid('getGridParam','selrow');
        //jQuery("#tblPrSerie").jqGrid('delGrid');
        $('#tblPrSerie').jqGrid('GridUnload');
        console.log(mydata);
        //mydata.splice(rowId-1,rowId); //Eliminado registro  splice(indexinicio,indexfin,[,campos que se agregan al aregllo])

        delete  mydata[rowId-1];


        actualizarGrid("tblPrSerie",optionPSM,null,buttonsGridPSM);
        for(var i=0;i<=mydata.length;i++){
            jQuery("#tblPrSerie").jqGrid('addRowData',i+1,mydata[i]);
        }
        var rows= jQuery("#tblPrSerie").jqGrid('getRowData');
        if(cant>=rows.length){
            jQuery("#tblPrSerie").jqGrid('hideCol',"btndel");
            $("#mensaje").html("");
        }else{
            $("#mensaje").html(" Debe Eliminar "+(rows.length-cant)+ " SERIES de la grilla");
        }
    }

    guardarSeries=function(a){
       // var selr = $('#tblPrSerie').jqGrid('getGridParam','selrow');
       // var row = $("#tblPrSerie").jqGrid('getRowData', selr);
        jQuery('#tblPrSerie').jqGrid('saveRow',lastselSerie);
        var rows= jQuery("#tblPrSerie").jqGrid('getRowData');

        var detSeries = {};
        var Series = [];
        //Datos generales
        detSeries.idproducto = $("#txtidProducto").val();
        detSeries.identradaProd = $("#txtiddetEntradaProd").val();

        //Datos Series
        if (rows.length > 0) {
            for (var i=0;i<rows.length;i++) {
                var aSerie = {};
                var row=rows[i];
                aSerie.idProdSeries= row.idProdSeries;
                aSerie.vNroSerie= row.vNroSerie;
                Series.push(aSerie);
            }
        }
        detSeries.lstSeries=Series;
        var parameters = {};
        parameters.objSeries = JSON.stringify(detSeries);

        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/guardarseries",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function (data) {   },
            success: function (requestData) {
                closeDialog('jqDialog1');
            },
            error: function (requestData, strError, strTipoError) {   },
            complete: function (requestData, exito) {    }
        });

    };


    function buttonsGridPSM(){
        $("#tblPrSerie").navGrid('#ptblPrSerie', {edit:false,add:false,del:false,search:false,refresh:false})

          /*  .navButtonAdd('#ptblPrSerie',{
                caption:"Agregar&nbsp;&nbsp;",
                buttonicon:"ui-icon-plus",
                onClickButton: function(){
                    nuevaMaterial();
                },
                position:"last"
            })
         .navButtonAdd('#ptblPrSerie',{
                caption:"Editar&nbsp;&nbsp;",
                buttonicon:"ui-icon-pencil",
                onClickButton: function(){
                    verMaterial();
                },
                position:"last"
            })
        ;*/
       //$("#tblPrSerie").jqGrid('filterToolbar', {stringResult: true, searchOnEnter: false, defaultSearch: 'cn', ignoreCase: true});
    }


    buscarMatePrimeravez = function() {
        var tbus="4";
        cant =<?php echo $this->cantidad;?>;

        var params = '['
            + '["@tBusqueda", "' + tbus + '"],'
            + '["@vDatoBus", "' + $("#txtidProducto").val() + '"]'
            + '["@vIddetEntradaProd", "' + $("#txtiddetEntradaProd").val() + '"]'
            + ']';
        parameters = {
            "tBusqueda": tbus,
            "vDatoBus":  $("#txtidProducto").val(),
            "vIddetEntradaProd":  $("#txtiddetEntradaProd").val()
        };

        $.ajax({
            url: jQuery.scriptPath + "index.php/almacen/listarseries",
            type: 'POST',
            cache: false,
            data: parameters,
            beforeSend: function (data) {
            },
            success: function (requestData) {
                $("#result").html(requestData);
                var datos=JSON.parse(requestData);
                //console.log(datos[0].idProdSeries);
                for(var i=0;i<datos.length;i++){
                    mydata.push({idProdSeries:datos[i].idProdSeries,vNroSerie:datos[i].vNroSerie,vEstAlmacen:datos[i].vEstAlmacen,vEstado:datos[i].vEstado});
                }
                var dif=cant-datos.length;
                if(dif>0){
                    for (var i=0;i<dif;i++){
                        mydata.push({idProdSeries:"",vNroSerie:"",vEstAlmacen:"",vEstado:""});
                    }
                }
               // console.log(cant);
               // console.log(mydata);

                inicializarGrid("tblPrSerie",optionPSM,null,buttonsGridPSM);
                for(var i=0;i<=mydata.length;i++){
                    jQuery("#tblPrSerie").jqGrid('addRowData',i+1,mydata[i]);
                }
                if(dif>=0){
                    jQuery("#tblPrSerie").jqGrid('hideCol',"btndel");
                }else{
                    $("#mensaje").html(" Debe Eliminar "+(datos.length-cant)+ " SERIES de la grilla");
                }

            },
            error: function (requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function (requestData, exito) {
            }
        });

    };
    //Funcion para regresar al la grilla naterior
    function Cancelar(){
        closeDialog('jqDialog1');
    }
    $(function(){
        buscarMatePrimeravez();
         $("#btnCancelarSe").button(ICON_CANCEL).click(function () {
             Cancelar('');
         });
         $("#btnGuardarSerie").button(ICON_SAVE).click(function(){
             guardarSeries();
         });
       /*reiniCombo("cbocsubcateg");
       getSubcategoria($("#cbocategor").val(),"cbocsubcateg");*/


    });
</script>