<?php
$library = new Libreria_Pintar();
$TipoBusqueda = array(array("0", "GENERAL"), array("1", "NOMBRE ACTIVO"), array("3", "NRO COTIZACION"), array("4", "CLIENTE"), array("5", "SERIE"));

?>

<div id="panelSalidaActivos" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 99%;margin: 1px; height:95%;">
    <div class="ui-widget ui-state-rojo ui-corner-top ui-title">
        <label>SALIDA DE ACTIVOS</label>
    </div>
    <div id="dialogBuscarSalidaMaterial">
        <table class="ui-panelLayout-main">
            <tr>
                <td style="vertical-align: top;">
                    <table border="0" style="margin-left:15px;">

                        <tr>
                            <td>
                                <b> Datos Busqueda</b>
                            </td>
                        </tr>

                        <tr class="rowdatospsm" id="rowdatospsm">
                            <td style="text-align: left">
                                <select id="cbotipob" name="cbotipob" style="width:140px;">
                                    <?php echo $library->ContenidoCombo($TipoBusqueda, $this->ctipmon, 0); ?>
                                </select>
                            </td>
                            <td></td>
                            <TD colspan="8">
                                Texto de busqueda: <input class="ui-text pnl" id="c_textbusqueda" onkeypress="if(event.keyCode==13){buscarSalidaActivos();}" style="width:100%" />
                            </TD>
                            <td> &nbsp;&nbsp;</td>
                            <td rowspan="3">
                                <button id="btnbuscar" name="btnbuscar" onclick="buscarSalidaActivos()">Buscar</button>
                            </td>
                        </tr>
                        <tr class="rowcoti">

                            <td width="100" style="text-align: left">Fecha Desde:</td>
                            <td width="30">&nbsp;</td>
                            <td width="200" style="text-align: left">Fecha Hasta:</td>
                            <td width="10">&nbsp;</td>
                            <td width="10">&nbsp;</td>

                        </tr>
                        <tr class="rowbcoti" id="panelbcoti">

                            <td>
                                <input type="text" id="fecdesde" class="ui-text" value="<?php echo $this->fechaini; ?>" style="text-align: left;width: 80px;" />
                            </td>
                            <td>&nbsp;</td>
                            <td colspan="2">
                                <input type="text" id="fechasta" class="ui-text" value="<?php echo $this->fechafin; ?>" style="text-align: left;width: 100px;" />
                            </td>
                            <td>&nbsp;</td>


                        </tr>
                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>

                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>
                    </table>
                </td>
            </tr>

        </table>
    </div>
    <div id="dialogMensaje">
    </div>
    <div id="panelListaSalidaActivos" align="left" style="width: 100%;margin-left: 15px; margin-right: 15px;">
        <table id="tblListaSalidaActivos"></table>
        <div id="ptblListaSalidaActivos"></div>
    </div>
    <br />
</div>
<script type="text/javascript">
    $("#cbotipob").combobox({
        selected: function(event, ui) {
            buscarSalidaActivos();
        }
    });


    optionSalidaMat = {
        width: 1200,
        height: 250,
        colNames: [
            'idSalidaActivos',
            'FecSalida',
            'FecRetorno',
            'vObra',
            'vLugar',
            'Cliente',
            'Nro Cotizacion',
            'idTecnico',
            'vTecnico',
            "vEstado",
            "Borrar",
            "Nuevo",
            "Imprimir",
            "Retorno"
        ],
        colModel: [{
                name: 'idSalidaActivo',
                index: 'idSalidaActivo',
                width: 90
            },
            {
                name: 'dFecSalida',
                index: 'dFecSalida',
                width: 80
            },
            {
                name: 'dFecRetorno',
                index: 'dFecRetorno',
                width: 80,
                hidden: false
            },
            {
                name: 'vObra',
                index: 'vObra',
                width: 180
            },
            {
                name: 'vLugar',
                index: 'vLugar',
                width: 180,
                hidden: false
            },
            {
                name: 'cliente',
                index: 'cliente',
                width: 180,
                hidden: false
            },
            {
                name: 'vnroCot',
                index: 'vnroCot',
                width: 90,
                hidden: false
            },

            {
                name: 'idTecnico',
                index: 'idTecnico',
                width: 80,
                hidden: true
            },
            {
                name: 'vTecnico',
                index: 'vTecnico',
                width: 160
            },
            {
                name: 'vEstado',
                index: 'vEstado',
                width: 60,
                hidden: false,
                editOptions: {
                    value: "1:0",
                    defaultvalue: "1"
                },
                formatter: 'checkbox'
            },
            {
                name: 'btndocumall',
                index: 'btndocumall',
                width: 50,
                align: 'center',
                formatter: btndocumtall,
                search: false,
                hidden: false
            },
            {
                name: 'btndocumall',
                index: 'btndocumall',
                width: 40,
                align: 'center',
                formatter: btnNuevo,
                search: false,
                hidden: true
            },
            {
                name: 'btndocumall',
                index: 'btndocumall',
                width: 40,
                align: 'center',
                formatter: btnImprimir,
                search: false,
                hidden: true
            },
            {
                name: 'btndocudevo',
                index: 'btndocudevo',
                width: 60,
                align: 'center',
                formatter: btnRetorno,
                search: false,
                hidden: false
            }
        ],
        caption: "&nbsp;&nbsp;&nbsp;Salida de Activos",
        ondblClickRow: function(id) {
            var row = $(this).getRowData(id);
            verSalidaMat();
        },
        afterInsertRow: function(rowid, aData) {
            switch (aData.nestado) {
                case '1':
                    break;
                case '0':

                    jQuery("#tblListaSalidaActivos").jqGrid('setCell', rowid, 'cidpers', '', {
                        color: 'red'
                    });
                    jQuery("#tblListaSalidaActivos").jqGrid('setCell', rowid, 'crazsoc', '', {
                        color: 'red'
                    });
                    jQuery("#tblListaSalidaActivos").jqGrid('setCell', rowid, 'vnrodoc', '', {
                        color: 'red'
                    });
                    jQuery("#tblListaSalidaActivos").jqGrid('setCell', rowid, 'nestado', '', {
                        color: 'red'
                    });
                    break;
            }
        },
        onSelectRow: function(id) {
            var row = $(this).getRowData(id);
        }
    };


    // -----> Borrar============================================00
    function btndocumtall(cellvalue, options, rowObject) {

        return '<div align="center" class="ui-pg-button " title="Borrar" style="text-align:center;float: left; ' +
            'cursor: pointer; display: block;" onmouseover="jQuery(this).addClass(\'ui-state-hover\');" ' +
            'onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
            'onclick="accionborrarsalida(\'' + options.rowId + '\');"><div class="ui-pg-div  ui-inline-edit" >' +
            '<span class="ui-icon ui-icon-trash"></span></div></div>';
    }

    function accionborrarsalida(rowId) {
        var rowdat = jQuery("#tblListaSalidaActivos").jqGrid('getRowData', rowId);

        var paramtrs = {
            idSalidaActivo: rowdat.idSalidaActivo
        }
        openDialogConfirm1("Seguro que desea eliminar el registro?", 350, {
            "Si": function() {
                $.ajax({
                    url: jQuery.scriptPath + "index.php/almacen/eliminarsalidaactivos",
                    type: 'POST',
                    cache: false,
                    data: paramtrs,
                    beforeSend: function(data) {},
                    success: function(requestData) {
                        var datos = JSON.parse(requestData);
                        console.log(datos);
                        // var parameters = {
                        //     idcotizacion: datos[0].idSalidaActivo
                        // };
                        buscarSalidaActivos();
                        closeDialog("jqDialogConfirmacion1");
                    },
                    error: function(requestData, strError, strTipoError) {
                        $("#result").html("Error " + strTipoError + ': ' + strError);
                    },
                    complete: function(requestData, exito) {}
                });
            },
            "No": function() {
                closeDialog("jqDialogConfirmacion1");

            }
        });


    }
    // -----> Nuevo ====================================================
    function btnNuevo(cellvalue, options, rowObject) {

        return '<div align="center" class="ui-pg-button " title="Nuevo a partir de esta cotizacion" style="text-align:center;float: left; cursor: pointer; display: block;" onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" onclick="accionbtnNuevo(\'' + options.rowId + '\');"><div class="ui-pg-div  ui-inline-edit" ><span class="ui-icon ui-icon-document"></span></div></div>';
    }

    function accionbtnNuevo(rowId) {
        var rowdat = jQuery("#tblListaSalidaActivos").jqGrid('getRowData', rowId);
        var paramtrs = {
            idCotiz: rowdat.idCotiz
        }
        console.log(paramtrs);
        $.ajax({
            url: jQuery.scriptPath + "index.php/cotizacion/copiarcotiz",
            type: 'POST',
            cache: false,
            data: paramtrs,
            beforeSend: function(data) {

            },
            success: function(requestData) {
                var datos = JSON.parse(requestData);
                console.log(datos);
                var parameters = {
                    idcotizacion: datos[0].idcotiz
                }
                var _post = $.post(path + "cotizacion/detcotizacion", parameters);
                _post.success(function(request) {
                    $("#panelSalidaActivos").html(request);
                });
            },
            error: function(requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function(requestData, exito) {}
        });



    }


    // -----> Retorno ====================================================
    function btnRetorno(cellvalue, options, rowObject) {

        return '<div align="center" class="ui-pg-button " title="Imprimir cotizacion" style="text-align:center;' +
            'float: left; cursor: pointer; display: block;" onmouseover="jQuery(this).addClass(\'ui-state-hover\');" ' +
            'onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" onclick="accionbtnRetorno(\'' + options.rowId + '\');">' +
            '<div class="ui-pg-div  ui-inline-edit" ><span class="ui-icon ui-icon-arrowreturnthick-1-w"></span></div></div>';
    }

    function accionbtnRetorno(rowId) {
        var row = $("#tblListaSalidaActivos").jqGrid('getRowData', rowId);
        if (row.idSalidaActivo == "" || row.idSalidaActivo == undefined) {
            openDialogWarning("Seleccione un Registro");
            return;
        }
        parameters = {
            "idSalidaActivo": row.idSalidaActivo
        };

        var _post = $.post(path + "almacen/detretornoactivos", parameters);
        _post.success(function(request) {
            $("#panelSalidaActivos").html(request);
        });
    }

    // -----> Imprimir PDF ====================================================
    function btnImprimir(cellvalue, options, rowObject) {

        return '<div align="center" class="ui-pg-button " title="Imprimir cotizacion" style="text-align:center;' +
            'float: left; cursor: pointer; display: block;" onmouseover="jQuery(this).addClass(\'ui-state-hover\');" ' +
            'onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" onclick="accionbtnImprimir(\'' + options.rowId + '\');">' +
            '<div class="ui-pg-div  ui-inline-edit" ><span class="ui-icon ui-icon-print"></span></div></div>';
    }

    function accionbtnImprimir(rowId) {
        var rowdat = jQuery("#tblListaSalidaActivos").jqGrid('getRowData', rowId);
        var paramtrs = {
            idSalidaActivo: rowdat.idSalidaActivo
        }
        host = '<?php echo $this->util()->getPath(); ?>report/';
        window.open(host + "rptSalidaMat.php?idSalida=" + rowdat.idSalidaActivo, '_blank');
    }






    nuevaSalidaMat = function() {
        parameters = {
            "idsigma": '0000000000'
        };
        window.open(path + "almacen/detsalidaactivos", "_self");
    };
    verSalidaMat = function() {
        var selr = $('#tblListaSalidaActivos').jqGrid('getGridParam', 'selrow');
        var row = $("#tblListaSalidaActivos").jqGrid('getRowData', selr);
        if (row.idSalidaActivo == "" || row.idSalidaActivo == undefined) {
            openDialogWarning("Seleccione un registro para editar.");
            return;
        }
        parameters = {
            "idSalidaActivo": row.idSalidaActivo
        };

        var _post = $.post(path + "almacen/detsalidaactivos", parameters);
        _post.success(function(request) {
            $("#panelSalidaActivos").html(request);
        });


    };


    function buttonsGridPerson() {
        $("#tblListaSalidaActivos")
            .navGrid('#ptblListaSalidaActivos', {
                edit: false,
                add: false,
                del: false,
                search: false,
                refresh: false
            })

            .navButtonAdd('#ptblListaSalidaActivos', {
                caption: "Crear&nbsp;&nbsp;",
                buttonicon: "ui-icon-plus",
                onClickButton: function() {
                    nuevaSalidaMat();
                },
                position: "last"
            })
            .navSeparatorAdd()
        /*
                    .navButtonAdd('#ptblListaSalidaActivos', {
                        caption: "Imprimir&nbsp;&nbsp;",
                        buttonicon: "ui-icon-pencil",
                        onClickButton: function() {
                            imprimir();
                        },
                        position: "last"
                    })
                    .navSeparatorAdd();*/
    }


    function imprimir() {
        var selr = $('#tblListaSalidaActivos').jqGrid('getGridParam', 'selrow');
        var row = $("#tblListaSalidaActivos").jqGrid('getRowData', selr);

        if (row.idSalidaActivo == "" || row.idSalidaActivo == undefined) {
            openDialogWarning("Seleccione Salida.");
            return;
        }
        host = '<?php echo $this->util()->getPath(); ?>report/';
        window.open(host + "rptCotizacion.php?idCotiz=" + row.idSalidaActivo, '_blank');
    }



    buscarSalidaActivos = function() {

        var tipob = $("#cbotipob").val();

        var params = '[' +
            '["@tBusqueda", "' + tipob + '"],' +
            '["@vDatoBus", "' + $("#c_textbusqueda").val() + '"],' +
            '["@vFecIni", "' + $("#fecdesde").val() + '"],' +
            '["@vFecFin", "' + $("#fechasta").val() + '"]' +
            ']';
        parameters = {
            "name": "tblListaSalidaActivos",
            "procedure": "almacen.List_SalidaActivos",
            "print": "true",
            "parameters": params
        };

        procesarProcedimientoJSON(
            "panelListaSalidaActivos", "tblListaSalidaActivos", optionSalidaMat, parameters, null, buttonsGridPerson
        );
    };

    $(function() {
        $("#fecdesde").datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });
        $("#fechasta").datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });
        buscarSalidaActivos();
        $("#btnbuscar").button(ICON_SEARCH);
        $("#div_titulo").html("Almacen => Salidas Activos");
    });
</script>