<?php
$library = new Libreria_Pintar();
$TipoBusqueda=array(array("0","GENERAL"),array("1","FECHA"));

?>

<div id="panelSalidaProducto" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 99%;margin: 1px; height:95%;">
    <div class="ui-widget ui-state-rojo ui-corner-top ui-title">
        <label>SALIDA DE PRODUCTOS</label>
    </div>
    <div id="dialogBuscarSalidaProducto" style="margin-bottom: -20px">

        <div class="col-sm-12 text-left ui-title text-nowrap bg-danger" >Datos del Producto</div>

        <div class="form-row">
            <div class="form-group col-md-6 text-left">
                <label for="inputModelo">Modelo</label>
                <input type="text" class="form-control" id="txtModelo" name="txtModelo" placeholder="Modelo">
            </div>
            <div class="form-group col-md-6 text-left">
                <label for="inputSerie">Serie</label>
                <input type="text" class="form-control" id="txtSerie" name="txtSerie" placeholder="Serie">
            </div>
        </div>

        <div class="col-sm-12 text-left ui-title text-nowrap bg-danger" >Datos del Proveedor</div>
        <div class="form-row">
            <div class="form-group col-md-6 text-left">
                <label for="inputRazonS" >Razon Social</label>
                <input type="text" class="form-control" id="txtRazonSocial" name="txtRazonSocial" placeholder="Razon social">
            </div>
            <div class="form-group col-md-6 text-left">
                <label for="inputRUC">RUC</label>
                <input type="text" class="form-control" id="txtRuc" name="txtRuc" placeholder="Ruc">
            </div>
        </div>

        <div class="col-sm-12 text-left text-nowrap bg-danger" ></div>


        <div class="form-group col-md-6 text-left">
            <label for="inputCity">Fecha Desde   </label>
            <input type="text" id="fecdesde" maxlength="10" class="form-control col-md-12" onkeypress="if(event.keyCode==13){buscarSalidaProd();}" value="<?php echo $this->fechaini; ?>" />
        </div>
        <div class="form-group col-md-6 text-left">
            <label for="inputState">Fecha Hasta</label>
            <input type="text" id="fechasta" maxlength="10" class="form-control col-md-12" onkeypress="if(event.keyCode==13){buscarSalidaProd();}" value="<?php echo $this->fechafin; ?>" />
        </div>


        <div class="form-group col-md-2 text-center" style="display: none;">
            <button id="btnbuscar" name="btnbuscar"  class="form-control" onclick="buscarEntradaProd()">Buscar</button>
        </div>
        <div  class="form-group">&thinsp;
        </div>








        <table class="ui-panelLayout-main"  style="display: none;">
            <tr>
                <td style="vertical-align: top;">
                    <table border="0" style="margin-left:15px;">
                         <tr><td>
                                <b>  Datos Busqueda</b>
                            </td></tr>

                        <tr class="rowdatospsm" id="rowdatospsm">
                            <td style="text-align: left">
                                <select id="cbotipob" name="cbotipob" style="width:140px;">
                                    <?php  echo $library->ContenidoCombo($TipoBusqueda, $this->ctipmon,0); ?>
                                </select>
                            </td>
                            <td></td>
                            <TD colspan="8">
                                Texto de busqueda: <input class="ui-text pnl" id="c_textbusqueda"  onkeypress="if(event.keyCode==13){buscarSalidaProd();}" style="width:100%" />
                            </TD>
                            <td> &nbsp;&nbsp;</td>
                            <td rowspan="3">
                                <button id="btnbuscar" name="btnbuscar" onclick="buscarSalidaProd()">Buscar</button>
                            </td>
                        </tr>
                        <tr class="rowcoti">

                            <td width="100" style="text-align: left">Fecha Desde:</td>
                            <td width="30">&nbsp;</td>
                            <td width="200" style="text-align: left">Fecha Hasta:</td>
                            <td width="10">&nbsp;</td>
                            <td width="10">&nbsp;</td>


                        </tr>
                        <tr class="rowbcoti" id="panelbcoti">

                            <td>
                                <input type="text" id="fecdesde" class="ui-text" value="<?php echo $this->fechaini; ?>" style="text-align: left;width: 80px;"/>
                            </td>
                            <td>&nbsp;</td>
                            <td colspan="2">
                                <input type="text" id="fechasta" class="ui-text" value="<?php echo $this->fechafin; ?>" style="text-align: left;width: 100px;"/>
                            </td>
                            <td>&nbsp;</td>


                        </tr>
                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>


                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>
                    </table>
                </td>
            </tr>

        </table>
    </div>
    <div id="dialogMensaje">
    </div>
    <div id="panelListaSalidaProd" align="left" style="width: 100%;margin-left: 15px; margin-right: 15px;">
        <table id="tblListaSalidaProd"></table>
        <div id="ptblListaSalidaProd"></div>
    </div>
    <br/>
</div>
<script type="text/javascript">


    $("#txtModelo").keyup(function(e){
        if($("#txtModelo").val().length>2 || e.keyCode==13 ){
            buscarSalidaProd();
            $("#txtModelo").focus();
        }
    });
    $("#txtSerie").keyup(function(e){
        if($("#txtSerie").val().length>2 || e.keyCode==13 ){
            buscarSalidaProd();
            $("#txtSerie").focus();
        }
    });
    $("#txtRazonSocial").keyup(function(e){
        if($("#txtRazonSocial").val().length>2 || e.keyCode==13 ){
            buscarSalidaProd();
            $("#txtRazonSocial").focus();
        }
    });
    $("#txtRuc").keyup(function(e){
        if($("#txtRuc").val().length>2 || e.keyCode==13 ){
            buscarSalidaProd();
            $("#txtRuc").focus();
        }
    });

    $("#cbotipob").combobox({
        selected: function(event, ui){
            buscarSalidaProd();
        }
    });


    optionSalidaProd = {
        width: 1100,
        height: 250,
        colNames: [
            'ID',
            'Fecha Salida',
            'Fecha Retorno',
            'Obra',
            'Lugar',
            'idTecnico',
            'Tecnico',
            "Estado",
            "Borrar",
            "Nuevo",
            "Imprimir",
            "Retorno"
        ],
        colModel: [
            {name: 'idSalidaProd', index:'idSalidaProd', width:80},
            {name: 'dFecSalida', index:'dFecSalida', width:80},
            {name: 'dFecRetorno', index:'dFecRetorno', width:80},
            {name: 'vObra', index:'vObra', width:200},
            {name: 'vLugar', index:'vLugar', width:200, hidden: false},
            {name: 'idTecnico', index:'idTecnico', width:70},
            {name: 'vTecnico', index:'vTecnico', width:150},
            {name: 'vEstado', index:'vEstado',width:50, hidden: false, editOptions:{value:"1:0",defaultvalue:"1"},formatter:'checkbox'},
            { name: 'btndocumall', index: 'btndocumall', width: 40, align: 'center' ,formatter : btndocumtall,search:false, hidden: false},
            { name: 'btndocumall', index: 'btndocumall', width: 40, align: 'center' ,formatter : btnNuevo,search:false, hidden: true},
            { name: 'btndocumall', index: 'btndocumall', width: 40, align: 'center' ,formatter : btnImprimir,search:false, hidden: false},
            { name: 'btndocudevo', index: 'btndocudevo', width: 60, align: 'center' ,formatter : btnRetorno,search:false}
        ],
        caption: "&nbsp;&nbsp;&nbsp;Salida de Productos",
        ondblClickRow: function(id){
            var row = $(this).getRowData(id);
            verSalidaProd();
        },
        afterInsertRow:function(rowid,aData){
            switch(aData.nestado){
                case'1':
                    break;
                case '0':
                    jQuery("#tblListaSalidaProd").jqGrid('setCell',rowid,'cidpers','',{color:'red'});
                    jQuery("#tblListaSalidaProd").jqGrid('setCell',rowid,'crazsoc','',{color:'red'});
                    jQuery("#tblListaSalidaProd").jqGrid('setCell',rowid,'vnrodoc','',{color:'red'});
                    jQuery("#tblListaSalidaProd").jqGrid('setCell',rowid,'nestado','',{color:'red'});
                break;
            }
        },
        onSelectRow: function(id) {
            var row = $(this).getRowData(id);
        }
    };



    // -----> Retorno ====================================================
    function btnRetorno(cellvalue, options, rowObject){

        return '<div align="center" class="ui-pg-button " title="Agregar Retorno" style="text-align:center;' +
            'float: left; cursor: pointer; display: block;" onmouseover="jQuery(this).addClass(\'ui-state-hover\');" ' +
            'onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" onclick="accionbtnRetorno(\''+options.rowId+'\');">' +
            '<div class="ui-pg-div  ui-inline-edit" ><span class="ui-icon ui-icon-arrowreturnthick-1-w"></span></div></div>';
    }

    function accionbtnRetorno(rowId){
        var row = $("#tblListaSalidaProd").jqGrid('getRowData', rowId);
        if(row.idSalidaProd == "" || row.idSalidaProd == undefined){
            openDialogWarning("Seleccione un Registro");
            return;
        }
        parameters = {
            "idSalidaProd": row.idSalidaProd
        };

        var _post = $.post(path + "almacen/detretornoprod", parameters);
        _post.success(function(request) {
            $("#panelSalidaProducto").html(request);
        });
    }



    function chkEliminar(cellvalue, options, rowObject) {
        return '<input  type="checkbox" id="chkconcluirexp_' + options.rowId + '" ' + (cellvalue == '1' ? ' checked="checked"' : '') +
            'onclick="changecheckboxcconcluirexp(' + options.rowId + ')" ' + (cellvalue == '1' ? '  ' : '') + '/>';
    }

    function changecheckboxcconcluirexp(rowId) {

        var row = jQuery("#tblListaSalidaProd").jqGrid('getRowData', rowId);
        openDialogConfirm1("Cambiar estado?", 350, {
            "Si": function () {
                var parmter = {};
                parmter.idSalidaProd = row.idSalidaProd;
                closeDialog("jqDialogConfirmacion1");
                $.post(path + "cotizacion/cotizaciondel", parmter, updCheckconcluir, 'json');
            },
            "No": function () {
                //ProcesoBuscarRuta(''); chkrecep_5
                $("#chkconcluirexp_" + rowId).attr('checked', false);
                closeDialog("jqDialogConfirmacion1");

            }
        });
    }
    function updCheckconcluir(data) {
        buscarSalidaProd();
    }



    // -----> Borrar============================================00
    function btndocumtall(cellvalue, options, rowObject){

        return '<div align="center" class="ui-pg-button " title="Borrar" style="text-align:center;float: left; ' +
            'cursor: pointer; display: block;" onmouseover="jQuery(this).addClass(\'ui-state-hover\');" ' +
            'onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
            'onclick="accionborrarsalida(\''+options.rowId+'\');"><div class="ui-pg-div  ui-inline-edit" >' +
            '<span class="ui-icon ui-icon-trash"></span></div></div>';
    }

    function accionborrarsalida(rowId){
        var rowdat = jQuery("#tblListaSalidaProd").jqGrid('getRowData',rowId);

        var paramtrs ={ idSalidaProd :rowdat.idSalidaProd }
        openDialogConfirm1("Seguro que desea eliminar el registro?", 350, {
            "Si": function () {
                $.ajax({
                    url: jQuery.scriptPath + "index.php/almacen/eliminarsalidaprod",
                    type: 'POST',
                    cache: false,
                    data: paramtrs,
                    beforeSend: function (data) {
                    },
                    success: function (requestData) {
                        var datos=JSON.parse(requestData);
                                console.log(datos);
                        var parameters ={ idSalidaProd :datos[0].idSalidaProd };
                        buscarSalidaProd();
                        closeDialog("jqDialogConfirmacion1");
                    },
                    error: function (requestData, strError, strTipoError) {
                        $("#result").html("Error " + strTipoError + ': ' + strError);
                    },
                    complete: function (requestData, exito) {
                    }
                });
            },
            "No": function () {
                closeDialog("jqDialogConfirmacion1");

            }
        });


    }
    // -----> Nuevo ====================================================
    function btnNuevo(cellvalue, options, rowObject){

        return '<div align="center" class="ui-pg-button " title="Nuevo a partir de esta cotizacion" style="text-align:center;float: left; cursor: pointer; display: block;" onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" onclick="accionbtnNuevo(\''+options.rowId+'\');"><div class="ui-pg-div  ui-inline-edit" ><span class="ui-icon ui-icon-document"></span></div></div>';
    }

    function accionbtnNuevo(rowId){
        var rowdat = jQuery("#tblListaSalidaProd").jqGrid('getRowData',rowId);
        var paramtrs ={ idSalidaProd :rowdat.idSalidaProd };
        console.log(paramtrs);
        $.ajax({
            url: jQuery.scriptPath + "index.php/cotizacion/copiarcotiz",
            type: 'POST',
            cache: false,
            data: paramtrs,
            beforeSend: function (data) {   },
            success: function (requestData) {
                var datos=JSON.parse(requestData);
              console.log(datos);
                var parameters ={ idSalidaProd :datos[0].idSalidaProd }
                var _post = $.post(path + "cotizacion/detcotizacion", parameters);
                _post.success(function(request) {
                    $("#panelSalidaProducto").html(request);
                });
            },
            error: function (requestData, strError, strTipoError) {
                $("#result").html("Error " + strTipoError + ': ' + strError);
            },
            complete: function (requestData, exito) {
            }
       });


    }

    // -----> Imprimir ====================================================
    function btnImprimir(cellvalue, options, rowObject){

        return '<div align="center" class="ui-pg-button " title="Imprimir Salida Prod" style="text-align:center;' +
            'float: left; cursor: pointer; display: block;" onmouseover="jQuery(this).addClass(\'ui-state-hover\');" ' +
            'onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" onclick="accionbtnImprimir(\''+options.rowId+'\');">' +
            '<div class="ui-pg-div  ui-inline-edit" ><span class="ui-icon ui-icon-print"></span></div></div>';
    }

    function accionbtnImprimir(rowId){
        var rowdat = jQuery("#tblListaSalidaProd").jqGrid('getRowData',rowId);
        var paramtrs ={ idSalidaProd :rowdat.idSalidaProd }
        host = '<?php echo $this->util()->getPath(); ?>report/';
        window.open(host+"rptSalidaProd.php?idSalida="+ rowdat.idSalidaProd ,'_blank');
    }



    nuevaSalidaProd = function(){
        parameters = {
            "idsigma": '0000000000'
        };
       window.open(path + "almacen/detsalidaprod", "_self");
    };
    verSalidaProd = function() {
        var selr = $('#tblListaSalidaProd').jqGrid('getGridParam','selrow');
        var row = $("#tblListaSalidaProd").jqGrid('getRowData', selr);
        if(row.idSalidaProd == "" || row.idSalidaProd == undefined){
            openDialogWarning("Seleccione un registro para editar.");
            return;
        }
        parameters = {
            "idSalidaProd": row.idSalidaProd
        };

        var _post = $.post(path + "almacen/detsalidaprod", parameters);
        _post.success(function(request) {
            $("#panelSalidaProducto").html(request);
        });


    };


    function buttonsGridSalidaProd(){
        $("#tblListaSalidaProd")
            .navGrid('#ptblListaSalidaProd', {edit:false,add:false,del:false,search:false,refresh:false})

            .navButtonAdd('#ptblListaSalidaProd',{
                caption:"Crear&nbsp;&nbsp;",
                buttonicon:"ui-icon-plus",
                onClickButton: function(){
                    nuevaSalidaProd();
                },
                position:"last"
            })
            .navSeparatorAdd()

            .navButtonAdd('#ptblListaSalidaProd',{
                caption:"Imprimir&nbsp;&nbsp;",
                buttonicon:"ui-icon-pencil",
                onClickButton: function(){
                    imprimir();
                },
                position:"last"
            })
            .navSeparatorAdd()
        ;
    }


    function imprimir(){
        var selr = $('#tblListaSalidaProd').jqGrid('getGridParam','selrow');
        var row = $("#tblListaSalidaProd").jqGrid('getRowData', selr);

        if(row.idSalidaProd == "" || row.idSalidaProd == undefined){
            openDialogWarning("Seleccione cotizacion.");
            return;
        }
        host = '<?php echo $this->util()->getPath(); ?>report/';
        window.open(host+"rptCotizacion.php?idSalidaProd="+ row.idSalidaProd ,'_blank');
    }



    buscarSalidaProd = function() {
        var fecdes=$("#fecdesde").val();
        var fechast =$("#fechasta").val();
        var modelo=$("#txtModelo").val();
        var serie=$("#txtSerie").val();
        var razsoc=$("#txtRazonSocial").val();
        var ruc=$("#txtRuc").val();
        var tipob='0';

        var params = '['
            + '["@tBusqueda", "' +tipob + '"],'
            + '["@vModelo", "' + modelo + '"],'
            + '["@vSerie", "' + serie + '"],'
            + '["@vRazonSoc", "' + razsoc + '"],'
            + '["@vRuc", "' + ruc + '"],'
            + '["@vFecIni", "' + fecdes + '"],'
            + '["@vFecFin", "' + fechast + '"]'
            + ']';
        parameters = {
            "name": "tblListaSalidaProd",
            "procedure": "almacen.List_SalidaProd",
            "print": "true",
            "parameters": params
        };

        procesarProcedimientoJSON(
            "panelListaSalidaProd"
            , "tblListaSalidaProd"
            , optionSalidaProd
            , parameters
            , null
            , buttonsGridSalidaProd
        );
    };

    $(function(){
        $("#fecdesde").datepicker({showOn: "button", buttonImage: pathImage + "calendar.gif", buttonImageOnly: true, dateFormat: "dd/mm/yy"});
        $("#fechasta").datepicker({showOn: "button", buttonImage: pathImage + "calendar.gif", buttonImageOnly: true, dateFormat: "dd/mm/yy"});
         buscarSalidaProd();
        $("#btnbuscar").button(ICON_SEARCH);
        $("#div_titulo").html("Almacen => Salida Productos");
    });


  //  themeComboBox("#cbo_bus");

</script>