<?php
$library = new Libreria_Pintar();
$TipoMoneda = array(array("2", "Soles"), array("1", "Dolares"));
$tiempo = array(array("Habil", "Habil"), array("Calendario", "Calendario"));
$TipoSoli = array(array("1", "SISTEMA CCTV HDCVI - HD"), array("2", "SISTEMA CCTV HDCVI - FULL HD"), array("3", "SISTEMA CCTV HDCVI - FULL HD Varifocal"), array("4", "SISTEMA CCTV HDCVI - 2K"), array("5", "SISTEMA CCTV IP - FULL HD"), array("6", "SISTEMA CCTV IP - FULL HD Varifocal"), array("7", "SISTEMA CCTV IP - 2K"), array("8", "SISTEMA CCTV IP - 4K"), array("9", "OTRO"));
$FormaPago = array(array("1", "Al contado"), array("2", "Adelanto del 50% del total y al finalizar el pago del 50% con la conformidad de la Obra"), array("9", "OTRO"));
$referencial = array(array("1", "Seleccione"), array("2", "LOS PRECIOS DE MATERIALES Y SERVICIOS SON REFERENCIALES PREVIA VISITA T&Eacute;CNICA SEG&Uacute;N CONFIRMACI&Oacute;N"), array("9", "OTRO"));
//print_r(count($TipoSoli));
$a = 0;
$b = 0;
$c = 0;
for ($i = 0; $i < count($TipoSoli); $i++) {
    if ($TipoSoli[$i][1] == $this->vMotivo) {
        $a = 1;
    }
}
if ($a == 0) {
    $motivo = 'OTRO';
} else {
    $motivo = $this->vMotivo;
}

for ($i = 0; $i < count($referencial); $i++) {
    if ($referencial[$i][1] == $this->nreferencial) {
        $b = 1;
    }
}
if ($b == 0) {
    $refere = 'OTRO';
} else {
    $refere = $this->nreferencial;
}
if (trim($this->nreferencial) == "") {
    $refere = 'Seleccione';
}

for ($i = 0; $i < count($FormaPago); $i++) {
    if ($FormaPago[$i][1] == $this->vFormaPago) {
        $c = 1;
    }
}
if ($c == 0) {
    $formap = 'OTRO';
} else {
    $formap = $this->vFormaPago;
}
if (trim($this->vFormaPago) == "") {
    $formap = 'Al contado';
}



?>

<div id="panelMantenimientoCotizacion" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 99%;margin: 1px; height:95%;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Detalle de Cotizacion</label>
    </div>
    <div id="dialogBuscarContribuyentePredio">
        <table class="ui-panelLayout-main">
            <tr>
                <td style="vertical-align: top;">
                    <table border="0" style="margin-left:45px;">
                        <tr>
                            <td>
                                <b> Datos Cliente</b>
                            </td>
                        </tr>
                        <tr class="rowBuscarContribuyente">

                            <td width="100" style="text-align: left">C&oacute;digo:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" style="text-align: left">Apellidos y Nombre:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230">&nbsp;</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" colspan="5" style="text-align: left">Nro. Documento:</td>
                            <td width="150">&nbsp;</td>
                        </tr>
                        <tr class="rowBuscarContribuyente" id="panelBuscarContribuyente">

                            <td>
                                <input class="ui-text-disable" readonly id="codigocontrib" value="<?php echo $this->idcliente; ?>" maxlength="10" style="width:90px" />
                            </td>
                            <td>&nbsp;</td>
                            <td colspan="3">
                                <input class="ui-text-disable pnl" readonly id="nombrecontrib" value="<?php echo $this->nombrec; ?>" style="width:100%" />
                            </td>
                            <td>&nbsp;</td>
                            <td colspan="5" style="text-align: left;">
                                <input class="ui-text-disable pnl" readonly id="nrodoc" value="<?php echo $this->vnrodoc; ?>" style="width:50%" />
                            </td>
                            <td rowspan="1">
                                <button id="btnbuscar" name="btnbuscar" onclick="buscarCliente()">Buscar Cliente</button>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <b> Datos Cotizacion</b>
                            </td>
                        </tr>
                        <tr class="rowcoti">

                            <td width="100" style="text-align: left">Fecha:</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" style="text-align: left">Tasa Cambio</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" class="soloSolesa">&nbsp; Tipo de Moneda</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" colspan="5" style="text-align: left">Nro. Cotizacion:</td>

                        </tr>

                        <tr class="rowbcoti" id="panelbcoti">

                            <td>
                                <input type="text" id="fecdesde" value="<?php echo $this->dfeccot; ?>" class="ui-text-disable " readonly style="text-align: left;width: 80px;" />
                            </td>
                            <td>&nbsp;</td>
                            <td class="soloSolesa">&nbsp;<input type="text" class="ui-text- pnl" id="tasacambio" value="<?php if ($this->tasacambio == '') {
                                                                                                                            echo '';
                                                                                                                        } else {
                                                                                                                            echo $this->tasacambio;
                                                                                                                        } ?>" style="width:50%" /></td>

                            <td>&nbsp;
                            </td>
                            <td colspan="2">
                                <select id="cbtipomon" name="cbtipomon" style="width:140px;">
                                    <?php echo $library->ContenidoCombo($TipoMoneda, $this->ctipmon, 0); ?>
                                </select>
                                <input type="hidden" class="ui-text-disable pnl" id="idcotizacion" value="<?php echo $this->idcotizacion; ?>" style="width:50%" />
                            </td>

                            <td colspan="5" style="text-align: left;">
                                <input class="ui-text-disable pnl" readonly id="c_nrocoti" value="<?php echo $this->vnrocot; ?>" style="width:50%" />
                            </td>

                        </tr>

                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>
                        <tr>
                            <td colspan="7">
                                Cotizacion solicitada por:
                                <select id="cbtitulo" name="cbtitulo" style="width:240px;">
                                    <?php echo $library->ContenidoComboSeleccionaporDescripcion($TipoSoli, $motivo, 0); ?>
                                </select>
                                <input class="ui-text pnl titulotext" id="c_motivo" value="<?php echo $this->vMotivo; ?>" style="width:50%; display: none" />
                                <input type="hidden" id="c_motivohd" value="<?php echo $this->vMotivo; ?>" style="width:50%; display: none" />
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <div id="dialogMensaje">
    </div>
    <div id="panelDetCotizacion" align="left" style="width: 99%;margin-left: 0px;">
        <table id="tblDetCotizacion"></table>
        <div id="ptblDetCotizacion">
        </div>
    </div>
    <br />


    <div align="left">
        <table border="0" style=" margin-left: 45px; margin-right: 45px">
            <tr>
                <td rowspan="6" style="width:78%;">
                    <table border="0" style="width:100%;">

                        <tr>
                            <td>Nota Referencial</td>
                            <td>
                                <select id="cbreferencial" name="cbreferencial" style="width:200px;">
                                    <?php echo $library->ContenidoComboSeleccionaporDescripcion($referencial, $refere, 0); ?>
                                </select>
                                <input class="ui-text pnl referencialtext" id="c_referencial" value="<?php echo $this->nreferencial; ?>" style="width:50%; display: none" />
                                <input type="hidden" id="referncialhd" value="<?php echo $this->nreferencial; ?>">
                            </td>
                        </tr>

                        <tr>
                            <td> Grabacion Disco: </td>
                            <td><input type="text" class="ui-text" id="txtdisco" value="<?php if ($this->disco == '') {
                                                                                            echo '';
                                                                                        } else {
                                                                                            echo $this->disco;
                                                                                        } ?>" maxlength="20" style="width:90px; text-align: right" /> días aproximado.
                            </td>
                        </tr>

                        <tr>
                            <td style="width:18%;"> Tiempo de Entrega:</td>
                            <td><input type="text" class="ui-text" id="txttentrega" value="<?php if ($this->tentrega == '') {
                                                                                                echo '';
                                                                                            } else {
                                                                                                echo $this->tentrega;
                                                                                            } ?>" maxlength="20" style="width:90px; text-align: right" />

                                <select id="cbtiempo" name="cbtiempo" style="width:150px;">
                                    <?php echo $library->ContenidoComboSeleccionaporDescripcion($tiempo, $this->tiempoo, 0); ?>
                                </select>
                            </td>
                        </tr>

                        <tr>
                            <td> Garantia: </td>
                            <td><input type="text" class="ui-text" id="txtgarantia" value="<?php if ($this->garantia == '') {
                                                                                                echo '12';
                                                                                            } else {
                                                                                                echo $this->garantia;
                                                                                            } ?>" maxlength="20" style="width:90px; text-align: right" /> Meses.
                            </td>
                        </tr>
                        <tr>
                            <td>Forma de Pago</td>
                            <td>
                                <select id="cbformapago" name="cbformapago" style="width:200px;">
                                    <?php echo $library->ContenidoComboSeleccionaporDescripcion($FormaPago, $formap, 0); ?>
                                </select>
                                <input class="ui-text pnl formapagotext" id="c_formapago" value="<?php echo $this->vFormaPago; ?>" style="width:50%; display: none" />
                                <input type="hidden" id="formapagohd" value="<?php echo $this->vFormaPago; ?>">
                            </td>
                        </tr>



                    </table>

                </td>
            </tr>

            <tr style="width:20%;">
                <td align="right"><b>Sub Total:</b></td>
                <td><b>
                        <input type="text" class="ui-text-disable" readonly id="txtsubtotal" value="<?php echo $this->subtotal; ?>" maxlength="20" style="width:90px; text-align: right" />
                    </b></td>
            </tr>
            <tr align="right">
                <td><b>IGV:</b></td>
                <td><b> <input type="text" class="ui-text-disable" readonly id="txtigv" value="<?php echo $this->igv; ?>" maxlength="20" style="width:90px; text-align: right" /></b></td>
            </tr>
            <tr align="right">
                <td><b>Total:</b></td>
                <td><b> <input type="text" class="ui-text-disable" readonly id="txttotal" value="<?php echo $this->total; ?>" maxlength="20" style="width:90px; text-align: right" /></b></td>
            </tr>

            <tr style="display: block">
                <td style="text-align: left">
                    <input type="checkbox" name="chkClitec" id="chkClitec" value="1" offvalue="0" onclick="habilitardesc();" class="ui-text" <?php if ($this->clientetec != '') {
                                                                                                                                                    if ($this->clientetec == 1) {
                                                                                                                                                        echo 'checked';
                                                                                                                                                    }
                                                                                                                                                } else {
                                                                                                                                                } ?>> Cliente tecnico
                </td>

            </tr>
            <tr>
                <td><button id="btncancelardet" name="btncancelardet">Cancelar</button></td>
                <td>
                    <button id="btnguardar" name="btnguardar" onclick="GuardardetalleCot()">Guardar</button>
                </td>
            </tr>


        </table>
    </div>

    <div id="panelDetCotizacionOPC" align="left" style="width: 99%;margin-left: 0px;">
        <table id="tblDetCotizacionOPC"></table>
        <div id="ptblDetCotizacionOPC">
        </div>
    </div>
    <br />
</div>
<script type="text/javascript">
    themeComboBox();

    function validarTipoCambio(tipo) {
        switch (tipo) {
            case '1': // Dolares
                $(".soloSoles").hide();
                ActualizarMontos();
                //$("#tasacambio").val("0");
                break;
            case '2': // Soles
                $(".soloSoles").show();
                break;
            default:
                break;
        }
    }
    validarTipoCambio($("#cbtipomon").val());

    $("#cbtipomon").combobox({
        selected: function(event, ui) {
            //validarTipoCambio($("#cbtipomon").val())
            ActualizarMontos();
            detalleCotizacionSave();
        }
    });
    $("#cbtitulo").combobox({
        selected: function(event, ui) {
            var select = document.getElementById('cbtitulo');
            var selectedOption = this.options[select.selectedIndex];
            console.log(selectedOption.value + ': ' + selectedOption.text);
            $("#c_motivohd").val(selectedOption.text);
            if ($("#cbtitulo").val() == '9') {
                $(".titulotext").show();
                $("#c_motivo").val("");


            } else {
                $(".titulotext").hide();
            }
        }
    });
    $("#cbreferencial").combobox({
        selected: function(event, ui) {
            var select = document.getElementById('cbreferencial');
            var selectedOption = this.options[select.selectedIndex];
            console.log(selectedOption.value + ': ' + selectedOption.text);
            $("#referncialhd").val(selectedOption.text);
            if ($("#cbreferencial").val() == '9') {
                $(".referencialtext").show();
                $("#c_referencial").val("");
            } else {
                $(".referencialtext").hide();
            }
        }
    });

    $("#cbformapago").combobox({
        selected: function(event, ui) {
            var select = document.getElementById('cbformapago');
            var selectedOption = this.options[select.selectedIndex];
            console.log(selectedOption.value + ': ' + selectedOption.text);
            $("#formapagohd").val(selectedOption.text);
            if ($("#cbformapago").val() == '9') {
                $(".formapagotext").show();
            } else {
                $(".formapagotext").hide();
            }
        }
    });

    var lastsel3;
    optionDetCoti = {
        datatype: "local",
        width: 1280,
        height: 250,
        keys: true,
        rowNum: 80,
        colNames: [
            'Id',
            'Id cot',
            'Modelo',
            'Producto o Servicio',
            'Descripcion',
            'Stock',
            'PU',
            'Cantidad',
            '% Descuento',
            'Valor Venta',
            'estado',
            'orden',
            "opcional",
            "tipops",
            "idprodserv",
            "",
            "",
            "Ficha Técnica",
            "",
            "",
            ""
        ],
        colModel: [{
                name: 'idDetCotiz',
                index: 'idDetCotiz',
                width: 40,
                hidden: true
            },
            {
                name: 'idCotiz',
                index: 'idCotiz',
                width: 40,
                hidden: true
            },
            {
                name: 'modelo',
                index: 'modelo',
                width: 140
            },
            {
                name: 'vNombrePSM',
                index: 'vNombrePSM',
                width: 200
            },
            {
                name: 'vDescrip',
                index: 'vDescrip',
                width: 280,
                editable: false,
                edittype: "text"
            },
            {
                name: 'stock',
                index: 'stock',
                width: 60,
                editable: false,
                edittype: "text"
            },
            {
                name: 'nPrecUnit',
                index: 'nPrecUnit',
                width: 70,
                editable: true,
                edittype: "text",
                editoptions: {
                    dataInit: function(elem) {
                        setTimeout(function() {
                            $(elem).numeric();
                        }, 100);
                    }
                }
            },
            {
                name: 'nCantidad',
                index: 'nCantidad',
                width: 70,
                editable: true,
                editoptions: {
                    dataInit: function(elem) {
                        setTimeout(function() {
                            $(elem).numeric();
                        }, 100);
                    }
                }
            },
            {
                name: 'nDesc',
                index: 'nDesc',
                width: 70,
                hidden: true,
                editable: true,
                editoptions: {
                    dataInit: function(elem) {
                        setTimeout(function() {
                            $(elem).numeric();
                        }, 100);
                    }
                }
            },
            {
                name: 'nPrecTotal',
                index: 'nPrecTotal',
                width: 70,
                editable: true,
                editoptions: {
                    dataInit: function(elem) {
                        setTimeout(function() {
                            $(elem).numeric();                            
                        }, 100);
                    }
                }
            },
            {
                name: 'vEstado',
                index: 'vEstado',
                width: 100,
                hidden: true,
                editable: false
            },
            {
                name: 'nOrden',
                index: 'nOrden',
                width: 200,
                hidden: true
            },
            {
                name: 'opcional',
                index: 'opcional',
                width: 200,
                hidden: true
            },
            {
                name: 'tipoPS',
                index: 'tipoPS',
                width: 200,
                hidden: true
            },
            {
                name: 'idProdServ',
                index: 'idProdServ',
                width: 200,
                hidden: true
            },
            {
                name: 'btndocumall',
                index: 'btndocumall',
                width: 40,
                align: 'center',
                formatter: btncalcular,
                search: false
            },
            {
                name: 'btndocumall',
                index: 'btndocumall',
                width: 40,
                align: 'center',
                formatter: btndelete,
                search: false
            },
            {
                name: 'docadjunto',
                index: 'docadjunto',
                width: 250,
                align: 'left',
                formatter: linkadjunto
            },
            {
                name: 'docadjunto',
                index: 'docadjunto',
                width: 250,
                align: 'left',
                hidden: true
            },
            {
                name: 'visor',
                index: 'visor',
                width: 20
            },
            {
                name: 'trash',
                index: 'trash',
                width: 20
            }
        ],
        editurl: "clientArray",
        caption: "&nbsp;&nbsp;&nbsp;Detalle de la Cotizacion",
        ondblClickRow: function(id) {
            var row = $(this).getRowData(id);
            //console.log(row);
            //dobleclickPersona(row);
            //  verCotizacion();
        },
        afterInsertRow: function(rowid, aData) {
            switch (aData.opcional) {
                case '':
                    break;
                case '1':
                    jQuery("#tblDetCotizacion").jqGrid('setCell', rowid, 'idDetCotiz', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacion").jqGrid('setCell', rowid, 'idCotiz', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacion").jqGrid('setCell', rowid, 'vNombrePSM', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacion").jqGrid('setCell', rowid, 'vDescrip', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacion").jqGrid('setCell', rowid, 'stock', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacion").jqGrid('setCell', rowid, 'nPrecUnit', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacion").jqGrid('setCell', rowid, 'nCantidad', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacion").jqGrid('setCell', rowid, 'nDesc', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacion").jqGrid('setCell', rowid, 'nPrecTotal', '', {
                        background: '#ddeaa6'
                    });
                    break;
            }
        },
        onSelectRow: function(id) {
            //var row = $(this).getRowData(id);
            // console.log(lastsel3);
            if (lastsel3 != undefined)
                calcular();
            if (lastsel2 != undefined) {
                calcularOpc();
            }

            if (id && id !== lastsel3) {
                jQuery('#tblDetCotizacion').jqGrid('saveRow', lastsel3);
                lastsel3 = id;
            }
            jQuery('#tblDetCotizacion').jqGrid('editRow', id, true);

        },
        gridComplete: function(id) {
            habilitarColumna("<?php echo $this->clientetec ?>");
            calcular();

            isGridComplete = true;
            $("#tblDetCotizacion").jqGrid('setSelection', 1, true);

            var ids = jQuery("#tblDetCotizacion").jqGrid('getDataIDs');

            for (var i = 0; i < ids.length; i++) {
                var cl = ids[i];
                var rowdat = jQuery("#tblDetCotizacion").jqGrid('getRowData', cl);
                buttvisor = '<div title="Visor de ' + rowdat.docadjunto + '" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\')" onclick="visorarchivo(\'' + rowdat.docadjunto + '\');"><span class="ui-icon ui-icon-search"></span></div>';

                jQuery("#tblDetCotizacion").jqGrid('setRowData', ids[i], {
                    visor: buttvisor
                });
                if ('' == '1') {
                    butttrash = '<div title="Eliminar ' + rowdat.vadjunto + '" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\')" onclick="eliminarDocAdjunto(\'' + rowdat.idsigma + '\');"><span class="ui-icon ui-icon-trash"></span></div>';

                    jQuery("#tblDetCotizacion").jqGrid('setRowData', ids[i], {
                        trash: butttrash
                    });
                }
            }
        },
        aftersavefunc: function(rowid) { // can add jqXHR, sentData, options
            alert(rowid + " is saved");
        }
    };


    habilitardesc = function() {
        if (document.getElementById('chkClitec').checked == true) {
            jQuery("#tblDetCotizacion").jqGrid('showCol', "nDesc");
            jQuery("#tblDetCotizacionOPC").jqGrid('showCol', "nDesc"); //Para la grilla de opcional
            calcular();
            //Para la grilla de opcional
            if (lastsel2 != undefined) {
                calcularOpc();
            }

        } else {
            jQuery("#tblDetCotizacion").jqGrid('hideCol', "nDesc");
            //jQuery("#tblDetCotizacion").jqGrid('showCol',"nDesc");
            jQuery('#tblDetCotizacion').jqGrid('saveRow', lastsel3);

            //Para la grilla de opcional
            jQuery("#tblDetCotizacionOPC").jqGrid('hideCol', "nDesc");
            jQuery('#tblDetCotizacionOPC').jqGrid('saveRow', lastsel2);

            var rows = jQuery("#tblDetCotizacion").jqGrid('getRowData');
            if (rows.length > 0) {
                for (var i = 0; i < rows.length; i++) {
                    $("#tblDetCotizacion").setRowData(i + 1, {
                        nDesc: 0
                    });
                }
            }

            //Para la grilla de opcional
            var rows1 = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData');
            if (rows1.length > 0) {
                for (var i = 0; i < rows1.length; i++) {
                    $("#tblDetCotizacionOPC").setRowData(i + 1, {
                        nDesc: 0
                    });
                }
            }


            calcular();
            if (lastsel2 != undefined) {
                calcularOpc();
            }
        }
    };

    buscarCliente = function() {
        parameters = {
            "idsigma": $("#idcotizacion").val()
        };
        openDialogData1("cotizacion/buscarpersona", parameters, 660);

        //   window.open(path + "mantenimientos/backup", "_self");

    };
    eliminar = function(a) {
        var selr = $('#tblDetCotizacion').jqGrid('getGridParam', 'selrow');
        var row = $("#tblDetCotizacion").jqGrid('getRowData', selr);
        if (row.cidpers == "" || row.cidpers == undefined) {
            openDialogWarning("Seleccione un registro para eliminar.");
            return;
        }
        parameters = {
            "idsigma": row.cidpers
        };

        //openDialogData2("mantenimientos/eliminarpersona", parameters, 460);
        openDialogConfirm1("\u00BFEst\u00E1 seguro de eliminar datos?", 350, {

            "si": function() {
                //openDialogData2("mantenimientos/eliminarpersona", parameters, 460);
                $.ajax({
                    url: jQuery.scriptPath + "index.php/mantenimientos/eliminarpersona",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function(data) {

                    },
                    success: function(requestData) {
                        $("#result").html(requestData);
                        closeDialog("jqDialogConfirmacion1");
                        closeDialog('jqDialog1');



                    },
                    error: function(requestData, strError, strTipoError) {
                        $("#result").html("Error " + strTipoError + ': ' + strError);
                    },
                    complete: function(requestData, exito) {}


                });
            },

            "no": function() {
                closeDialog("jqDialogConfirmacion1");

            }
        })


    };

    function linkadjunto(cellvalue, options, rowObject) {
        return '<a href="#" onclick="linkadjuntoOpen(\'' + options.rowId + '\',\'' + cellvalue + '\')" > ' + cellvalue + '</a>'
    }

    function linkadjuntoOpen(rowId, cellvalue) {
        var row = jQuery("#tblResultDocAdjunto").jqGrid('getRowData', rowId);
        //console.log(row);
        window.open(path + "mantenimientos/forzardescarga?file=" + cellvalue);
    }


    function ActualizarMontos() {

        jQuery('#tblDetCotizacion').jqGrid('saveRow', lastsel3);
        var tasa = $("#tasacambio").val();
        var tipomon = $("#cbtipomon").val();
        if (document.getElementById('chkClitec').checked == true) {
            var tieneDes = 'SI';
        } else {
            var tieneDes = 'NO';
        }
        if (tasa == 0 || tasa == undefined || tasa == "") {
            openDialogWarning("Ingrese la tasa de cambio.");
            return;
        }
        var rows = jQuery("#tblDetCotizacion").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                var subt = parseFloat(row.nPrecUnit);
                if (tipomon == '1') { //Si es dolares divide el subtotal entre la tasa de cambio
                    subtotal = subt / tasa;
                } else { //Si es soles multiplica el subtotal por la tasa de cambio
                    subtotal = subt * tasa;
                }
                var total = subtotal * (row.nCantidad);
                if (tieneDes == "SI") {
                    var pdesc = row.nDesc;
                } else {
                    var pdesc = 0;
                }
                var total1 = total - (total * pdesc / 100);
                console.log(total1);
                $("#tblDetCotizacion").setRowData(i + 1, {
                    nPrecUnit: parseFloat(Math.round(subtotal * 100) / 100).toFixed(2)
                });
                $("#tblDetCotizacion").setRowData(i + 1, {
                    nPrecTotal:  parseFloat(Math.round(total1 * 100) / 100).toFixed(2)
                });
            }
        }



        /**Tabla opcional actualizando datos*/

        jQuery('#tblDetCotizacionOPC').jqGrid('saveRow', lastsel2);
        if (document.getElementById('chkClitec').checked == true) {
            var tieneDes = 'SI';
        } else {
            var tieneDes = 'NO';
        }
        if (tasa == 0 || tasa == undefined || tasa == "") {
            openDialogWarning("Ingrese la tasa de cambio.");
            return;
        }
        var rows = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                var subt = parseFloat(row.nPrecUnit);
                if (tipomon == '1') { //Si es dolares divide el subtotal entre la tasa de cambio
                    subtotal = subt / tasa;
                } else { //Si es soles multiplica el subtotal por la tasa de cambio
                    subtotal = subt * tasa;
                }
                var total = subtotal * (row.nCantidad);
                if (tieneDes == "SI") {
                    var pdesc = row.nDesc;
                } else {
                    var pdesc = 0;
                }
                var total1 = total - (total * pdesc / 100);
                //console.log(total1);
                $("#tblDetCotizacionOPC").setRowData(i + 1, {
                    nPrecUnit: parseFloat(Math.round(subtotal * 100) / 100).toFixed(2)
                });
                $("#tblDetCotizacionOPC").setRowData(i + 1, {
                    nPrecTotal: parseFloat(Math.round(total1 * 100) / 100).toFixed(2)
                });
            }
        }

        /**total de cotizacion*/
        var rows = jQuery("#tblDetCotizacion").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                if (row.opcional != '1') {
                    var subt = parseFloat(row.nPrecTotal);
                    subtotal = subtotal + subt;
                } else {}
            }


            var txtotal = subtotal;

            var txsubtotal = (txtotal / 1.18);

            var txigv = txtotal - txsubtotal;

            $("#txtsubtotal").val(parseFloat(Math.round(txsubtotal * 100) / 100).toFixed(2));
            $("#txtigv").val(parseFloat(Math.round(txigv * 100) / 100).toFixed(2));
            $("#txttotal").val(parseFloat(Math.round(txtotal * 100) / 100).toFixed(2));



        }
        return true;
    };
    var formatNumber = {
        separador: ",", // separador para los miles
        sepDecimal: '.', // separador para los decimales
        formatear: function(num) {
            num += '';
            var splitStr = num.split('.');
            var splitLeft = splitStr[0];
            var splitRight = splitStr.length > 1 ? this.sepDecimal + splitStr[1] : '';
            var regx = /(\d+)(\d{3})/;
            while (regx.test(splitLeft)) {
                splitLeft = splitLeft.replace(regx, '$1' + this.separador + '$2');
            }
            return this.simbol + splitLeft + splitRight;
        },
        new: function(num, simbol) {
            this.simbol = simbol || '';
            return this.formatear(num);
        }
    }

    function calcular() {
        var rows = jQuery("#tblDetCotizacion").jqGrid('getRowData');
        if (rows.length > 0) {} else {
            return;
        }
        if (document.getElementById('chkClitec').checked == true) {
            var tieneDes = 'SI';
        } else {
            var tieneDes = 'NO';
        }
        //console.log(lastsel3);
        if (lastsel3 == undefined) {
            lastsel3 = 1;
        }
        //console.log(lastsel3);
        jQuery('#tblDetCotizacion').jqGrid('saveRow', lastsel3);
        gsrr = jQuery("#tblDetCotizacion").jqGrid('getRowData');
        //var nrowid = $('#tblDetCotizacion').jqGrid('getGridParam','selrow');
        var subtot = (gsrr[lastsel3 - 1].nPrecUnit) * (gsrr[lastsel3 - 1].nCantidad);
        if (tieneDes == "SI") {
            var pdesc = gsrr[lastsel3 - 1].nDesc;
        } else {
            var pdesc = 0;
        }
        var total1 = subtot - (subtot * pdesc / 100);
        $("#tblDetCotizacion").setRowData(lastsel3, {
            nPrecTotal: parseFloat(Math.round(total1 * 100) / 100).toFixed(2) 
        });

        var rows = jQuery("#tblDetCotizacion").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                if (row.opcional != '1') {
                    var subt = parseFloat(row.nPrecTotal);
                    subtotal = subtotal + subt;
                } else {}
            }

            var txtotal = subtotal;

            var txsubtotal = (txtotal / 1.18);

            var txigv = txtotal - txsubtotal;

            $("#txtsubtotal").val(parseFloat(Math.round(txsubtotal * 100) / 100).toFixed(2));
            $("#txtigv").val(parseFloat(Math.round(txigv * 100) / 100).toFixed(2));
            $("#txttotal").val(parseFloat(Math.round(txtotal * 100) / 100).toFixed(2));

        }
        return true;
    };

    detalleCotizacionSave = function() {
        jQuery('#tblDetCotizacion').jqGrid('saveRow', lastsel3);
        var rows = jQuery("#tblDetCotizacion").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                parameters = {
                    "idDetCotiz": row.idDetCotiz,
                    "nPrecUnit": row.nPrecUnit,
                    "nCantidad": row.nCantidad,
                    "nPrecTotal": row.nPrecTotal,
                    "nDescu": row.nDesc
                };
                $.ajax({
                    url: jQuery.scriptPath + "index.php/cotizacion/detcotizacionupdate",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function(data) {},
                    success: function(requestData) {

                    },
                    error: function(requestData, strError, strTipoError) {},
                    complete: function(requestData, exito) {}
                });
            }
        }

        //Actualizamos el opcional
        jQuery('#tblDetCotizacionOPC').jqGrid('saveRow', lastsel2);
        var rows1 = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData');
        if (rows1.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows1.length; i++) {
                var row = rows1[i];
                parameters = {
                    "idDetCotiz": row.idDetCotiz,
                    "nPrecUnit": row.nPrecUnit,
                    "nCantidad": row.nCantidad,
                    "nPrecTotal": row.nPrecTotal,
                    "nDescu": row.nDesc
                };
                $.ajax({
                    url: jQuery.scriptPath + "index.php/cotizacion/detcotizacionupdate",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function(data) {},
                    success: function(requestData) {

                    },
                    error: function(requestData, strError, strTipoError) {},
                    complete: function(requestData, exito) {}
                });
            }
        }
    }
    GuardardetalleCot = function() {
        jQuery('#tblDetCotizacion').jqGrid('saveRow', lastsel3);
        var rows = jQuery("#tblDetCotizacion").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                parameters = {
                    "idDetCotiz": row.idDetCotiz,
                    "nPrecUnit": row.nPrecUnit,
                    "nCantidad": row.nCantidad,
                    "nPrecTotal": row.nPrecTotal,
                    "nDescu": row.nDesc
                };
                $.ajax({
                    url: jQuery.scriptPath + "index.php/cotizacion/detcotizacionupdate",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function(data) {},
                    success: function(requestData) {

                    },
                    error: function(requestData, strError, strTipoError) {},
                    complete: function(requestData, exito) {}
                });
            }
        }

        //Actualizamos el opcional
        jQuery('#tblDetCotizacionOPC').jqGrid('saveRow', lastsel2);
        var rows1 = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData');
        if (rows1.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows1.length; i++) {
                var row = rows1[i];
                parameters = {
                    "idDetCotiz": row.idDetCotiz,
                    "nPrecUnit": row.nPrecUnit,
                    "nCantidad": row.nCantidad,
                    "nPrecTotal": row.nPrecTotal,
                    "nDescu": row.nDesc
                };
                $.ajax({
                    url: jQuery.scriptPath + "index.php/cotizacion/detcotizacionupdate",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function(data) {},
                    success: function(requestData) {

                    },
                    error: function(requestData, strError, strTipoError) {},
                    complete: function(requestData, exito) {}
                });
            }
        }



        if ($("#cbtitulo").val() == '9') {
            var titulo = $("#c_motivo").val();
        } else {
            var titulo = $("#c_motivohd").val();

        }




        if ($("#cbformapago").val() == '9') {
            var formapago = $("#c_formapago").val();
        } else {
            var formapago = $("#formapagohd").val();

        }

        if ($("#cbreferencial").val() == '9') {
            var referencial = $("#c_referencial").val();
        } else if ($("#cbreferencial").val() == '1') {
            var referencial = "";
        } else {
            var referencial = $("#referncialhd").val();

        }

        if (document.getElementById('chkClitec').checked == true) {
            var tieneDes = 1;
        } else {
            var tieneDes = 0;
        }
        parameters1 = {
            "idsigma": $("#idcotizacion").val(),
            "subtotal": $("#txtsubtotal").val(),
            "igv": $("#txtigv").val(),
            "total": $("#txttotal").val(),
            "tipoMoneda": $("#cbtipomon").val(),
            "tasaCambio": $("#tasacambio").val(),
            "Clientetec": tieneDes,
            "TiempoEntrega": $("#txttentrega").val(),
            "Garantia": $("#txtgarantia").val(),
            "Motivo": titulo,
            "Formapago": formapago,
            "Referencial": referencial,
            "Disco": $("#txtdisco").val(),
            "Tiempo": $("#cbtiempo").val()




        };
        $.ajax({
            url: jQuery.scriptPath + "index.php/cotizacion/cotizacionupdate",
            type: 'POST',
            cache: false,
            data: parameters1,
            beforeSend: function(data) {},
            success: function(requestData) {
                imprimir();
                window.open(path + "cotizacion/cotizacion", "_self");
            },
            error: function(requestData, strError, strTipoError) {},
            complete: function(requestData, exito) {}
        });

    };
    nuevaPSM = function() {
        var tasa = $("#tasacambio").val();
        var tipomon = $("#cbtipomon").val();

        if (tipomon == '1') { //Si es dolares

        } else { //Si es soles
            if (tasa == 0 || tasa == undefined || tasa == "" || isNaN(tasa)) {
                openDialogWarning("Ingrese la tasa de cambio.");
                return;
            }
        }

        parameters = {
            "idsigma": $("#idcotizacion").val()
        };
        openDialogData1("cotizacion/addpsm", parameters, 560, 500);

    };

    addopcional = function() {
        var tasa = $("#tasacambio").val();
        var tipomon = $("#cbtipomon").val();

        if (tipomon == '1') { //Si es dolares

        } else { //Si es soles
            if (tasa == 0 || tasa == undefined || tasa == "" || isNaN(tasa)) {
                openDialogWarning("Ingrese la tasa de cambio.");
                return;
            }
        }
        parameters = {
            "idsigma": $("#idcotizacion").val(),
            "opcional": 1
        };
        openDialogData1("cotizacion/addpsm", parameters, 560, 500);
        //inicializarGrid('tblDetCotizacionOPC',optionDetCotiOPC);
        //buscardetCotizacionOpcional();
    };

    crearmaterial = function() {
        parameters = {
            "idsigma": '...'
        };

        openDialogData2("mantenimientos/material", parameters, 460, 200);
    };
    addMaterial = function(a) {
        PARAMETRO_NIVEL_LLAMADA = 3;
        ArregloMateriales.splice(0, ArregloMateriales.length); //Eliminar el arreglo
        var selr = $('#tblDetCotizacion').jqGrid('getGridParam', 'selrow');
        var row = $("#tblDetCotizacion").jqGrid('getRowData', selr);
        var tipo = row.tipoPS;
        var nombre = row.vNombrePSM;
        // console.log(row.tipoPS);
        if (tipo == "" || tipo == undefined || tipo == '1' || nombre == 'Material' || nombre == 'MATERIAL' || nombre == 'MATERIALES') {
            openDialogWarning("Seleccione un Servicio.");
            return;
        }
        parameters = {
            "idsigma": row.idProdServ,
            "nombre": row.vNombrePSM,
            "idcotizacion": $("#idcotizacion").val(),
            "Descripcion": row.vDescrip,
            "idDetCotizacion": row.idDetCotiz
        };

        openDialogData1("mantenimientos/agregarmaterialserv", parameters, 460, 460);
        // closeDialog("jqDialog2");
    };

    addMaterial1 = function(a) {
        PARAMETRO_NIVEL_LLAMADA = 3;
        ArregloMateriales.splice(0, ArregloMateriales.length); //Eliminar el arreglo
        var selr = $('#tblDetCotizacionOPC').jqGrid('getGridParam', 'selrow');
        var row = $("#tblDetCotizacionOPC").jqGrid('getRowData', selr);
        var tipo = row.tipoPS;
        var nombre = row.vNombrePSM;
        // console.log(row.tipoPS);
        if (tipo == "" || tipo == undefined || tipo == '1' || nombre == 'Material' || nombre == 'MATERIAL' || nombre == 'MATERIALES') {
            openDialogWarning("Seleccione un Servicio.");
            return;
        }
        parameters = {
            "idsigma": row.idProdServ,
            "nombre": row.vNombrePSM,
            "idcotizacion": $("#idcotizacion").val(),
            "opcional": "1",
            "idDetCotizacion": row.idDetCotiz,
            "Descripcion": row.vDescrip
        };

        openDialogData1("mantenimientos/agregarmaterialserv", parameters, 460, 460);
        // closeDialog("jqDialog2");
    };
    /*
    addMaterial = function(){
        parameters = {
            "idsigma": $("#idcotizacion").val()
        };
        openDialogData1("mantenimientos/agregarmaterial", parameters, 420,350);
    };*/

    function buttonsGridDetcoti() {
        $("#tblDetCotizacion")
            .navGrid('#ptblDetCotizacion', {
                edit: false,
                add: false,
                del: false,
                search: false,
                refresh: false
            })

            .navButtonAdd('#ptblDetCotizacion', {
                caption: "Agregar&nbsp;&nbsp;",
                buttonicon: "ui-icon-plus",
                onClickButton: function() {
                    nuevaPSM();
                },
                position: "last"
            })
            .navSeparatorAdd()


            .navButtonAdd('#ptblDetCotizacion', {
                caption: "Agregar Material&nbsp;&nbsp;",
                buttonicon: "ui-icon-plus",
                onClickButton: function() {
                    addMaterial();
                },
                position: "last"
            })
            .navSeparatorAdd()

            /*  .navButtonAdd('#ptblDetCotizacion',{
                caption:"Crear Material&nbsp;&nbsp;",
                buttonicon:"ui-icon-plus",
                onClickButton: function(){
                    crearmaterial();
                },
                position:"last"
            })
            .navSeparatorAdd()*/

            .navButtonAdd('#ptblDetCotizacion', {
                caption: "Opcional&nbsp;&nbsp;",
                buttonicon: "ui-icon-pencil",
                onClickButton: function() {
                    addopcional();
                },
                position: "last"
            })
            .navSeparatorAdd()

        /* .navButtonAdd('#ptblDetCotizacion',{
             caption:"Imprimir&nbsp;&nbsp;",
             buttonicon:"ui-icon-pencil",
             onClickButton: function(){
                 imprimir();
             },
             position:"last"
         })
         .navSeparatorAdd()*/
        ;
    }


    function imprimir() {
        var selr = $('#tblDetCotizacion').jqGrid('getGridParam', 'selrow');
        var row = $("#tblDetCotizacion").jqGrid('getRowData', selr);

        host = '<?php echo $this->util()->getPath(); ?>report/';
        window.open(host + "rptCotizacion.php?idCotiz=" + $("#idcotizacion").val(), '_blank');
        //console.log(host);

    }

    // -----> Borrar============================================00
    function btndelete(cellvalue, options, rowObject) {

        return '<div align="center" class="ui-pg-button " ' +
            'title="Borrar" style="text-align:center;float: left; cursor: pointer; display: block;" ' +
            'onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
            'onclick="eliminardetcotiz(\'' + options.rowId + '\');"><div class="ui-pg-div  ui-inline-edit" >' +
            '<span class="ui-icon ui-icon-trash"></span></div></div>';
    }

    function eliminardetcotiz(rowId) {

        var row = jQuery("#tblDetCotizacion").jqGrid('getRowData', rowId);
        openDialogConfirm1("Eliminar Registro?", 350, {
            "Si": function() {
                var parmter = {};
                parmter.idDetCotiz = row.idDetCotiz;
                closeDialog("jqDialogConfirmacion1");
                $.post(path + "cotizacion/detcotizaciondel", parmter, updCheckdelete, 'json');
            },
            "No": function() {
                //ProcesoBuscarRuta(''); chkrecep_5
                closeDialog("jqDialogConfirmacion1");

            }
        });
    }

    function updCheckdelete(data) {
        //console.log(data);
        /*{ "Aceptar": function() { closeDialog("jqDialogInfo"); }} */
        lastsel3 = undefined
        buscardetCotizacion();
        /*openDialogInfo("Eliminado", "250", "150", null, function () {
             lastsel3=undefined
            buscardetCotizacion();

        });*/
    }



    // -----> Calcular============================================00
    function btncalcular(cellvalue, options, rowObject) {

        return '<div align="center" class="ui-pg-button " ' +
            'title="Calcular" style="text-align:center;float: left; cursor: pointer; display: block;" ' +
            'onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
            'onclick="Calculadetcotiz(\'' + options.rowId + '\');"><div class="ui-pg-div  ui-inline-edit" >' +
            '<span class="ui-icon ui-icon-calculator"></span></div></div>';
    }


    function Calculadetcotiz(rowId) {
        var row = jQuery("#tblDetCotizacion").jqGrid('getRowData', rowId);
        calcular();

        actualizarcantdetalleCot();
    }


    buscardetCotizacion = function() {
        var params = '[' +
            '["@p1_cod", ""],' +
            '["@p2_idcotizacion", "' + $("#idcotizacion").val() + '"]' +
            ']';
        parameters = {
            "name": "tblDetCotizacion",
            "procedure": "buscar_detcotizacion",
            "print": "true",
            "parameters": params
        };

        procesarProcedimientoJSON(
            "panelDetCotizacion", "tblDetCotizacion", optionDetCoti, parameters, null, buttonsGridDetcoti
        );
    };


    //Funcion para regresar al la grilla naterior
    function Cancelar() {
        window.open(path + "cotizacion/cotizacion", "_self");
    }

    //Para ver si tiene que el campo de descuento activado, entonces se muestran el campo en las dos grillas
    habilitarColumna = function(val) {
        if (val == '1') {
            jQuery("#tblDetCotizacion").jqGrid('showCol', "nDesc");
            jQuery("#tblDetCotizacionOPC").jqGrid('showCol', "nDesc");
        }
    };


    actualizarcantdetalleCot = function() {
        jQuery('#tblDetCotizacion').jqGrid('saveRow', lastsel3);
        var rows = jQuery("#tblDetCotizacion").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                parameters = {
                    "idDetCotiz": row.idDetCotiz,
                    "nPrecUnit": row.nPrecUnit,
                    "nCantidad": row.nCantidad,
                    "nPrecTotal": row.nPrecTotal,
                    "nDescu": row.nDesc
                };
                $.ajax({
                    url: jQuery.scriptPath + "index.php/cotizacion/detcotizacionupdate",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function(data) {},
                    success: function(requestData) {

                    },
                    error: function(requestData, strError, strTipoError) {},
                    complete: function(requestData, exito) {}
                });
            }
        }

    }
    //Grilla Opcional ====================================================================
    var lastsel2;
    optionDetCotiOPC = {
        datatype: "local",
        width: 1280,
        height: 120,
        keys: true,
        rowNum: 80,
        colNames: [
            'Id',
            'Id cot',
            'Modelo',
            'Producto o Servicio',
            'Descripcion',
            'PU',
            'Cantidad',
            '% Descuento',
            'Valor Venta',
            'estado',
            'orden',
            "opcional",
            "tipops",
            "idprodserv",
            "",
            "",
            "",
            "Ficha Técnica",
            "",
            "",
            ""

        ],
        colModel: [{
                name: 'idDetCotiz',
                index: 'idDetCotiz',
                width: 60,
                hidden: true
            },
            {
                name: 'idCotiz',
                index: 'idCotiz',
                width: 60,
                hidden: true
            },
            {
                name: 'modelo',
                index: 'modelo',
                width: 140
            },
            {
                name: 'vNombrePSM',
                index: 'vNombrePSM',
                width: 200
            },
            {
                name: 'vDescrip',
                index: 'vDescrip',
                width: 280,
                editable: false,
                edittype: "text"
            },
            {
                name: 'nPrecUnit',
                index: 'nPrecUnit',
                width: 70,
                editable: true,
                edittype: "text",
                editoptions: {
                    dataInit: function(elem) {
                        setTimeout(function() {
                            $(elem).numeric();
                        }, 100);
                    }
                }
            },
            {
                name: 'nCantidad',
                index: 'nCantidad',
                width: 70,
                editable: true,
                editoptions: {
                    dataInit: function(elem) {
                        setTimeout(function() {
                            $(elem).numeric();
                        }, 100);
                    }
                }
            },
            {
                name: 'nDesc',
                index: 'nDesc',
                width: 70,
                hidden: true,
                editable: true,
                editoptions: {
                    dataInit: function(elem) {
                        setTimeout(function() {
                            $(elem).numeric();
                        }, 100);
                    }
                }
            },
            {
                name: 'nPrecTotal',
                index: 'nPrecTotal',
                width: 70,
                editable: true,
                editoptions: {
                    dataInit: function(elem) {
                        setTimeout(function() {
                            $(elem).numeric();
                        }, 100);
                    }
                }
            },
            {
                name: 'vEstado',
                index: 'vEstado',
                width: 100,
                hidden: true,
                editable: false
            },
            {
                name: 'nOrden',
                index: 'nOrden',
                width: 200,
                hidden: true
            },
            {
                name: 'opcional',
                index: 'opcional',
                width: 200,
                hidden: true
            },
            {
                name: 'tipoPS',
                index: 'tipoPS',
                width: 200,
                hidden: true
            },
            {
                name: 'idProdServ',
                index: 'idProdServ',
                width: 200,
                hidden: true
            },
            {
                name: 'vEstado',
                index: 'vEstado',
                width: 30,
                hidden: false,
                editOptions: {
                    value: "1:0",
                    defaultvalue: "1"
                },
                formatter: chkPasarPrincipal
            },
            {
                name: 'btndocumall',
                index: 'btndocumall',
                width: 40,
                align: 'center',
                formatter: btncalcularop,
                search: false
            },
            {
                name: 'btndocumall',
                index: 'btndocumall',
                width: 40,
                align: 'center',
                formatter: btndeleteop,
                search: false
            },
            {
                name: 'docadjunto',
                index: 'docadjunto',
                width: 250,
                align: 'left',
                formatter: linkadjunto
            },
            {
                name: 'docadjunto',
                index: 'docadjunto',
                width: 250,
                align: 'left',
                hidden: true
            },
            {
                name: 'visor',
                index: 'visor',
                width: 20
            },
            {
                name: 'trash',
                index: 'trash',
                width: 20
            }

        ],
        editurl: "clientArray",
        caption: "&nbsp;&nbsp;&nbsp;Detalle de la Cotizacion Opcional",
        ondblClickRow: function(id) {
            var row = $(this).getRowData(id);
            //console.log(row);
            //dobleclickPersona(row);
            //  verCotizacion();
        },
        afterInsertRow: function(rowid, aData) {
            switch (aData.opcional) {
                case '':
                    break;
                case '2':
                    jQuery("#tblDetCotizacionOPC").jqGrid('setCell', rowid, 'idDetCotiz', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacionOPC").jqGrid('setCell', rowid, 'idCotiz', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacionOPC").jqGrid('setCell', rowid, 'modelo', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacionOPC").jqGrid('setCell', rowid, 'vNombrePSM', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacionOPC").jqGrid('setCell', rowid, 'vDescrip', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacionOPC").jqGrid('setCell', rowid, 'nPrecUnit', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacionOPC").jqGrid('setCell', rowid, 'nCantidad', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacionOPC").jqGrid('setCell', rowid, 'nDesc', '', {
                        background: '#ddeaa6'
                    });
                    jQuery("#tblDetCotizacionOPC").jqGrid('setCell', rowid, 'nPrecTotal', '', {
                        background: '#ddeaa6'
                    });
                    break;
            }
        },
        onSelectRow: function(id) {
            //var row = $(this).getRowData(id);
            // console.log(lastsel3);
            if (lastsel3 != undefined)
                calcular();
            if (lastsel2 != undefined)
                calcularOpc();

            if (id && id !== lastsel2) {
                jQuery('#tblDetCotizacionOPC').jqGrid('saveRow', lastsel2);
                lastsel2 = id;
            }
            jQuery('#tblDetCotizacionOPC').jqGrid('editRow', id, true);

        },
        gridComplete: function(id) {
            habilitarColumna("<?php echo $this->clientetec ?>");

            isGridComplete = true;
            $("#tblDetCotizacionOPC").jqGrid('setSelection', 1, true);

            var ids = jQuery("#tblDetCotizacionOPC").jqGrid('getDataIDs');

            for (var i = 0; i < ids.length; i++) {
                var cl = ids[i];
                var rowdat = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData', cl);
                buttvisor = '<div title="Visor de ' + rowdat.idProdServ + '" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\')" onclick="visorarchivo(\'' + rowdat.docadjunto + '\');"><span class="ui-icon ui-icon-search"></span></div>';

                jQuery("#tblDetCotizacionOPC").jqGrid('setRowData', ids[i], {
                    visor: buttvisor
                });
                if ('' == '1') {
                    butttrash = '<div title="Eliminar ' + rowdat.vadjunto + '" style="float: left; cursor: pointer; display: block;" class="ui-pg-div ui-inline-edit"  onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\')" onclick="eliminarDocAdjunto(\'' + rowdat.idsigma + '\');"><span class="ui-icon ui-icon-trash"></span></div>';

                    jQuery("#tblDetCotizacionOPC").jqGrid('setRowData', ids[i], {
                        trash: butttrash
                    });
                }
            }
        },
        aftersavefunc: function(rowid) { // can add jqXHR, sentData, options
            alert(rowid + " is saved");
        }
    };

    function chkPasarPrincipal(cellvalue, options, rowObject) {
        return '<input  type="checkbox" id="chkconcluirexp_' + options.rowId + '" ' + (cellvalue == '1' ? ' checked="checked"' : '') +
            'onclick="changecheckboxdisabled(' + options.rowId + ')" ' + (cellvalue == '0' ? '  ' : '') + '/>';
    }

    function changecheckboxdisabled(rowId) {

        var row = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData', rowId);
        openDialogConfirm1("El producto/Servicio pasara a la grilla Principal?", 350, {
            "Si": function() {
                var parmter = {};
                parmter.idDetCotiz = row.idDetCotiz;
                closeDialog("jqDialogConfirmacion1");
                // $.post(path + "cotizacion/productdel", parmter, updCheckconcluir, 'json');
                $.ajax({
                    url: jQuery.scriptPath + "index.php/cotizacion/cotizacionopcionalapricipal",
                    type: 'POST',
                    cache: false,
                    data: parmter,
                    beforeSend: function(data) {},
                    success: function(requestData) {
                        buscardetCotizacionOpcional();
                        buscardetCotizacion();
                        //window.open(path + "cotizacion/cotizacion", "_self");
                    },
                    error: function(requestData, strError, strTipoError) {},
                    complete: function(requestData, exito) {}
                });

            },
            "No": function() {
                //ProcesoBuscarRuta(''); chkrecep_5
                $("#chkconcluirexp_" + rowId).attr('checked', true);
                closeDialog("jqDialogConfirmacion1");

            }
        });
    }
    // -----> Borrar opcional ============================================00
    function btndeleteop(cellvalue, options, rowObject) {

        return '<div align="center" class="ui-pg-button " ' +
            'title="Borrar" style="text-align:center;float: left; cursor: pointer; display: block;" ' +
            'onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
            'onclick="eliminardetcotizop(\'' + options.rowId + '\');"><div class="ui-pg-div  ui-inline-edit" >' +
            '<span class="ui-icon ui-icon-trash"></span></div></div>';
    }

    function eliminardetcotizop(rowId) {

        var row = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData', rowId);
        openDialogConfirm1("Eliminar Registro?", 350, {
            "Si": function() {
                var parmter = {};
                parmter.idDetCotiz = row.idDetCotiz;
                closeDialog("jqDialogConfirmacion1");
                $.post(path + "cotizacion/detcotizaciondel", parmter, updCheckdeleteop, 'json');
            },
            "No": function() {
                //ProcesoBuscarRuta(''); chkrecep_5
                closeDialog("jqDialogConfirmacion1");

            }
        });
    }

    function updCheckdeleteop(data) {
        //console.log(data);
        /*{ "Aceptar": function() { closeDialog("jqDialogInfo"); }} */
        lastsel2 = undefined
        buscardetCotizacionOpcional();
        /*openDialogInfo("Eliminado", "250", "150", null, function () {
         lastsel3=undefined
         buscardetCotizacion();

         });*/
    }
    // -----> Calcular============================================00
    function btncalcularop(cellvalue, options, rowObject) {

        return '<div align="center" class="ui-pg-button " ' +
            'title="Calcular" style="text-align:center;float: left; cursor: pointer; display: block;" ' +
            'onmouseover="jQuery(this).addClass(\'ui-state-hover\');" onmouseout="jQuery(this).removeClass(\'ui-state-hover\');" ' +
            'onclick="Calculadetcotizop(\'' + options.rowId + '\');"><div class="ui-pg-div  ui-inline-edit" >' +
            '<span class="ui-icon ui-icon-calculator"></span></div></div>';
    }


    function Calculadetcotizop(rowId) {
        var row = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData', rowId);
        calcularOpc();

        actualizarcantdetalleCotop();
    }

    actualizarcantdetalleCotop = function() {
        jQuery('#tblDetCotizacionOPC').jqGrid('saveRow', lastsel2);
        var rows1 = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData');
        if (rows1.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows1.length; i++) {
                var row = rows1[i];
                parameters = {
                    "idDetCotiz": row.idDetCotiz,
                    "nPrecUnit": row.nPrecUnit,
                    "nCantidad": row.nCantidad,
                    "nPrecTotal": row.nPrecTotal,
                    "nDescu": row.nDesc
                };
                $.ajax({
                    url: jQuery.scriptPath + "index.php/cotizacion/detcotizacionupdate",
                    type: 'POST',
                    cache: false,
                    data: parameters,
                    beforeSend: function(data) {},
                    success: function(requestData) {

                    },
                    error: function(requestData, strError, strTipoError) {},
                    complete: function(requestData, exito) {}
                });
            }
        }

    }
    buscardetCotizacionOpcional = function() {
        var params = '[' +
            '["@p1_cod", ""],' +
            '["@p2_idcotizacion", "' + $("#idcotizacion").val() + '"]' +
            ']';
        parameters = {
            "name": "tblDetCotizacionOPC",
            "procedure": "buscar_detcotizacionOpcional",
            "print": "true",
            "parameters": params
        };

        procesarProcedimientoJSON(
            "panelDetCotizacionOPC", "tblDetCotizacionOPC", optionDetCotiOPC, parameters, null, buttonsGridDetcotiOPC
        );
    };

    function buttonsGridDetcotiOPC() {
        $("#tblDetCotizacionOPC")
            .navGrid('#ptblDetCotizacionOPC', {
                edit: false,
                add: false,
                del: false,
                search: false,
                refresh: false
            })

            .navButtonAdd('#ptblDetCotizacionOPC', {
                caption: "Agregar&nbsp;&nbsp;",
                buttonicon: "ui-icon-plus",
                onClickButton: function() {
                    addopcional();
                },
                position: "last"
            })
            .navSeparatorAdd()


            .navButtonAdd('#ptblDetCotizacionOPC', {
                caption: "Agregar Material&nbsp;&nbsp;",
                buttonicon: "ui-icon-plus",
                onClickButton: function() {
                    addMaterial1();
                },
                position: "last"
            })
            .navSeparatorAdd()

        /*  .navButtonAdd('#ptblDetCotizacion',{
            caption:"Crear Material&nbsp;&nbsp;",
            buttonicon:"ui-icon-plus",
            onClickButton: function(){
                crearmaterial();
            },
            position:"last"
        })
        .navSeparatorAdd()

        .navButtonAdd('#ptblDetCotizacion',{
            caption:"Opcional&nbsp;&nbsp;",
            buttonicon:"ui-icon-pencil",
            onClickButton: function(){
                addopcional();
            },
            position:"last"
        })
        .navSeparatorAdd()

        .navButtonAdd('#ptblDetCotizacion',{
         caption:"Imprimir&nbsp;&nbsp;",
         buttonicon:"ui-icon-pencil",
         onClickButton: function(){
         imprimir();
         },
         position:"last"
         })
         .navSeparatorAdd()*/
        ;
    }


    function calcularOpc() {

        var rows = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData');
        if (rows.length > 0) {} else {
            return;
        }

        if (document.getElementById('chkClitec').checked == true) {
            var tieneDes = 'SI';
        } else {
            var tieneDes = 'NO';
        }
        //console.log(lastsel2);
        if (lastsel2 == undefined) {
            lastsel2 = 1;
        }
        //console.log(lastsel2);
        jQuery('#tblDetCotizacionOPC').jqGrid('saveRow', lastsel2);
        gsrr = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData');
        //var nrowid = $('#tblDetCotizacion').jqGrid('getGridParam','selrow');
        var subtot = (gsrr[lastsel2 - 1].nPrecUnit) * (gsrr[lastsel2 - 1].nCantidad);
        if (tieneDes == "SI") {
            var pdesc = gsrr[lastsel2 - 1].nDesc;
        } else {
            var pdesc = 0;
        }
        var total1 = subtot - (subtot * pdesc / 100);
        $("#tblDetCotizacionOPC").setRowData(lastsel2, {
            nPrecTotal: parseFloat(Math.round(total1 * 100) / 100).toFixed(2) 
        });

        var rows = jQuery("#tblDetCotizacionOPC").jqGrid('getRowData');
        if (rows.length > 0) {
            var subtotal = 0;
            for (var i = 0; i < rows.length; i++) {
                var row = rows[i];
                if (row.opcional != '1') {
                    var subt = parseFloat(row.nPrecTotal);
                    subtotal = subtotal + subt;
                } else {}
            }
            var igv = (subtotal * 8) / 100;
            var total = igv + subtotal;
            // $("#txtsubtotal").val(subtotal);
            //  $("#txtigv").val(parseFloat(Math.round(igv * 100) / 100).toFixed(2));
            //  $("#txttotal").val(parseFloat(Math.round(total * 100) / 100).toFixed(2));
        }
        return true;
    };




    $(function() {
        $("#fecdesde").datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });
        $("#fechasta").datepicker({
            showOn: "button",
            buttonImage: pathImage + "calendar.gif",
            buttonImageOnly: true,
            dateFormat: "dd/mm/yy"
        });




        buscardetCotizacion();
        var tieneop = <?php echo $this->tieneop; ?>;
        if (tieneop == 1) {
            buscardetCotizacionOpcional();
        }
        var titulo = "<?php echo $this->vMotivo; ?>";
        var miObjeto = ["SISTEMA CCTV HDCVI - HD",
            "SISTEMA CCTV HDCVI - FULL HD",
            "SISTEMA CCTV HDCVI - FULL HD Varifocal",
            "SISTEMA CCTV HDCVI - 2K",
            "SISTEMA CCTV IP - FULL HD",
            "SISTEMA CCTV IP - FULL HD Varifocal",
            "SISTEMA CCTV IP - 2K",
            "SISTEMA CCTV IP - 4K",
            "OTROS"
        ];
        var estado = 0;
        miObjeto.forEach(function(valor, indice, array) {
            //console.log("En el índice " + indice + " hay este valor: " + valor);
            //console.log("En ttulo " +titulo);
            //console.log("ttulo " +valor);
            if (valor == titulo) {
                estado = 1;
            }
        });
        if (estado == 0) {
            $(".titulotext").show();
        }

        var titulo1 = "<?php echo $this->nreferencial; ?>";
        var miObjeto1 = ["Seleccione",
            "LOS PRECIOS DE MATERIALES Y SERVICIOS SON REFERENCIALES PREVIA VISITA T&Eacute;CNICA SEG&Uacute;N CONFIRMACI&Oacute;N",
            "OTRO"
        ];
        var estado1 = 0;
        miObjeto1.forEach(function(valor, indice, array) {
            //console.log("En el índice " + indice + " hay este valor: " + valor)
            //console.log("En ttulo " +titulo1);
            //console.log("ttulo " +valor);
            if (valor == titulo1 || trim(titulo1) == "") {
                estado1 = 1;
            }
        });
        if (estado1 == 0) {
            $(".referencialtext").show();
        }

        //Para mostrar la descripcion de la nota de pago  ===> INICIO
        var titulo2 = "<?php echo $this->vFormaPago; ?>";
        var miObjeto2 = ["Al contado",
            "Adelanto del 50% del total y al finalizar el pago del 50% con la conformidad de la Obra",
            "OTRO"
        ];
        var estado2 = 0;
        miObjeto2.forEach(function(valor, indice, array) {
            //console.log("En el índice " + indice + " hay este valor: " + valor)
            //console.log("En ttulo " +titulo2);
            //console.log("ttulo " +valor);
            if (valor == titulo2 || trim(titulo2) == "") {
                estado2 = 1;
            }
        });
        if (estado2 == 0) {
            $(".formapagotext").show();
        }
        //FIN<==========






        $("#btnbuscar").button({
            icons: {
                primary: "ui-icon-search"
            }
        });
        $("#btnguardar").button({
            icons: {
                primary: "ui-icon-disk"
            }
        });
        $("#btncancelardet").button({
            icons: {
                primary: "ui-icon-cancel"
            }
        }).click(function() {
            parameters = {
                "idCotiz": $("#idcotizacion").val()
            };
            $.ajax({
                url: jQuery.scriptPath + "index.php/cotizacion/cancelarcotiz",
                type: 'POST',
                cache: false,
                data: parameters,
                beforeSend: function(data) {},
                success: function(requestData) {},
                error: function(requestData, strError, strTipoError) {
                    $("#result").html("Error " + strTipoError + ': ' + strError);
                },
                complete: function(requestData, exito) {}
            });
            Cancelar('');

        });


        /* $("#btnbuscardocs").button({icons: {primary: "ui-icon-search"}}).click(function () {
             ProcesoBuscarRuta('');
         });*/
    });

    function reiniCombo(celement) {
        var xelem = $("#" + celement);
        xelem.combobox("destroy");
        $("option:selected", xelem).removeAttr("selected");
        $("option[value='9999999999']", xelem).attr("selected", "selected");
        //xelem.combobox();
    }

    function visorarchivo(nom_archivo) {
        /*openDialogDataFunction1("documentos/ddocumentomante", { type: "M", ddocument: row.idsigma,cidsigma :$('#cidsigma').val(),ctipjerar: $('#ctipjerar').val() }, "980", "630", "Modificar Documento " + row.dstipdocu, null, { 'Aceptar': function() { DdocumentoSave('M'); }, 'Cancelar': function() { closeDialog("jqDialog1"); } });*/
        //http://localhost:81/titaniaSQL/public/uploadDdocuments/
        //console.log(jQuery.scriptPath+'uploadDdocuments/'+nom_archivo);
        var page = '';
        arrarchivo = nom_archivo.split(".");
        extarchivo = arrarchivo[1];

        if (extarchivo == 'png' || extarchivo == 'jpg' || extarchivo == 'gif') {

            if (navigator.appName == 'Microsoft Internet Explorer') {

                var ver = getInternetExplorerVersion();
                if (ver > -1) {
                    // alert(ver);
                    if (ver <= 9.0) {
                        page = jQuery.scriptPath + 'FichaTecnica/' + nom_archivo;
                        var $dialog = $('<div></div>')
                            .html('<div align="center"><iframe style="border: 0px; " src="' + page + '" width="700" height="600"></iframe></div>')
                            .dialog({
                                autoOpen: false,
                                modal: true,
                                height: 700,
                                width: 800,
                                title: "Visor de Archivos"
                            });
                        $dialog.dialog('open');

                    }
                } else {
                    page = path + "mantenimientos/visordocs?img=" + nom_archivo;
                    var $dialog = $('<div></div>')
                        .load(page)
                        .dialog({
                            autoOpen: false,
                            modal: true,
                            height: 650,
                            width: 800,
                            title: "Visor de Archivos"
                        });
                    $dialog.dialog('open');


                }
            } else {

                page = path + "mantenimientos/visordocs?img=" + nom_archivo;
                var $dialog = $('<div></div>')
                    .load(page)
                    .dialog({
                        autoOpen: false,
                        modal: true,
                        height: 650,
                        width: 800,
                        title: "Visor de Archivos"
                    });
                $dialog.dialog('open');

            }




        } else {
            page = jQuery.scriptPath + 'FichaTecnica/' + nom_archivo;
            var $dialog = $('<div></div>')
                .html('<div align="center"><iframe style="border: 0px; " src="' + page + '" width="700" height="600"></iframe></div>')
                .dialog({
                    autoOpen: false,
                    modal: true,
                    height: 700,
                    width: 800,
                    title: "Visor de Archivos"
                });
            $dialog.dialog('open');
        }
    }
</script>