<div id="panelMantenimientoProductos" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 455px;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Mantenimiento de Activos</label>
    </div>
    <form id="frmmaterial" name="frmmaterial" method="post">
        <table border="0" class="ui-table-panelLayout">
            <tr>
                <td style="text-align: left">
                    C&oacute;digo
                </td>
                <td style="text-align: left">
                    <input class="editable ui-text" style="background-color: #e4e4e4;" type="text" id="txtidsigma" name="txtidsigma" value="<?php echo $this->idsigma; ?>" readonly="readonly" />
                </td>
            </tr>
            <tr>
                <td style="text-align: left">
                    Nombres
                </td>
                <td style="text-align: left">
                    <input class="editable ui-text" size="50" style="" type="text" id="txtvnombreMat" name="txtvnombreMat" value="<?php echo $this->vNombre; ?>" />
                </td>
            </tr>
            <tr>
                <td style="text-align: left">
                    Serie
                </td>
                <td style="text-align: left">
                    <input class="editable ui-text" size="25" style="" maxlength="25" type="text" id="txtSerie" name="txtSerie" value="<?php echo $this->vSerie; ?>" />
                </td>
            </tr>
            <tr>
                <td style="text-align: left">
                    Marca
                </td>
                <td style="text-align: left">
                    <input class="editable ui-text" size="50" style="" type="text" id="txtmarca" name="txtmarca" value="<?php echo $this->vMarca; ?>" />
                </td>
            </tr>
            <tr>
                <td style="text-align: left">
                    Modelo
                </td>
                <td style="text-align: left">
                    <input class="editable ui-text" size="50" style="" type="text" id="txtmodelo" name="txtmodelo" value="<?php echo $this->vMarca; ?>" />
                </td>
            </tr>


            <tr>
                <td style="text-align: left">
                    Descripci&oacute;n
                </td>
                <td style="text-align: left">
                    <textarea class="editable ui-text" style="width:300px; height:100px;max-width:300px; max-height:100px;" id="txtdescrip" name="txtdescrip"><?php echo $this->vDescrip; ?></textarea>
                </td>
            </tr>
            <tr>
                <td style="text-align: left">
                    Stock
                </td>
                <td style="text-align: left">
                    <input class="editable ui-text" size="20" style="" maxlength="6" type="number" id="txtStock" name="txtStock" value="<?php echo $this->nStock; ?>" />
                </td>
            </tr>
            <tr style="display: block">
                <td style="text-align: left">
                    <input type="checkbox" name="estado" value="1" id="estado" class="ui-text" <?php if ($this->nestado != '') {
                                                                                                    if ($this->nestado == 1) {
                                                                                                        echo 'checked';
                                                                                                    }
                                                                                                } else {
                                                                                                    echo 'checked';
                                                                                                } ?>> Estado
                </td>

            </tr>

            <tr>
                <td colspan="2" style="text-align: center;">
                    <button type="button" style="width:120px;" id="btnguardarperson" name="btnguardarperson" onclick="guardaractivos()">
                        Guardar
                    </button>
                    <button type="button" style="width:120px;" id="btncancelperson" name="btncancelperson" onclick="cerrarMantProd()">
                        Cancelar
                    </button>
                </td>
            </tr>
        </table>
    </form>
</div>
<script type="text/javascript">
    $("#btnguardarperson").button({
        icons: {
            primary: 'ui-icon-disk'
        },
        text: true
    });

    $("#btncancelperson").button({
        icons: {
            primary: 'ui-icon-close'
        },
        text: true
    });
    themeComboBox("#cbocatego");
    themeComboBox("#cboUnidadMed");

    function cerrarMantProd() {
        closeDialog("jqDialog3");
    }

    function guardaractivos() {
        var vnombre = $("#txtvnombreMat").val();
        var vSerie = $("#txtSerie").val();
        var form = $("#frmmaterial");
        var catego = $("#cbocatego").val();

        var unM = $("#cboUnidadMed").val();

        if (document.getElementById("estado").checked) {
            var nestado1 = 1;
        } else {
            var nestado1 = 0;
        }

        if ($.trim(vnombre) == "") {
            openDialogError("Ingrese nombre", "250", "150", function() {
                $("#txtvnombreMat").focus();
            });
            return;
        }
        if ($.trim(catego) == "9999999999") {
            openDialogError("Seleccione Categoria", "250", "150", function() {
                $("#txtvnrodoc").focus();
            });
            return;
        }

        if ($.trim(vSerie) == "") {
            openDialogError("Ingrese la Serie", "250", "150", function() {
                $("#txtSerie").focus();
            });
            return;
        }


        $.ajax({
            dataType: "html",
            type: "POST",
            url: path + "mantenimientos/guardaractivos/", // Ruta donde se encuentra nuestro action que procesa la peticion XmlHttpRequest
            data: form.serialize() + "&estado=" + nestado1,
            success: function(requestData) { //Llamada exitosa)
                var datos = JSON.parse(requestData);
                if (datos[0][1] == "Err") {
                    openDialogInfo(datos[0][2]);
                } else {
                    openDialogInfo("Registrado correctamente");
                    $("#c_codigocontrib").val(requestData);
                    buscarActivos();
                    cerrarMantProd();
                }

            },
            error: function(requestData, errNumber, errMessage) {
                if (errNumber == '') {
                    openDialogError("No se puede determinar el error.");
                } else {
                    openDialogError(errNumber + ': ' + errMessage);
                }
            }
        });
    }




    $(document).ready(function() {


    });
</script>