<div id="panelMantenimientoProducto" align="center" class="ui-widget ui-widget-content ui-corner-top" style="width: 99%;margin: 3px; height:95%;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Mantenimiento Tasa de cambio</label>
    </div>
    <div id="dialogBuscarContribuyentePredio">
        <table class="ui-panelLayout-main">
            <tr>
                <td style="vertical-align: top;">
                    <table border="0" style="margin-left:45px;">
                        <tr class="rowBuscarContribuyente">

                            <td width="200" style="text-align: left">C&oacute;digo:</td>
                            <td width="10">&nbsp;</td>
                            <td width="200">Fecha Hasta:</td>
                            <td width="230">&nbsp;</td>
                            <td width="10">&nbsp;</td>
                            <td width="230" colspan="5" style="text-align: left"></td>
                            <td width="20">&nbsp;</td>
                        </tr>
                        <tr class="rowBuscarContribuyente" id="panelBuscarContribuyente">

                            <td>
                                <input type="text" id="fecdesde" class="ui-text" value="<?php echo $this->fechaini; ?>" style="text-align: left;width: 100px;"/>
                            </td>

                            <td>&nbsp;</td>
                            <td colspan="2">
                                <input type="text" id="fechasta" class="ui-text" value="<?php echo $this->fechafin; ?>" style="text-align: left;width: 100px;"/>
                            </td>


                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td colspan="5" style="text-align: left; display: none">
                                <input class="ui-text pnl" id="c_desc" onkeypress="if(event.keyCode==13){buscarTasa();}" style="width:50%" />
                            </td>
                            <td>
                                <button id="btnbuscar" name="btnbuscar" onclick="buscarTasa()">Buscar</button>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="13" height="8px"></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <div id="dialogMensaje">
    </div>

    <div id="panelListaTasaC" align="left" style="width: 99%;margin: 20px;">
        <table id="tblListaTasaC"></table>
        <div id="ptblListaTasaC"></div>
    </div>
    <br/>
</div>
<script type="text/javascript">
    optionTasac = {
        width: 600,
        height: 250,
        colNames: [
            'ID',
            'Tasa',
            'Fecha',
            'Estado'
        ],
        colModel: [
            {name: 'idtasa', index:'idtasa', width:100, align: "center"},
            {name: 'ntasa', index:'ntasa', width:250, align: "center"},
            {name: 'dfecha', index:'dfecha', width:200, align: "center"},
            {name: 'vEstado', index:'vEstado', width:50, hidden: true, editOptions:{value:"1:0",defaultvalue:"1"},formatter:'checkbox'}
        ],
        caption: "&nbsp;&nbsp;&nbsp;Tasa de cambio Registrados",
        ondblClickRow: function(id){
            var row = $(this).getRowData(id);
            verPersona();
        },

        afterInsertRow:function(rowid,aData){
        switch(
                aData.nestado
            ){case'1':
                break;
            case '0':

                jQuery("#tblListaTasaC").jqGrid('setCell',rowid,'cidpers','',{color:'red'});
                jQuery("#tblListaTasaC").jqGrid('setCell',rowid,'crazsoc','',{color:'red'});
                jQuery("#tblListaTasaC").jqGrid('setCell',rowid,'vnrodoc','',{color:'red'});
                jQuery("#tblListaTasaC").jqGrid('setCell',rowid,'nestado','',{color:'red'});
                break;
       }
        },
        onSelectRow: function(id) {
            var row = $(this).getRowData(id);
        }
    };



    eliminar=function(a){
        var selr = $('#tblListaTasaC').jqGrid('getGridParam','selrow');
        var row = $("#tblListaTasaC").jqGrid('getRowData', selr);
        if(row.cidpers == "" || row.cidpers == undefined){
            openDialogWarning("Seleccione un registro para eliminar.");
            return;
        }
        parameters = {
           // "idsigma": row.cidpers
        };

        //openDialogData2("mantenimientos/eliminarpersona", parameters, 460);
       openDialogConfirm1("\u00BFEst\u00E1 seguro de eliminar datos?",350,{

           "si":function(){
               //openDialogData2("mantenimientos/eliminarpersona", parameters, 460);
               $.ajax({
                   url: jQuery.scriptPath + "index.php/mantenimientos/eliminarproducto",
                   type: 'POST',
                   cache: false,
                   data: parameters,
                   beforeSend: function (data) {

                   },
                   success: function (requestData) {
                       $("#result").html(requestData);
                       closeDialog("jqDialogConfirmacion1");
                       closeDialog('jqDialog2');
                       $("#c_codigocontrib").val("");
                       buscarMate();


                   },
                   error: function (requestData, strError, strTipoError) {
                       $("#result").html("Error " + strTipoError + ': ' + strError);
                   },
                   complete: function (requestData, exito) {
                   }


               });
           },

           "no":function(){
               closeDialog("jqDialogConfirmacion1");

           }
       })


    };

    nuevaPersona = function(){
        parameters = {
            "idsigma": '...'
        };
        openDialogData2("mantenimientos/tasacambio", parameters, 400);
    };
    verPersona = function() {
        var selr = $('#tblListaTasaC').jqGrid('getGridParam','selrow');
        var row = $("#tblListaTasaC").jqGrid('getRowData', selr);
        if(row.idtasa == "" || row.idtasa == undefined){
            openDialogWarning("Seleccione un registro para editar.");
            return;
        }
        parameters = {
            "idsigma": row.idtasa
        };

        openDialogData2("mantenimientos/tasacambio", parameters, 400);

    };


    function buttonsGridPerson(){
        $("#tblListaTasaC")
            .navGrid('#ptblListaTasaC', {edit:false,add:false,del:false,search:false,refresh:false})

            .navButtonAdd('#ptblListaTasaC',{
                caption:"Agregar&nbsp;&nbsp;",
                buttonicon:"ui-icon-plus",
                onClickButton: function(){
                    nuevaPersona();
                },
                position:"last"
            })
            .navSeparatorAdd()


            .navButtonAdd('#ptblListaTasaC',{
                caption:"Editar&nbsp;&nbsp;",
                buttonicon:"ui-icon-pencil",
                onClickButton: function(){
                    verPersona();
                },
                position:"last"
            })
            .navSeparatorAdd()

            .navButtonAdd('#ptblListaTasaC',{
                caption:"Eliminar&nbsp;&nbsp;",
                buttonicon:"ui-icon-pencil",
                onClickButton: function(){
                    eliminar();
                },
                position:"last"
            })
            .navSeparatorAdd()
            /*
            .navButtonAdd('#ptblListaTasaC',{
                caption:"Imprimir&nbsp;&nbsp;",
                buttonicon:"ui-icon-pencil",
                onClickButton: function(){
                    imprimir();
                },
                position:"last"
            })
            .navSeparatorAdd()*/
        ;
    }


    buscarTasa = function() {
        var params = '['

			+ '["@dfecha", "' + $("#fecdesde").val() + '"],'
            + '["@dfin", "' + $("#fechasta").val() + '"]'
            + ']';
        parameters = {
            "name": "tblListaTasaC",
            "procedure": "Bus_TasaCambio",
            "print": "true",
            "parameters": params
        };

        procesarProcedimientoJSON(
            "panelListaTasaC"
            , "tblListaTasaC"
            , optionTasac
            , parameters
            , null
            , buttonsGridPerson
        );
    };

    $(function(){
        $("#fecdesde").datepicker({showOn: "button", buttonImage: pathImage + "calendar.gif", buttonImageOnly: true, dateFormat: "dd/mm/yy"});
        $("#fechasta").datepicker({showOn: "button", buttonImage: pathImage + "calendar.gif", buttonImageOnly: true, dateFormat: "dd/mm/yy"});
        buscarTasa();
        $("#btnbuscar").button();
    });
</script>