<div id="panelMantenimientoProductos"
     align="center"
     class="ui-widget ui-widget-content ui-corner-top"
     style="width: 380px;margin: 3px;">
    <div class="ui-widget ui-state-default ui-corner-top ui-title">
        <label>Mantenimiento de Materiales</label>
    </div>
<form id="frmmaterial" name="frmmaterial" method="post">
    <table border="0" class="ui-table-panelLayout">
        <tr>
            <td style="text-align: left">
                C&oacute;digo
            </td>
            <td style="text-align: left">
                <input class="editable ui-text"
                       style="background-color: #e4e4e4;"
                       type="text"
                       id="txtidsigma"
                       name="txtidsigma"
                       value="<?php echo $this->idtasa; ?>" readonly="readonly"/>
            </td>
        </tr>
        <tr>
            <td style="text-align: left">
                Tasa
            </td>
            <td style="text-align: left">
                <input class="editable ui-text"
                       size="30"
                       style=""
                       type="text"
                       id="txttasa"
                       name="txttasa"
                       value="<?php echo $this->ntasa; ?>"/>
            </td>
        </tr>
        <tr>
            <td style="text-align: left">
                Fecha
            </td>
            <td style="text-align: left">
                <input type="text" id="fecha" name="fecha" class="ui-text" value="<?php echo $this->dfecha; ?>" style="text-align: left;width: 100px;"/>
            </td>
        </tr>

        <tr style="display: none">
            <td style="text-align: left">
                <input type="checkbox" name="estado" value="1" id="estado" offvalue="0" class="ui-text" <?php if ($this->nestado!=''){ if($this->nestado==1){echo 'checked';}}else{echo 'checked';} ?>> Estado
            </td>

        </tr>

        <tr>
            <td colspan="2" style="text-align: center;">
                <button type="button" style="width:120px;" id="btnguardarperson" name="btnguardarperson" onclick="guardarPersona()">
                    Guardar
                </button>
                <button type="button" style="width:120px;" id="btncancelperson" name="btncancelperson" onclick="cerrarMantProd()">
                    Cancelar
                </button>
            </td>
        </tr>
    </table>
</form>
</div>
<script type="text/javascript">
    $("#btnguardarperson").button({
        icons:{primary:'ui-icon-disk'},
        text:true
    });

    $("#btncancelperson").button({
        icons:{primary:'ui-icon-close'},
        text:true
    });
    themeComboBox("#cbocatego");



    function cerrarMantProd(){
        closeDialog("jqDialog2");
    }

    function guardarPersona(){
        var vtasa = $("#txttasa").val();
        var form= $("#frmmaterial");
        var fecha = $("#fecha").val();
      /*  if(document.getElementById("estado").checked){
            var nestado1=1;
        }  else  {
            var  nestado1=0;
        }*/

        if($.trim(vtasa) == ""){
            openDialogError("Ingrese tasa", "250", "150", function() {
                $("#txttasa").focus();
            });
            return;
        }
        if($.trim(fecha) == ""){
            openDialogError("Ingrese fecha", "250", "150", function() {
                $("#fecha").focus();
            });
            return;
        }


        $.ajax({
            dataType: "html",
            type: "POST",
            url: path + "mantenimientos/guardartasacambio/", // Ruta donde se encuentra nuestro action que procesa la peticion XmlHttpRequest
            data:form.serialize() ,
            success: function(requestData){ 	//Llamada exitosa)
                openDialogInfo("Registrado correctamente");
                $("#c_codigocontrib").val(requestData);
                buscarTasa();
                cerrarMantProd();
            },
            error: function(requestData, errNumber, errMessage){
                if(errNumber == '') {
                    openDialogError("No se puede determinar el error.");
                } else {
                    openDialogError(errNumber +': ' + errMessage);
                }
            }
        });
    }




    $( document ).ready(function() {
        $("#fecha").datepicker({showOn: "button", buttonImage: pathImage + "calendar.gif", buttonImageOnly: true, dateFormat: "dd/mm/yy"});

    });
</script>